### ISSUE TITLE
Using a default theme as a showcase and explaining how specific things can be created.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwentyfive#10]
Hi

I am brainstorming here.
Can we use the default theme as a teaching platform at the same time?
Perhaps in the design add links to important resources. Perhaps include some text as to how some of the design is created.
I am looking for ways in how one shares information in a teachable way to where someone can look at the design and get some information at the same time.
Thanks.

**Comment by jenxi** [comment]
Maybe we can start by listing down the features to highlight and move on to creating the guide? Would the target audience would be someone completely new to WordPress? Or someone new to block themes?

**Comment by karmatosed** [comment]
As we look to develop the theme I think having actionable issues in this repo makes sense. That brings me to this one. I think this is more of a desire and something that can fall into action once the theme has been created. With that in mind I would recommend perhaps not having it sit as an issue and either:

- Think of a deliverable documentation issue from this and put it in that team for when theme is created.
- Consider it once theme is made and close this for now.

**Comment by carolinan** [comment]
I agree that this is not actionable right now.
There is no room in the theme itself to include how-to guides; for example, neither theme.json or the template files can have comments.
