### ISSUE TITLE
Use a native Forms block on a contact page

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwentyfive#11]
Hi

An experimental Forms block has been created but it is not working yet.
Forms block label
https://github.com/WordPress/gutenberg/labels/%5BBlock%5D%20Form%20%28experimental%29

A contact form page can be created for the theme showing the new Forms block included in Gutenberg. That means over the next months getting some focused attention on getting a workable Forms block in place.

**Comment by karmatosed** [comment]
I have updated the title to reflect what I think is the requirement here of the theme. This can focus on whether this gets added as a feature or not, then the work to be done upstream needs to be decided.

**Comment by carolinan** [comment]
I do not believe that it will be possible to stabilize the form blocks for 6.7.

**Comment by paaljoachim** [comment]
Hi @carolinan I thought I would atleast mention it as a possibility. Leaving it open as a possibility. We will just see how things go.

**Comment by carolinan** [comment]
This block has not been stabilised in this release cycle.
