### ISSUE TITLE
More granular size options than previous themes

### ISSUE THREAD

**Issue by JosVelasco** [WordPress/twentytwentyfive#12]
Generally, implementing websites from a given design works better with each iteration, but sometimes, the options are too limited, and values must be specified manually.

Fonts:
As mentioned in [this issue](https://github.com/WordPress/twentytwentyfour/issues/577) from the Twenty Twenty-Four theme, adding more font size options would turn the size selector into a dropdown. However, I think this is where I must edit the sizes more often.

Spacings:
The spacing in the Twenty Twenty-Four theme works pretty well most of the time, but I think this could be a good opportunity to introduce a more flexible theme.

Alignments:
Would it be too confusing to add more options than the default, None, Wide width, and Full width? I usually find myself changing the alignment to Wide. And sometimes, I have to manually adjust the maximum width if the design doesn't fall into these three options.

**Comment by kraftner** [comment]
> Alignments: Would it be too confusing to add more options than the default, None, Wide width, and Full width? I usually find myself changing the alignment to Wide. And sometimes, I have to manually adjust the maximum width if the design doesn't fall into these three options.

This is more of an issue with Gutenberg itself which has https://github.com/WordPress/gutenberg/issues/27629 on the topic.
