### ISSUE TITLE
Add alternative templates for Personal Blog

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#132]
[Figma File](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=77-7921&t=bCFceo6KG1JJBgYQ-4)

The index/home, archive, and search templates use the same design for the list of posts, so one pattern can be created and re-used in all these templates.

Some templates have a section called "Other posts". This should be a pattern, created separately from the templates, basically to avoid multiple people working on the same part at the same time.

**Alternative One**

![Captura de ecrã 2024-08-27, às 16 15 26](https://github.com/user-attachments/assets/7f3b59b3-ac2c-4385-a9dc-a42f4f6a8123)

- [x] Text-only blog
- [x] Text-only post
- [x] Text-only archive
- [x] Text-only search

**Alternative Two**

![Captura de ecrã 2024-08-27, às 16 15 34](https://github.com/user-attachments/assets/1e7b7317-576f-4546-aa44-f51bb24b0f6d)

- [x] Vertical header, right aligned blog
- [x] Vertical header, right aligned post
- [x] Vertical header, right aligned archive
- [x] Vertical header, right aligned search
- [x] Vertical header, right aligned page

**Comment by carolinan** [comment]
Because of the time constraints in the project I suggest focusing on number two.

**Comment by beafialho** [comment]
I do not have assigning permissions, but I'm working on these.

**Comment by beafialho** [comment]
@carolinan should these templates be created instead as patterns as well like you describe in  #42?

**Comment by jasmussen** [comment]
> I do not have assigning permissions, but I'm working on these.

Can we add Bea to this repo?

**Comment by beafialho** [comment]
> Can we add Bea to this repo?

I have permissions now, thanks!
