### ISSUE TITLE
Question: How to address "Other Posts" section in the templates?

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#134]
**Description**
As per [the design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=559-1893&t=bCFceo6KG1JJBgYQ-4), we have an "Other Posts" section in some of the Single templates. It seems that it isn't possible to style the latest posts block this way and the problem with using the query loop is that it can not exclude the current post, so it won't technically be "other" posts.

@richtabor @MaggieCabrera @jasmussen do you have a suggestion for how to build this? Should we reconsider using this section?

![Captura de ecrã 2024-08-27, às 16 26 15](https://github.com/user-attachments/assets/aab5aa94-2bc1-4c6d-adff-66e61dfc7ada)

**Comment by carolinan** [comment]
If https://github.com/WordPress/gutenberg/issues/42810 can not be solved before Beta 1, the fastest solution is to have a regular query loop below another heading, for example "latest posts" or "more posts".

**Comment by jasmussen** [comment]
I'd tend to echo Carolina. The subheading could even be "All posts" or just "Posts".

**Comment by beafialho** [comment]
> the fastest solution is to have a regular query loop below another heading, for example "latest posts" or "more posts".

I agree with this, using "More Posts" for example.

**Comment by carolinan** [comment]
Unfortunately, I don't think that we can re-use the "Text-only blog, posts" query pattern for this since the "More posts" are not intended to have the pagination, correct?

We can re-use **parts** of it though.

**Comment by beafialho** [comment]
> Unfortunately, I don't think that we can re-use the "Text-only blog, posts" query pattern for this since the "More posts" are not intended to have the pagination, correct?

Correct, the "More posts" section at the bottom of the template should not have pagination but other than pagination, the design is exactly the same 👍

**Comment by beafialho** [comment]
This seems solved, right? I'll go ahead and close it.
