### ISSUE TITLE
Add more information to the readme about how to get the images from Figma

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#135]
**Is your feature request related to a problem? Please describe.**

Contributors are sharing that they are not sure how to get the images from Figma, and where to find the image credits.

**Describe the solution you'd like**

The readm.md file can be updated with more information.

**Comment by jasmussen** [comment]
I'm actually curious about this too. I don't think there's an easy way. It might be good to upload all these files to a shared folder, and point to those images from the README and Figma.

**Comment by carolinan** [comment]
I thought about creating a PR with all the images and credits, but I think many of the images on the [Figma image resource page](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=77-8118&t=SUQRtOhw1dC8WNfK-0) are unused.

**Comment by juanfra** [comment]
I like the idea of a shared folder. Is there any org account we can use for that?

**Comment by jasmussen** [comment]
Google Drive doesn't feel like a great solution, since we'd have to bounce email invitations around. Really we just need the images stored somewhere. Can we just zip the images, and if it's less than 10mb, upload it as a comment, right here?

**Comment by juanfra** [comment]
I believe we're good with Google Drive with the right sharing settings. There's too many images and I think it's going to be hard to have them all in less than 10mb.

I've created a folder in my account and will upload the converted images there.

Here's the link: https://tinyurl.com/tt5-images

Can you please confirm that it's working? Thanks in advance.

**Comment by jasmussen** [comment]
Confirmed working. It let me download a webp version of this:

![location](https://github.com/user-attachments/assets/296f31c4-ff9e-43e9-b1aa-12307f7086e6)

_The above I converted to JPEG just to get it to show up here._

**Comment by juanfra** [comment]
Excellent, thanks for confirming Joen! I'm getting all the images listed in the Figma file (Image files page) and putting them there in both jpg and webp.

**Comment by carolinan** [comment]
The problem is bigger than downloading the image file, because the license information and the link to the source needs to be in the readme.
In Figma, some of the images are listed without this information.

**Comment by jasmussen** [comment]
Can we include that information in the README here? #143

**Comment by juanfra** [comment]
All the photos I collected, except four, come from rawpixel. The filename is including the ID, and the way to get the license is by following the link `rawpixel.com/image/$id`.

By adding that in the readme, we should be good. 

The four that are not coming from rawpixel come from Flickr, and are the images for [this pattern](https://github.com/WordPress/twentytwentyfive/pull/126) where we could totally use placeholders.

**Comment by jasmussen** [comment]
If we can use the real images instead of placeholders, I think it would be a much more compelling pattern to use. Can we just include the Flickr links in the README?

**Comment by juanfra** [comment]
I think so. The different images from Flickr are part of the US National Archive and are under the "[The commons](https://www.flickr.com/commons/usage/)," which makes them free to use. The only thing that's unclear to me is if that is the same as [CC1.0](https://creativecommons.org/publicdomain/zero/1.0/). 

In both cases the link in the readme will suffice, what I don't know if it's CC1.0 or not.

As an example, this is the [Flickr page](https://www.flickr.com/photos/usnationalarchives/3906400735/in/album-72157622329706918/) of one of the ones used.

**Comment by jasmussen** [comment]
Thanks for the links. From my read, those are safe to use, though I'll prod someone to check!

Notably these two stand out:

> Access Restrictions: Unrestricted
> Use Restrictions: Unrestricted

> Participating institutions may have various reasons for determining that "no known copyright restrictions" exist, such as:
> 
> * The copyright is in the public domain because it has expired;
> * The copyright was injected into the public domain for other reasons, such as failure to adhere to required formalities or conditions;
> * The institution owns the copyright but is not interested in exercising control; or
> * The institution has legal rights sufficient to authorize others to use the work without restrictions.

**Comment by carolinan** [comment]
As far as I remember the theme directory does allow the use of "no known copyright restrictions", as long as there are no other restrictions added by the website that shares them, so these images should be OK.

**Comment by jasmussen** [comment]
I heard back from someone more in the know about these details. They mentioned:

> The example is from the U.S. National Archives says “No known copyright restrictions.” I would deem that to be a safe enough source to claim that we really took great pains to ensure we were not knowingly or even accidentally violating a copyright.
> The more prestigious or official the source that declares “No known copyright restrictions.” the safer we are.
> So go forth and conquer along with two steps to follow:
> a.  A U.S. Federal govt source is highest likelihood of the “No known copyright restriction” assertion being defensible. Second best source is from a state govt.  So aim for the most official sources you can muster if you have a choice.
> b.  Please screenshot and save the page for each photo that says “No known copyright restrictions.”   In the screenshot, record the URL and time and date of your visit.

The short: the ones from Flickr are good to use. A is taken care of, presumably, as we're not adding any additional photos to the pool.

B is an action item. This GH issue—any GH issue really—can be a place to store screenshots with dates, as comments. How does that sound?

**Comment by juanfra** [comment]
Thanks, Joen! That's good news.

I'm sharing screenshots of the Flickr pages for posterity.

🔗 URL: https://www.flickr.com/photos/usnationalarchives/8676029464/in/photostream/
![Screenshot 2024-08-30 at 11-00-27 Young Woman Soliciting Funds For A Chicago Organization In… Flickr](https://github.com/user-attachments/assets/5eb6bfce-b883-4233-a890-fff2e9eaede1)

🔗 URL: https://www.flickr.com/photos/usnationalarchives/3906419575/
![Screenshot 2024-08-30 at 10-59-48 Ms  Gail Falk Seltzer a Staff Lawyer for Field Services w… Flickr](https://github.com/user-attachments/assets/c449a975-2177-466b-b4b9-68f638ebac77)

🔗 URL: https://www.flickr.com/photos/usnationalarchives/3906400735/
![Screenshot 2024-08-30 at 10-59-01 One of a Series of Portraits of Miners Waiting to Go to Wo… Flickr](https://github.com/user-attachments/assets/82b14136-7b20-48dd-a22d-3215163ae6bf)

🔗 URL: https://www.flickr.com/photos/usnationalarchives/7157920320/
![Screenshot 2024-08-30 at 10-58-15 Young sugarcane field worker  His hat symbolizes effects o… Flickr](https://github.com/user-attachments/assets/af60236f-c3f0-4d72-9997-2b493c4ff576)

**Comment by jasmussen** [comment]
Fantastic! That works. Done.
