### ISSUE TITLE
Explore designs with negative margins

### ISSUE THREAD

**Issue by altivero** [WordPress/twentytwentyfive#14]
Some nice patterns could be created with overlapping images etc.

It may require adding z-index controls #[60411](https://github.com/WordPress/gutenberg/issues/60411) to blocks that allow negative margins.

See my comment there https://github.com/WordPress/gutenberg/issues/60411#issuecomment-2103669987 for issues that I came across.

**Comment by carolinan** [comment]
There are some designs in Figma that will likely need to use negative margins.
I will add the z-index issue to the list of Gutenberg issues, but I do not believe it will be solved in the 6.7 release.
