### ISSUE TITLE
Add section styles

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#142]
This is a **suggestion** for adding section styles, block style variations that can be applied to, in this case, the group block.

Each style would use an accessible combination of two or more colors from the palette, **and each style needs to continue to work when the user changes the color palette preset.** 

The purpose is to make it easy for users to change the style of a part of their content, pattern, or templates.

Section styles are .JSON files placed in the `styles` folder or a subfolder to `styles`.
Each file needs to include: schema, version, title, slug, one ore more block types, and the styles.

Section styles can not include settings. For example, it can set a font size, but not add new font size options to the typography control.

```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 3,
	"title": "Base",
	"slug": "section-1",
	"blockTypes": [ "core/group" ],
	"styles": {}
}
```

Each the section style would include:

- Background color and text color. Link color, if different from text color.
- Spacing
- Styles for elements:
  - Buttons
  - Headings

The CSS for these style variations are often repeated multiple times on the same page, which is why I recommend limiting the styles.

**Comment by richtabor** [comment]
Here's an example I've found pretty solid (we'd replace colors, make sure we do what's suitable for each): 

```
{
    "$schema": "https://schemas.wp.org/trunk/theme.json",
    "version": 3,
    "slug": "section-3",
    "title": "Style 3",
    "blockTypes": [
        "core/group",
        "core/columns",
        "core/column"
    ],
    "styles": {
        "color": {
            "background": "var(--wp--preset--color--theme-5)",
            "text": "var(--wp--preset--color--theme-1)"
        },
        "blocks": {
            "core/separator": {
                "color": {
                    "text": "color-mix(in srgb, currentColor 25%, transparent)"
                }
            }
        },
        "elements": {
            "button": {
                "color": {
                    "background": "var(--wp--preset--color--theme-1)",
                    "text": "var(--wp--preset--color--theme-5)"
                },
                ":hover": {
                    "color": {
                        "background": "color-mix(in srgb, var(--wp--preset--color--theme-1) 85%, #000)",
                        "text": "var(--wp--preset--color--theme-5)"
                    }
                }
            }
        }
    }
}
```

**Comment by richtabor** [comment]
Worth nothing that each color variation should define its own as well, like this: https://github.com/Automattic/themes/blob/trunk/assembler/styles/colors/01-blueberry.json#L155-L202

**Comment by jasmussen** [comment]
Thanks for the code samples Rich! I tried my hand at a starting point for this effort in #151.

**Comment by jasmussen** [comment]
What remains on this one?

**Comment by carolinan** [comment]
It is starting to bug me a little bit that the pink one is style-1, when pink is not the first color in the palette 😆  But maybe that is just me.

**Comment by jasmussen** [comment]
I'm happy to spin up a PR to change the order. Any preferred order?

**Comment by carolinan** [comment]
I would prefer if the order matched the default palette.
So style-1 would be contrast

![image](https://github.com/user-attachments/assets/09d849ac-d0b3-414f-b8c2-319310b79b51)

But this would cause conflicts with new PR's, perhaps it needs to be done later.

**Comment by jasmussen** [comment]
Good heuristic. We'll keep this issue open as something to come back to for that purpose.

**Comment by carolinan** [comment]
I think we have gone to far now to change the order of the styles, but I think they still need new names.

**Comment by richtabor** [comment]
We have not gone too far. It's simple to rename the files, change the slugs, and conduct a find and replace. A few minutes of work and the styles have some sort of hierarchy to them. 

For what it's worth, I don't think they should be ordered by the colors in the color palette, simply lightest to darkest. So there's some visual hierarchy and less guessing when choosing a style.
