### ISSUE TITLE
Spacing/Typography presets: reduce total amount to use the ergonomic controls

### ISSUE THREAD

**Issue by jasmussen** [WordPress/twentytwentyfive#152]
**Is your feature request related to a problem? Please describe.**

At the moment, there are 8 spacing presets, and 6 typography presets. These amounts cause the segmented dimensions and typography controls to be replaced by dropdowns:

![Screenshot 2024-08-29 at 12 19 32](https://github.com/user-attachments/assets/4585855b-d676-48fe-982d-bc67352ba9b5)

![Screenshot 2024-08-29 at 12 22 05](https://github.com/user-attachments/assets/ac3bdead-ba56-41d8-90e5-eef3a8e4cd64)

**Describe the solution you'd like**

The dropdown experience is not as good a user experience, requiring two clicks instead of one. If we reduce the amount of spacing presets to 7 (for example deleting the X-Tiny), we get the range control:

![Screenshot 2024-08-29 at 12 24 43](https://github.com/user-attachments/assets/5791f3e2-b20a-4e49-a6f5-1adfe03195e7)

Similarly, if we remove a single font size preset, we get the single-click typography size control:

![Screenshot 2024-08-29 at 12 28 52](https://github.com/user-attachments/assets/6437d144-a31c-405d-9a53-54c88ddc4a35)

I'd suggest consolidating and removing either the Extra Large or Extra Extra Large size.

**Comment by carolinan** [comment]
💯

**Comment by jasmussen** [comment]
Nice. I'll spin up a PR, just to feel it out.
