### ISSUE TITLE
Theme info page

### ISSUE THREAD

**Issue by codersantosh** [WordPress/twentytwentyfive#158]
**Is your feature request related to a problem? Please describe.**
I haven't seen a dedicated theme info page for default themes. This absence can make finding detailed information about theme features and contributors difficult.

**Describe the solution you'd like**
I propose adding a theme info page for the Twenty Twenty-Five theme. This page should include details such as theme features and contributors (content can be discussed). This addition would enhance the user experience by making accessing detailed information about the Twenty Twenty-Five theme easier.

**Comment by carolinan** [comment]
Hi @codersantosh the documentation is published when the theme is released.
I am closing this issue in favor of the tracking issue that is already open.
https://github.com/WordPress/twentytwentyfive/issues/20
