### ISSUE TITLE
Post format archive templates

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#17]
It has probably not gone unnoticed that there is a request to[ add support for post formats](https://make.wordpress.org/core/2024/07/08/what-would-you-like-to-see-in-the-next-default-wordpress-theme/#comment-46916) to block themes in general and Twenty Twenty-Five.

Currently, there are only two things that the **theme** can do to support post formats:
- Register them using the theme support (Post formats are not enabled by default) `add_theme_support( 'post-formats')`
- Include HTML templates for the post format archives. 

From the theme developer handbook:
>In the case of [post formats](https://developer.wordpress.org/themes/functionality/post-formats/), the taxonomy is ‘post_format’ and the terms are ‘post-format-{format}. i.e. taxonomy-post_format-post-format-link.php for the link post format.

https://developer.wordpress.org/themes/basics/template-hierarchy/#custom-taxonomies

**Comment by justintadlock** [comment]
I did quite a bit of exploration for post formats here: https://github.com/x3p0-dev/x3p0-ideas/issues/17

It's probably a bit more involved than we'd want to include a default theme, but just sharing in case any of it's useful.

**Comment by beafialho** [comment]
What else is needed from design here? There are "post format" templates mocked up [here](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3259-4046&t=ZfLLXJppTnoBfVEI-4).

**Comment by carolinan** [comment]
Then I will remove the needs design label.

**Comment by carolinan** [comment]
@beafialho The theme can include archive templates for post formats. But not templates for single post formats. It is not part of the template hierarchy.

**Comment by carolinan** [comment]
Hm, actually that does not work either. When the query loop is set to inherit the query from the template, the editor shows all posts, but the front shows the correct post with the expected format.

Branch for testing: https://github.com/WordPress/twentytwentyfive/tree/add/post-formats
Create a new post and assign it the link format. Save.
Go to the front of the site and add type/link : yoursite.domain/type/link.
Confirm that the archive shows the post you created.
In the admin toolbar, select "Edit site" to open the template for the link format.
The query block, which is supposed to inherit the parameters from the template, shows all posts.

**Comment by jasmussen** [comment]
I can confirm your steps.

Post:
![Screenshot 2024-09-24 at 13 03 43](https://github.com/user-attachments/assets/9d31d5cb-a6e4-4256-9fa3-ddfbf3dab044)

Frontend:

![Screenshot 2024-09-24 at 13 03 25](https://github.com/user-attachments/assets/072f1727-d9a0-482c-9e23-350213c372f0)

Editor:


![Screenshot 2024-09-24 at 13 03 32](https://github.com/user-attachments/assets/604d62b5-4608-44ca-be42-6a365bcb16bb)

Is that https://github.com/WordPress/gutenberg/issues/53049 that needs to fully be addressed?

Thinking. The beta is around the corner. TT5 is meant to be a blogging first theme. The post formats work on the frontend, and there's even a "Format" type in the status inspector, already shipping with WordPress. The remaining piece is indeed the admin templates. Given that this format selector already ships, is the missing template type and handling a blocker for this feature to be included in Twenty Twenty-Five? I'd tend to think your branch could be worth merging and seeing if we can fix the bug of the missing template in the block editor post Beta 1. I may be able to wrangle help. Perhaps @draganescu?

**Comment by carolinan** [comment]
There is one bug fix plus the PHP "backport" to core that still needs to be finished for the query loop filter.

----

These are the two tickets I opened but did not find time to work on:

Post Formats: Query loop shows the wrong posts when inheriting the query from the post format archive template
https://github.com/WordPress/gutenberg/issues/65320

Post formats: Archive templates have no description and use the slug instead of a readable name 
https://github.com/WordPress/gutenberg/issues/65319

Besides that, it is not possible to create post format templates (of any kind) in the Site Editor.


----

The theme could create custom post templates, one for each supported format, but supporting that long term is trickier if the feature is introduced.

**Comment by carolinan** [comment]
If the query loop contains multiple formats, say, standard and video, there is no way to use different blocks for the video.
Well, not without "hacks".
