### ISSUE TITLE
Add Inter Typography

### ISSUE THREAD

**Issue by EldarAgalarov** [WordPress/twentytwentyfive#171]
Hi. Please add [Inter font](https://github.com/rsms/inter) into the theme. Inter is a typeface carefully crafted & designed for computer screens. Inter is popular and better than Roboto on small screens.

**Comment by beafialho** [comment]
Hi! Thank you for your suggestion. All typefaces selected for the theme have been carefully tested and have wide language support. This one did not contemplate the addition of Inter, but you may add it to your site once you install the theme through the font library.
