### ISSUE TITLE
Reconsider the use of the trademark symbol

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#180]
**Is your feature request related to a problem? Please describe.**

The use of the registered trademark symbol is confusing and factually incorrect since the theme or its creators can not claim that anything in it, including a fake branding, is a registered trademark.

**NOT A LAWYER**
And if "Stories" is an actual registered trademark, for anything related to software, it must not be used.

In my personal opinion, It is also against the spirit of GPL, since it is likely that it can be interpreted that "you can not use this because it is a registered trademark".

**Comment by beafialho** [comment]
The intention behind the usage of it was to include an example of a visual indication of what a business or a brand could look like using the theme. If there are legal concerns, we may always opt out of using the **®** in the patterns.

**Comment by jasmussen** [comment]
I love the rounded trademark symbol, so I asked a lawyer. Though good instinct, this is important to figure out.

@beafialho in case we can't use it, I found some alternatives that don't carry any legal meaning at all:

![Screenshot 2024-09-03 at 08 46 26](https://github.com/user-attachments/assets/68d32624-8a5f-4dd5-9802-ebbb3a53c891)

How would you feel about "StoriesⓉ"?

**Comment by jasmussen** [comment]
Ah, unfortunately those circles don't work as well:

![Screenshot 2024-09-03 at 08 49 38](https://github.com/user-attachments/assets/94d3c002-c212-49db-b439-a5e6aa76b589)

Some additional options. "Stories⁺"

![Screenshot 2024-09-03 at 08 51 10](https://github.com/user-attachments/assets/51932a03-ebed-4c9c-be6b-5e2c968d0c8f)

"Stories⁽⁺⁾":

![Screenshot 2024-09-03 at 08 53 20](https://github.com/user-attachments/assets/0973d7ba-fd71-426c-a31d-6a6489755294)

"Stories™":

![Screenshot 2024-09-03 at 08 57 06](https://github.com/user-attachments/assets/89938687-9cef-4d10-a8f5-8a59ccf8f578)

The trademark symbol should be fine to use as it indicates _unregistered_.

**Comment by carolinan** [comment]
If only there was a glyph for the WP logo...

**Comment by carolinan** [comment]
We can't just add an svg with the logo can we?

**Comment by beafialho** [comment]
Thank you both for your input! I think it'd be fine to just use "Stories".

**Comment by beafialho** [comment]
It loses some of its character though.

**Comment by carolinan** [comment]
It can still be used on the demo site...

**Comment by beafialho** [comment]
> It can still be used on the demo site...

True. It will look inconsistent with the same term in the patterns, but to be honest I don't think it's a big issue. We can move on without any symbol 👍

**Comment by jasmussen** [comment]
Just reporting that I did hear back from a lawyer, and they confirm we should remove the (R). We _can_ use the TM mark as decorative, but that appears a little fuzzy too. So best path forward, unfortunately, is to either find a neutral glyph (asterisk, other), or remove it.

**Comment by carolinan** [comment]
Thank you for confirming.

**Comment by beafialho** [comment]
Thank you for confirming. It's one of those inoffensive visual elements that aren't actually inoffensive 🙂 Let's just remove the `®` symbol from everywhere.
