### ISSUE TITLE
Block Patterns - Landing page - Heading, paragraph, links and full-height image on the right

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#188]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Landing page - Heading, paragraph, links and full-height image on the right` pattern.
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1787&t=iMHEZ4xZGwCzs1U9-4)

**Original pattern colors** ❌
![Captura de ecrã 2024-09-03, às 11 59 22](https://github.com/user-attachments/assets/617a5e68-d33b-48ec-aa27-29016addcf87)

**Pattern using colors from the existing palette** ✅
![Captura de ecrã 2024-09-03, às 17 14 49](https://github.com/user-attachments/assets/c5b95284-4715-4c13-bddb-1e54a72fe1b4)

**Comment by juanfra** [comment]
Completed in https://github.com/WordPress/twentytwentyfive/pull/202
