### ISSUE TITLE
Add issue templates to repo

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentytwentyfive#19]
I would like to bring in issue templates to this repo that are similar to the ones other community repos have. This will help as issues come in and scale up.

The ones I would like to bring in are:

- Bug report: including some steps so that people can fill out specific sections. This will help once we have testing going on. It will encourage things like steps to reproduce by using a template format.
- Feature request

We don't probably need anything more than that to start but we absolutely could add other templates.

If everyone agrees I will bring these in but I am creating this issue to first propose it and secondly get opinions of the ones I am suggesting and others people might also want.

**Comment by carolinan** [comment]
Yeah lets go ahead and add them.

**Comment by karmatosed** [comment]
Ok, I will work on those, thank you @carolinan.

**Comment by juanfra** [comment]
Thank you both! I [created a PR](https://github.com/WordPress/twentytwentyfive/pull/43) for this one because we'll probably start to see new issues now that the theme has been announced and the designs are public.
