### ISSUE TITLE
Block Patterns - Services - Team photos

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#191]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Services - Team photos` pattern.
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1806&t=iMHEZ4xZGwCzs1U9-4)

![Captura de ecrã 2024-09-03, às 12 10 31](https://github.com/user-attachments/assets/e3528142-9dbb-4183-9636-bde4810bd920)

**Comment by juanfra** [comment]
Hi Bea, 

We have already completed this one here: https://github.com/WordPress/twentytwentyfive/issues/79

**Comment by beafialho** [comment]
Oh, awesome. I'll close this one then, thanks!
