### ISSUE TITLE
Post date:  Fine tune the font size

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#192]
**Description**

When the font size slugs were changed in theme.json, the post-date was not changed from `small` to `medium`, so the default post-date size was a size too small.

However, looking at how the post date is used in the existing patterns, they all add the small font size directly in the markup, except for the twentytwentyfive/more-posts pattern.

So would it not be more logical to:
- Keep the `small` font size in theme..json
- Add the `medium` size to the more-posts pattern.
- Remove the size from the markup in the patterns that uses `small`.

When the user adds a new post date block, it would use size small and this would be two sizes smaller than the default paragraph text, but it would match the post date else where in the design.

**Comment by beafialho** [comment]
I don't think I'm understanding exactly what the issue is. Currently, when I add post date, it's looking good.

**Comment by carolinan** [comment]
There are more places in the code that changes the font size of the post date, than places that uses the default size.
So I think it would be logical to update the default size to use the size that is used the most.

**Comment by carolinan** [comment]
> Remove the size from the markup in the patterns that uses small.

The font size does not need to be in the markup, if it uses the default size. That is only duplicate code to maintain.

**Comment by beafialho** [comment]
> That is only duplicate code to maintain.

I see. If everything will look the same on the front end as it does now, I have no objections 👍

**Comment by carolinan** [comment]
I closed this because it won't be relevant until the font sizes are revised, again.
