### ISSUE TITLE
Add the "combined" global style varitations

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#193]
**Is your feature request related to a problem? Please describe.**

The theme now has typography presets, color palette presets, and section styles.
This issue is for creating the style variations that combine different presets: In other words, the json files for the style variations that will be available next to the default style here at the top of the Styles panel:

![image](https://github.com/user-attachments/assets/97238e1f-5000-4137-9126-09d3f6c6abd1)

[Here are the current Figma designs](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3155-1729)

- [x] Evening - Manrope + Manrope (Dark mode)  _(kishanjasani)_
- [x] Noon - Beirut & Literata 60P _(shail-mehta)_
- [x] Dusk - Volkorn and Fira code     _(carolinan)_
- [x] Afternoon - Platypi + Ysabeau Office _(kishanjasani)_
- [x] Twilight - Roboto Slab + Manrope _(beafialho)_
- [x] Morning - Literata 60pt + Ysabeau Office _(juanfra)_
- [x] Sunrise - Platypi + Literata 60pt _(juanfra)_
- [x] Midnight - Literata 60pt + Fira Sans _(beafialho)_

**Comment by carolinan** [comment]
I'd like to work on Dusk.

**Comment by beafialho** [comment]
I'd like to work on Twilight and Midnight.

**Comment by juanfra** [comment]
I'm not a morning person, but I'll make an exception; I take Morning and Sunrise.

**Comment by kishanjasani** [comment]
I'd like to work on `Afternoon - Platypi + Ysabeau Office` and `Evening - Manrope + Manrope (Dark mode)`.

**Comment by shail-mehta** [comment]
I would like to work on `Noon - Beirut & Literata 60P`  style variation.

**Comment by carolinan** [comment]
Hi @shail-mehta @kishanjasani do you still want to work on these? Or can anyone work on these styles?

**Comment by beafialho** [comment]
Thanks for double checking @carolinan, I was going to ask this. I'm happy to handle these as well 🙋🏻‍♀️

**Comment by juanfra** [comment]
Given the priority of this issue and the recent activity, I'd prefer if Bea could start with this. Also, considering that she'll be out starting Friday.

**Comment by beafialho** [comment]
I'll get started on these given that it is time-sensitive.

**Comment by juanfra** [comment]
Thanks, Bea. Thank you all!

**Comment by carolinan** [comment]
These are all added, we can use the "clean up" issues to track these now.
