### ISSUE TITLE
"Pill" text style

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#195]
**Description**

![Captura de ecrã 2024-09-02, às 16 01 19](https://github.com/user-attachments/assets/94fb2ffc-9dbc-42f0-9ca2-a1d3d06259b1).

We use a "pill" style for some text elements in several patterns. 

- https://github.com/WordPress/twentytwentyfive/issues/76
- https://github.com/WordPress/twentytwentyfive/issues/77
- https://github.com/WordPress/twentytwentyfive/issues/57
- https://github.com/WordPress/twentytwentyfive/issues/63
- https://github.com/WordPress/twentytwentyfive/issues/64
- https://github.com/WordPress/twentytwentyfive/issues/175

And in the following template as well:

- https://github.com/WordPress/twentytwentyfive/issues/41

This goal of this issue is to track the implementation of the "pill" text style and its usage in different locations.

There's a separate discussion going on about what HTML element would be the best one to use for these "pills" depending on the context, [here](https://github.com/WordPress/twentytwentyfive/issues/150). For the time being, headings and paragraphs looks the most appropriate ones to cover all cases.

There's also a contribution that includes a version of how this text style would look like, it can be found [here](https://github.com/WordPress/twentytwentyfive/pull/118/files#diff-f3d8635069ab04f1108d0fc2002438a75932d712fb5d029d936c5d6423967e93). It's likely that for organization purposes we'll cherry pick that into a different PR so that we can expedite things for the other patterns.

**Comment by carolinan** [comment]
The style is also used for post terms -tags.
The style is different in different style variations. For example the style variation with the grey background has a 4px border radius.

**Comment by carolinan** [comment]
When the block style from #118 is applied to a paragraph or heading, the border is used on the entire length of the block, unless placed in a flex or grid item:

![image](https://github.com/user-attachments/assets/63eb8119-1d6c-4713-bdda-f691378eaca3)

Where a paragraph was intended to be used, I think it may be easier for users to make it look "correct" if a button block is used.
Perhaps this button could be a variation simply called "small button" ?

**Comment by jasmussen** [comment]
The pill-shaped paragraph feels like such a clear design element, and an example of how you can use the block editor to visually express various styles. It seems valid enough to include in patterns, where this is used most often. Is there any reason we can't just include the row wrapper for where this element is needed? The fact that you can unwrap the pill and "break" its appearance is the case for most patterns, including the overlapping gallery patterns and others.

**Comment by carolinan** [comment]
Why make it breakable if it is not necessary?

**Comment by jasmussen** [comment]
Any pattern is breakable, and in this case it's a key part of the visual design of the theme. It'll lose a lot of character if we remove this pill shape. I'm almost certainly missing nuance here, so if I'm missing something, please clarify. In this case it seems like we should try our best to achieve the design Bea set out here.

**Comment by carolinan** [comment]
I thought the comments were referring to using the **button** instead of the **paragraph**, I asked:

> Where a paragraph was intended to be used, I think it may be easier for users to make it look "correct" if a button block is used.
Perhaps this button could be a variation simply called "small button" ?

using a button where the pill *can* be used will not make it loose character?

**Comment by jasmussen** [comment]
From what I can see of the patterns, not all the pill-shaped items will be linked. So a button isn't the best in that case, is it?

**Comment by carolinan** [comment]
Buttons are not linked by default. Neither are paragraphs.

The tags are: In the post terms block, the link can't even be removed :/  So that right now requires a separate style

**Comment by carolinan** [comment]
I know there are people who will not agree with me but there is still the option to hide decorative items from screen readers.

**Comment by jasmussen** [comment]
The semantics of using an unlinked button are unclear to me, but if that's fine, no objection from me. I don't think of these as decorative. I genuinely think of these as carefully designed sections of a page, where the border, radius, font size, all of those pieces, play a role in creating the whole.

**Comment by carolinan** [comment]
Anyone want to have a go at adding custom CSS to adjust the area the border covers?
