### ISSUE TITLE
Design & Frontend

### ISSUE THREAD

**Issue by amitbajracharya** [WordPress/twentytwentyfive#2]
Hi Everyone,
I am happy to contribute as a designer to this project. If needed can do the front end as well.

**Comment by kafleg** [comment]
> Hi Everyone, I am happy to contribute as a designer to this project. If needed can do the front end as well.

That is awesome @amitbajracharya 

Let's keep the discussion going; we can all work together to make this theme.

**Comment by amitbajracharya** [comment]
We need to decide if we are following any theme this time so that its easier to design.

**Comment by carolinan** [comment]
> We need to decide if we are following any theme this time so that its easier to design.

Yes, the plan is to publish a blog post on the make blog asking people for their ideas, and take inspiration from that.

**Comment by carolinan** [comment]
Hi @amitbajracharya 
The design has been presented and is available using this [Figma link](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five).

Your contributions are welcome. I will close this issue now since it is not related to an actionable task.

**Comment by amitbajracharya** [comment]
Thanks. I will contribute whatever I can. :)
