### ISSUE TITLE
The Pull-quote block have extra padding on top & bottom

### ISSUE THREAD

**Issue by viralsampat90** [WordPress/twentytwentyfive#213]
**Description**
Hello,

I have reviewed the "Pull-quote" block and found that there is extra white space displaying at top & bottom of the block on both editor side & front-end side. I think that it should be little bit, Not that much.

**Step-by-step reproduction instructions**

- Go to admin and select the "Pull-quote" block first.
- Add its paragraph text & citation text.
- Set it border to see it more clear.
- Update the page and check its admin text and front-end text.

**Expected behavior**
I think that the white space it should be little bit, Not that much.

**Here, I have provided screenshot for expected behaviour**
![after-resolve-twenty-twenty-five-pull-quote-editor-side](https://github.com/user-attachments/assets/52dcf491-ea0d-4919-9a0a-351819c20183)
![after-resolved-twenty-twenty-five-pull-quote-front-end](https://github.com/user-attachments/assets/8c6f068d-a124-46d4-a126-c29e6db7e98c)

**Screenshots**
![twenty-twenty-five-pull-quote-editor-side](https://github.com/user-attachments/assets/80117cc6-e0b1-4963-ba57-fa0ecb49bb1d)
![twenty-twenty-five-pull-quote-front-end](https://github.com/user-attachments/assets/45058e6e-cc51-4433-95ab-46c5c3977f42)

**Environment info**

- Device: Macbook M1
- OS: 14.6.1 (23G93)
- Browser: Google Chrome
- Version 128.0.6613.114 (Official Build) (arm64)
- WordPress version: 6.6.1 running, Gutenberg 19.1.0 , Theme active: Twenty Twenty-Five,

**Additional context**
I have tested this issue with active and inactive Gutenberg plugin and I am getting this issue.

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by juanfra** [comment]
Thanks for your contribution!
