### ISSUE TITLE
Performance assessment and support for Twenty Twenty-Five

### ISSUE THREAD

**Issue by felixarntz** [WordPress/twentytwentyfive#216]
**Is your feature request related to a problem? Please describe.**
This is a tracking issue for the WordPress Performance Team to take a closer look at the performance implications of using TT5. Usually, this means benchmarking a WordPress test site using the theme, comparing with previous default themes, and identifying bottlenecks if there are any.

If performance problems are discovered, it's worth noting that they may not necessarily happen due to a problem in the theme. Rather than that, several times in the past, the theme's usage of WordPress core features exposed performance flaws in the implementation of these features, which then led to improvements of the core features' performance.

**Describe the solution you'd like**
N/A

@carolinan @juanfra Is there a particular milestone or timeframe where from your perspective the theme would be in a good state for assessing performance?

cc @joemcgill @mukeshpanchal27 @swissspidy @westonruter @adamsilverstein

**Comment by juanfra** [comment]
Hi @felixarntz - We were talking with @carolinan and we believe that this could take place after "Beta 1".

**Comment by felixarntz** [comment]
Thanks @juanfra @carolinan!

**Comment by carolinan** [comment]
Note that some of the images in the theme may still need to be replaced completely or with AVIF.

**Comment by felixarntz** [comment]
@mukeshpanchal27 Is this something you could own?

Maybe a good approach would be:
* Run benchmarks for TT5 on latest WP (e.g. 6.7 Beta) and compare outcomes with TT4 and TT3 on the same WP version.
* Run Lighthouse analyses on a few TT5 templates in the browser to identify potential areas of improvements (based on the recommendations it provides).
* Manual review of some of the performance relevant theme PHP/JS code if any (probably not much given this is a block theme).

**Comment by mukeshpanchal27** [comment]
> [@mukeshpanchal27](https://github.com/mukeshpanchal27) Is this something you could own?

Yes.

**Comment by mukeshpanchal27** [comment]
I ran some benchmarks using [dummy data](https://raw.githubusercontent.com/WPTT/theme-unit-test/master/themeunittestdata.wordpress.xml) for TT3, TT4, and TT5.

In the [TT5 Performance Benchmarks for WP 6.7 Beta 2](https://docs.google.com/spreadsheets/d/1qSnFRsNKjYkDgY1dLPUN2gpSu7o3cenfw4Wfm5Jxsxc/edit?usp=sharing), I've added data based on the results. The numbers indicate a performance regression in TT5.

**Comment by mukeshpanchal27** [comment]
### Server-timing for TT3 <> TT5 in fresh WP beta 2 installation

| Mertic | TT3 | TT5 | Diff % | Diff abs. |
| --- | --- | --- | --- | --- |
| Response Time | 46.96 | 58.07 | 23.66% | 11.11 |
| wp-before-template | 29.29 | 35.96 | 22.77% | 6.67 |
| wp-template | 16.18 | 20.34 | 25.71% | 4.16 |
| wp-total | 45.5 | 56.27 | 23.67% | 10.77 |


The numbers indicate a performance regression in TT5. Someone needs to run the benchmark to verify the performance numbers.

**Comment by mukeshpanchal27** [comment]
### Xhprof report for TT3 <> TT5 in fresh WP beta 2 installation

![Image](https://github.com/user-attachments/assets/ec110d92-dde8-476a-8506-6c0ac40f8361)

**Comment by mukeshpanchal27** [comment]
@juanfra @carolinan 

TT5 uses a large number of patterns. The current trunk (Beta 2) includes 97 patterns, while the TT5 repository shows 99 patterns. Do we really need all of these patterns?

**Comment by carolinan** [comment]
I would have liked to see patterns moved to the pattern directory, but there are bugs when placing those patterns directly in a template file:
https://github.com/WordPress/gutenberg/issues/64104
https://github.com/WordPress/twentytwentyfive/issues/23

**Comment by carolinan** [comment]
Why does the number of patterns matter for the overall performance? They should only be queried when a user is opening the inserter / on the pattern data views, no?

**Comment by mukeshpanchal27** [comment]
> Why does the number of patterns matter for the overall performance? They should only be queried when a user is opening the inserter / on the pattern data views, no?

Block patterns are registered in `init` hook. See https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-patterns.php#L343-L407

**Comment by felixarntz** [comment]
Thank you @mukeshpanchal27 for the assessment and @carolinan for the feedback.

It's worth noting that a year ago we saw similar problems in TT4, because it had way more patterns than TT3. The same is the case for TT5, so makes sense that we see a regression from that.

That said, if anything this is a Core problem in how the patterns are registered on `init`. Maybe we can iterate on that in Core, to e.g. lazy-load only what's needed, similar to how it's [already implemented for block variations](https://make.wordpress.org/core/2024/02/29/performance-improvements-for-registering-block-variations-with-callbacks/). In any case, it wouldn't be reasonable to argue that the theme should have fewer patterns because of this performance concern.

Is there anything else we can identify in TT5 that would be a partial cause for the server-side performance regression? If not, I think we can ignore this problem in the context of the theme, but we should probably open a Trac ticket to think about solutions.

@mukeshpanchal27 Would you be able to also do a Web Vitals comparison between e.g. TT5 and TT4, so that we can cover client-side performance as well?

**Comment by mukeshpanchal27** [comment]
> Is there anything else we can identify in TT5 that would be a partial cause for the server-side performance regression? 

No

### Web Vitals comparison for TT3 <> TT5

For home page benchmark the setup have one post with featured image.

| Mertic | TT3 | TT5 | Diff % | Diff abs. |
| --- | --- | --- | --- | --- |
| FCP | 101.95 | 95.45 | -6.38% | -6.50 |
| LCP | 101.95 | 95.45 | -6.38% | -6.50 |
| TTFB | 60.85 | 74.25 | 22.02% | 13.40 |
| LCP-TTFB | 40.9 | 20.1 | -50.86% | -20.80 |

The `TTFB` number shows regression other number look solid.

**Comment by felixarntz** [comment]
Thanks @mukeshpanchal27!

The fact that TT5 has faster LCP than TT3 is very promising, even more so given that it has slower TTFB. This suggests that TT5 is more optimized for client-side performance, which is quite valuable, given that client-side performance problems cannot be solved through caching, while server-side performance problems can.

In other words, for sites that have a full page cache, sites using TT5 should be quite a bit faster than sites using TT3, which is great.

The remaining server-side issue is something we should think about addressing in Core. I don't think there's a ticket for lazy-loading block patterns yet? Do you recall any previous efforts like that @mukeshpanchal27 @joemcgill? I only remember that we worked on lazy-loading block variations so far.

**Comment by mukeshpanchal27** [comment]
> Do you recall any previous efforts like that [@mukeshpanchal27](https://github.com/mukeshpanchal27) [@joemcgill](https://github.com/joemcgill)?

In 6.4, we implemented caching for [theme block pattern files, which were cached in a transient as a performance enhancement](https://core.trac.wordpress.org/changeset/56978). However, the lazy-loading of block patterns hasn't been addressed. It would be a good idea to create a separate ticket to explore this further.

Also found https://core.trac.wordpress.org/ticket/59532 that load pattern content only when used.

**Comment by mukeshpanchal27** [comment]
Found GB issue related to lazy-load pattern https://github.com/WordPress/gutenberg/issues/23301

**Comment by juanfra** [comment]
Thank you so much for this @felixarntz @mukeshpanchal27 @carolinan 

We're triaging the open issues for TT5 and we were wondering if we're good to go and close this one or if you'd like to keep it open for some reason?

Thanks again.

**Comment by felixarntz** [comment]
@juanfra 

> We're triaging the open issues for TT5 and we were wondering if we're good to go and close this one or if you'd like to keep it open for some reason?

Thanks for checking in, I think it's okay to close this one. Looks like client-side performance is quite solid, and the server-side performance issues aren't new and not caused by TT5 itself.

**Comment by juanfra** [comment]
Thank you Felix!
