### ISSUE TITLE
Register  the "pages" pattern category

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#219]
During the meeting on September 4, the attendees agreed that having a category for pages would be helpful.
This category can be used for homepage and landing page patterns.

Resource and code example:
[https://developer.wordpress.org/reference/functions/register_block_pattern_category/
https://developer.wordpress.org/themes/patterns/registering-patterns/#pattern-categories

**Comment by juanfra** [comment]
Thanks! It looks like this one is already done, should we close it as completed?

**Comment by carolinan** [comment]
yes!
