### ISSUE TITLE
Add Pattern: Grid with videos

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#221]
🛠️ The goal of this issue is to track the implementation of the Grid with videos pattern.
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.

[Figma](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-2028&m=dev)

For the "Podcast" text, please use a paragraph block with the "pill" style applied.
You can use empty placeholders for the video blocks.

![image](https://github.com/user-attachments/assets/c599ca08-3a15-4757-80a0-aae82af74862)

**Comment by eirichmond** [comment]
I'm happy to tackle this one :)

**Comment by eirichmond** [comment]
@carolinan when you say empty placeholder, is there a prefered way of doing that?

**Comment by beafialho** [comment]
@eirichmond I believe that means to just add the video block without adding any demo videos to the block.

**Comment by carolinan** [comment]
Yeah that is what I meant 😊

**Comment by eirichmond** [comment]
Ok, I've added a PR for this #228 :)
