### ISSUE TITLE
Replace Literata font with Literata 72pt

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#229]
The font intended to be used in the theme is not "Literata", but instead "Literata 60pt". This version has more elegant serifs and adds a different character to the theme.

The font can be downloaded [here](https://drive.google.com/file/d/10gXtroY3pgFzJ43CUaDM5aNPwp96LOOc/view).

I believe this is a blocker for the creation of the style variations that use this font in #193.

**Comment by carolinan** [comment]
The font needs to have a public source other than a Google drive, because:
1) It must be a reliable source with license and copyright information
2) The theme will need to update the font family to a newer version about once per year.

**Comment by beafialho** [comment]
Well in that case, it'll have to look less good. I'll close this issue.

**Comment by carolinan** [comment]
But where are the files from? I assume the original source is trusted.

**Comment by beafialho** [comment]
It was a file I downloaded from Google Fonts a while ago (perhaps 1 or 2 years), but they must have updated the font files. I don't see these static files anywhere "official" now.

**Comment by beafialho** [comment]
Actually, I was browsing the Literata GitHub repo, and they do have[ the 72pt version](https://github.com/googlefonts/literata/tree/main/fonts/webfonts), which we could use.

**Comment by carolinan** [comment]
Yeah if that works design wise then the source is valid.

**Comment by beafialho** [comment]
That would be great. I believe we'll need all the weights. Thanks for reopening ✨

**Comment by shail-mehta** [comment]
Replaced `Literata` and `Literata 60pt` fonts with `Literata 72pt`

PR: https://github.com/WordPress/twentytwentyfive/pull/256
