### ISSUE TITLE
Move the style variation specific font families from the main theme.json to the variation json file.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/twentytwentyfive#233]
## What?
Move the style variation specific font families from the main theme.json to the variation JSON file.

## Why?
Currently, the font families must be defined in the main theme.json file to load as expected in the editor when the style variation is switched. If this issue https://github.com/WordPress/gutenberg/issues/59965 is fixed (in progress https://github.com/WordPress/gutenberg/pull/65019), we could avoid this 'hack' that's producing the printing of not needed CSS in the frontend. So, this change would be a tiny performance improvement, and it could lead to simpler-to-define typography variations.

**Comment by jasmussen** [comment]
@jffng is https://github.com/WordPress/twentytwentyfive/pull/237 related to this? Just doing some dusting off of issues given the beta is nearing.

**Comment by jffng** [comment]
@jasmussen yes that's right — #237 depends on the above Gutenberg issue + PR being resolved.

**Comment by carolinan** [comment]
@matiasbenedetto  @jffng Are there any updates to this?

**Comment by matiasbenedetto** [comment]
> @matiasbenedetto @jffng Are there any updates to this?

👋 Yes, I updated both https://github.com/WordPress/gutenberg/pull/65019 and https://github.com/WordPress/twentytwentyfive/pull/237

They are ready for review.
