### ISSUE TITLE
Missing `hidden-` prefix on patterns?

### ISSUE THREAD

**Issue by codersantosh** [WordPress/twentytwentyfive#234]
**Description**

> Let's prefix hidden patterns using hidden- when we name the pattern file.

Based on the description, many pattern files are missing the `hidden-` prefix when there is ` Inserter: no` in the patterns.

**Comment by gohelkunjan** [comment]
Hi @carolinan 

Many pattern files are missing the hidden- prefix, which should be applied when the Inserter: no condition is present. For example, a file named news-blog-archive.php should be renamed to hidden-news-blog-archive.php. may i right?

Thanks

**Comment by carolinan** [comment]
@gohelkunjan No, the patterns that are used to create the templates are not usually prefixed with hidden.

**Comment by carolinan** [comment]
Let me close this in favor of the more in depth issue that is meant to cover all pattern names: https://github.com/WordPress/twentytwentyfive/issues/244

**Comment by gohelkunjan** [comment]
Okay
