### ISSUE TITLE
Add default and optional color palettes

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#24]
This is a tracking issue for adding color palettes.
**Note that all colors and slugs listed here may be iterated on during the process.**

## Colors used in the default style

FIgma: https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3112-260&t=qC1CDiog2u4tpIsg-4

In Figma, the default color palette is presented as

Primary `#111111`
Background `#FFFFFF`
Secondary `#686868`
Tertiary `#FBFAF3`
Opacity 20% `#FFFFFF33`
Accent 1 `#FFEE58`
Accent 2 `#F6CFF4`
Accent 3 `#503AA8`

To make it smoother to switch themes, my suggestion would be to:
- Change "Primary"  to "Contrast"
- Change "Background" to "Base"
- Change "Secondary" to " Contrast two"
- Change "Tertiary" to "Contrast three"

Here is a table with a comparison with Twenty Twenty-Four just to compare the color names/slugs
| Twenty Twenty-Five | Twenty Twenty-Four Color Palette  |
|--------------------|----------------------------------|
|  Base `#FFFFFF` | Base - `#f9f9f9`               |
|     -               | Base / Two - `#ffffff`         |
|  Contrast `#111111`  | Contrast - `#111111`           |
|  Contrast / Two `#686868`    | Contrast / Two - `#636363`     |
|  Contrast/ Three `#FBFAF3`   | Contrast / Three - `#A4A4A4`   |
|  Accent `#FFEE58`  | Accent - `#cfcabe`   |
|  Accent / Two `#F6CFF4`  | Accent / Two - `#c2a990`       |
|  Accent / Three `#503AA8`   | Accent / Three - `#d8613c`     |
|  - | Accent / Four - `#b1c5a4`      |

----

## Color palette presets

**WIP: These are not complete**

Color palette presets are partial .json files that only contain color settings.
Each preset uses its own file.
Each file needs to include version, schema, slug, and title.
The files need to be placed in the styles folder, but it is also possible to organize the files using subfolders, for example
styles/color.

### Manrope + Manrope (Dark mode)
Contrast `#D1D1D1`
Base `#1B1B1B`
Accent 1 `#6F6720`
Accent 2 `#CFBEE4`
Accent 3 `#3F3272`

### Beirut & Literata 60P
Contrast `#5F5F5F`
Base `#F8F7F5`
Accent 1 `#FFFFFF`
Accent 2 `#914D0E`
Accent 3 `#191919`

### Volkorn and Fira code
Contrast `#3B3B3B`
Base `#E2E2E2`
Accent 1 `#F5EDFF`
Accent 2 `#650DD4`
Accent 3 `#191919`

### Platypi + Ysabeau Office
Contrast `#516028`
Base `#DAE7BD`
Accent 1 `#EBF6D3`
Accent 2 `#C7F642`
Accent 3 `#303D10`

### Roboto Slab + Manrope
Contrast `#FFFFFF`
Base `#131313`
Accent 1 `#4B52FF`
Accent 2 `#252525`
Accent 3 `#FF6442`

### Literata 60pt + Ysabeau Office
Contrast `#57544B`
Base `#DFDCD7`
Accent 1 `#182949`
Accent 2 `#7A9BDB`
Accent 3 `#F8F5F0`

### Platypi + Literata 60pt
Contrast `#DB9AB1`
Base `#330616`
Accent 1 `#F0FDA6`
Accent 2 `#C1E4E7`
Accent 3 `#DB9AB1`

### Literata 60pt + Fira Sans
Contrast) `#79F3B1`
Base `#4433A6`
Accent 1 `#4433A6`
Accent 2 `#79F3B1`
Accent 3 `#251D51`

**Comment by juanfra** [comment]
Thank you, Carolina. I favor consistency between default themes (so that people can switch themes and get things working right away), so I believe adjusting names, as you suggested, could be the way to go.

Pinging @beafialho @jasmussen for visibility.

**Comment by beafialho** [comment]
I have recently updated the default palette on the Figma file removing the green accent tones so there are 3 accent colors: only yellow, lilac and purple.

Personally, I find the nomenclature "Primary", "Background", "Secondary" and "Tertiary" more intuitive.

I'd also love to know @richtabor's opinion.

**Comment by carolinan** [comment]
Twenty Twenty-Three uses base, contrast, primary.
Twenty twenty-Two uses foreground, background, primary

The problem with "background" is that it is not always used as the background. CSS classes named like `has-background-background` becomes confusing.

**Comment by carolinan** [comment]
So how about:
Base `#FFFFFF`
Contrast `#111111`
Primary `#686868`
Secondary `#FBFAF3`
Opacity 20% `#FFFFFF33`  -Or tertiary?
Accent 1 `#FFEE58`
Accent 2 `#F6CFF4`
Accent 3 `#503AA8`

**Comment by richtabor** [comment]
> The problem with "background" is that it is not always used as the background. 

Yes, this is the case with any color naming, other than "accent" really.

**Comment by carolinan** [comment]
Do you want to disable default color palette, duotones and gradients?

**Comment by efu98** [comment]
Hello! Can I work on this?

**Comment by carolinan** [comment]
Hi @efu98 
Yes, absolutely. The default color palette are already added, but the other optional palettes still need to be added.

First I suggest asking @beafialho if the other palettes should include the same primary, secondary, and opacity as the default palette.

**Comment by carolinan** [comment]
Also the palettes need names, feel free to suggest some.

**Comment by karmatosed** [comment]
I wanted to first say I appreciate the consideration here. I did myself quite like this suggestion:

> Change "Primary" to "Contrast"
> Change "Background" to "Base"
> Change "Secondary" to " Contrast two"
> Change "Tertiary" to "Contrast three"

The issue is primary might not be primary for a custom scheme, the same as secondary - even though they start at that point. It's never easy naming color schemes but we shouldn't not have a complex, awesome one.

Twenty Twenty-Four for example uses the Base/Contrast/Accent combination, so for those moving from it to this it would transition easier.

**Comment by efu98** [comment]
Hello ! Here are the name I found for the palettes, I thought it would be nice to go with words that designate part of a day since you talk about time in the theme description:
- Evening
- Noon
- Dusk
- Afternoon
- Twilight
- Morning
- Sunrise
- Midnight
<img width="975" alt="Capture d’écran 2024-08-22 à 00 14 14" src="https://github.com/user-attachments/assets/4bfcc1f9-8240-4a90-b70b-83d55ac7be57">
Let me know what you think 😄 

@beafialho Should all the palettes include the same Primary, Secondary, and Opacity colours as the default palette?

**Comment by carolinan** [comment]
_Unrelated to the optional color palettes:_
Is the transparent color wrong? Because I think it is invisible...?
![transparent-20](https://github.com/user-attachments/assets/4d1b9ed0-cbc0-4cea-8c7a-854e71f21856)


I think it should be #11111133? https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=559-1942&t=PJROpHtiReAh54XJ-4
![transparent-grey-20](https://github.com/user-attachments/assets/0e5c3857-3e96-416c-b10b-0944aa040b0f)

**Comment by beafialho** [comment]
> Hello ! Here are the name I found for the palettes, I thought it would be nice to go with words that designate part of a day since you talk about time in the theme description:
> 
> * Evening
> * Noon
> * Dusk
> * Afternoon
> * Twilight
> * Morning
> * Sunrise
> * Midnight
>
> @beafialho Should all the palettes include the same Primary, Secondary, and Opacity colours as the default palette?

Thank you for coming up with the names @efu98! For some reason, I did not name them. The palette's colors can be seen above each mockup:

![Captura de ecrã 2024-08-23, às 16 15 38](https://github.com/user-attachments/assets/7fda026f-088b-43fa-9a3e-02c51b2415aa)

**Comment by efu98** [comment]
Here is the updated color palettes added with #107.
In the CTA newsletter, some variations (see Literata 60pt + Ysabeau Office) use multiple colors for the buttons, i am not sure how to handle it. 
### Evening - Manrope + Manrope (Dark mode) 

Contrast `#D1D1D1`\
Base `#1B1B1B`\
Accent 1 `#6F6720`\
Accent 2 `#CFBEE4`\
Accent 3 `#3F3272`\
Primary `#A1A1A1`\
Secondary `#353535`\
Opacity 20% `#FFFFFF33`

### Noon - Beirut & Literata 60P

Contrast `#5F5F5F`\
Base `#F8F7F5`\
Accent 1 `#FFFFFF`\
Accent 2 `#914D0E`\
Accent 3 `#191919`\
Primary `#5F5F5F`\
Secondary `#F1EEE9`\
Opacity 20% `#19191933`

### Dusk - Volkorn and Fira code

Contrast `#3B3B3B`\
Base `#E2E2E2`\
Accent 1 `#F5EDFF`\
Accent 2 `#650DD4`\
Accent 3 `#191919`\
Primary `#5F5F5F`\
Secondary `#DBDBDB`\
Opacity 20% `#3B3B3B33`

### Afternoon - Platypi + Ysabeau Office

Contrast `#516028`\
Base `#DAE7BD`\
Accent 1 `#EBF6D3`\
Accent 2 `#C7F642`\
Accent 3 `#303D10`\
Primary `#516028`\
Secondary `#EBF6D3`\
Opacity 20% `#51602833`

### Twilight - Roboto Slab + Manrope

Contrast `#FFFFFF`\
Base `#131313`\
Accent 1 `#4B52FF`\
Accent 2 `#252525`\
Accent 3 `#FF6442`\
Primary `#DB9AB1`\
Secondary `#4A1628`\
Opacity 20% `#DB9AB133`

### Morning - Literata 60pt + Ysabeau Office

Contrast `#57544B`\
Base `#DFDCD7`\
Accent 1 `#182949`\
Accent 2 `#7A9BDB`\
Accent 3 `#F8F5F0`\
Primary `#F7E6FF`\
Secondary `#D7D3CC`\
Opacity 20% `#1A1A1A33`

### Sunrise - Platypi + Literata 60pt

Contrast `#DB9AB1`\
Base `#330616`\
Accent 1 `#F0FDA6`\
Accent 2 `#C1E4E7`\
Accent 3 `#DB9AB1`\
Primary `#DB9AB1`\
Secondary `#4A1628`\
Opacity 20% `#DB9AB133`

### Midnight - Literata 60pt + Fira Sans

Contrast `#79F3B1`\
Base `#4433A6`\
Accent 1 `#4433A6`\
Accent 2 `#79F3B1`\
Accent 3 `#251D51`\
Primary `#D594F4`\
Secondary `#372696`\
Opacity 20% `#79F3B133`
