### ISSUE TITLE
Audit patterns filenames

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#244]
**Description**

Our goal is to make the naming as intuitive as possible. To achieve this, we need to audit the patterns' names and define proper naming for the different templates in the `patterns` folder. We can check how it was done for the past default themes with patterns so that users are familiar with how we name things out of the box.

I believe we should consider the convention that was historically established in WordPress themes, but as prefixes: `single-*`, `page-*`, `archive-*`, `home-*`, `search-*`. Thinking also of `template-*` as an option.

We also need to find some convention for the other isolated patterns the theme is packed with, an idea could be thinking of the main category as the prefix.

**Comment by carolinan** [comment]
We should also audit the visible names.
I found that under Appearance > Editor > Patterns, names are being cut off:
![image](https://github.com/user-attachments/assets/4476adfd-7ecd-4142-8cd5-861f2a9db3f1)

**Comment by carolinan** [comment]
I looked through some new block themes and the most popular block themes (from different trusted authors) and there does not seem to be an established practice.
One thing stood out, none of them have as many patterns as this 😊 I mean most of them have like 5-6 patterns.

So I don't mind using the same naming as in Twenty Twenty-Four.

**Comment by juanfra** [comment]
Thanks, Carolina! Yes, I hope people will enjoy the different patterns this theme will be shipped with 😅

> So I don't mind using the same naming as in Twenty Twenty-Four.

Sounds good to me, let's do that.

**Comment by jasmussen** [comment]
How much/little can we change after the first beta? @juanfra is this something you would have bandwidth to look at this week? In case you can point me to a specific list of patterns to rename, visible or filenames, I'm happy to take a stab.

**Comment by juanfra** [comment]
> @juanfra is this something you would have bandwidth to look at this week?

Yes, I will find space to look at it this week.

> How much/little can we change after the first beta? 

I am not sure if renaming files would count as adding new things or not. But just in case, I'd like to have a pass before beta 1.

**Comment by juanfra** [comment]
I've been taking a look at this and came to the following:

| Now | Proposed |
| --- | --- |
| comments.php |  |
| banner-about-book.php |  |
| banner-with-description-and-images-grid.php |  |
| contact-centered-social-link.php |  |
| contact-info-locations.php |  |
| contact-location-and-link.php |  |
| cover-big-heading.php | banner-cover-big-heading.php |
| cta-book-links.php |  |
| cta-book-locations.php |  |
| cta-centered-heading.php |  |
| cta-events-list.php |  |
| cta-grid-products-link.php |  |
| cta-heading-search.php |  |
| event-rsvp.php |  |
| event-schedule.php |  |
| events-three-columns-images-and-titles.php | event-3-col.php |
| footer-centered.php |  |
| footer-columns.php |  |
| footer-newsletter.php |  |
| footer-social.php |  |
| footer.php |  |
| grid-videos.php |  |
| grid-with-categories.php |  |
| header-centered.php |  |
| header-columns.php |  |
| header-large-title.php |  |
| header.php |  |
| heading-and-paragraph-with-image.php |  |
| hero-book.php |  |
| hero-full-width-image.php |  |
| hero-overlapped-book-cover-with-links.php |  |
| hero-podcast.php |  |
| hidden-404.php |  |
| hidden-blog-heading.php |  |
| hidden-search.php |  |
| hidden-sidebar.php |  |
| hidden-written-by.php |  |
| instagram-grid.php | media-instagram-grid.php |
| intro-left-aligned-description.php | banner-intro.php |
| intro-short-heading-image.php | banner-intro-image.php |
| logos.php |  |
| more-posts.php |  |
| news-blog-archive-template.php | template-archive-news-blog.php |
| news-blog-home-template.php | template-home-news-blog.php |
| news-blog-query-loop.php | template-query-loop-news-blog.php |
| news-blog-search-results-template.php | template-search-news-blog.php |
| news-blog-single-post-with-sidebar-template.php | template-single-news-blog.php |
| news-blog-with-featured-posts-grid-template.php | template-home-posts-grid-news-blog.php |
| news-blog-with-sidebar-template.php | template-home-with-sidebar-news-blog.php |
| newsletter-signup.php | cta-newsletter.php |
| overlap-images-and-paragraph.php | overlapped-images.php |
| page-coming-soon.php |  |
| page-cv-bio.php |  |
| page-landing-book.php |  |
| page-landing-event.php |  |
| page-landing-podcast.php |  |
| page-link-in-bio-heading-paragraph-links-image.php |  |
| page-link-in-bio-wide-margins.php |  |
| page-link-in-bio-with-tight-margins.php |  |
| page-portfolio-home.php |  |
| photo-blog-archive-template.php | template-archive-photo-blog.php |
| photo-blog-home-template.php | template-home-photo-blog.php |
| photo-blog-page-template.php | template-page-photo-blog.php |
| photo-blog-posts.php | template-query-loop-photo-blog.php |
| photo-blog-search-results-template.php | template-search-photo-blog.php |
| photo-blog-single-post-template.php | template-single-photo-blog.php |
| post-navigation.php |  |
| post-with-left-aligned-content.php |  |
| poster-like-section.php | banner-poster.php |
| posts-personal-blog.php | template-query-loop.php |
| pricing-2-col.php |  |
| pricing-3-col.php |  |
| services-subscriber-only-section.php |  |
| services-team-photos.php | |
| services-three-columns.php | services-3-col.php |
| template-single-offset.php |  |
| testimonials-review-large-image-right.php | testimonials-large.php |
| testimonials-three-columns-six-testimonials.php | testimonials-6-col.php |
| testimonials-two-columns-avatar.php | testimonials-2-col.php |
| text-faqs.php |  |
| text-only-blog-archive-template.php | template-archive-text-blog.php |
| text-only-blog-home-template.php | template-home-text-blog.php |
| text-only-blog-posts.php | template-query-loop-text-blog.php |
| text-only-blog-search-template.php | template-search-text-blog.php |
| text-only-blog-single-post-template.php | template-single-text-blog.php |
| vertical-header-right-aligned-archive-template.php | template-archive-vertical-header-blog.php |
| vertical-header-right-aligned-home-template.php | template-home-vertical-header-blog.php |
| vertical-header-right-aligned-page-template.php | template-page-vertical-header-blog.php |
| vertical-header-right-aligned-post-template.php | template-single-vertical-header-blog.php |
| vertical-header-right-aligned-posts.php | template-query-loop-vertical-header-blog.php |
| vertical-header-right-aligned-search-results-template.php | template-search-vertical-header-blog.php |
| vertical-header.php |  |

Proposed === empty means no changes.

@jasmussen @carolinan @richtabor, I'll appreciate your thoughts on this.

**Comment by richtabor** [comment]
As long as they're more descriptive than "Heading with Image" etc, then it's a win. We need to think about what someone would search for to find it. They don't have to be super long, but intentional.
