### ISSUE TITLE
Add comments section to all "single" templates

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#245]
**Description**

We need to add the comments section to all "single" templates.

Right now the comments template needs to be added to the following templates:

- [ ] News blog single post with sidebar.
- [ ] Photo blog single post.
- [ ] Text only blog single post.
- [ ] Right aligned single post.

**Comment by eirichmond** [comment]
I'm happy to address this.

**Comment by juanfra** [comment]
Thank you @eirichmond, I'll assign it to you.

**Comment by eirichmond** [comment]
@juanfra @carolinan I've just submitted a PR on #266 for this.
