### ISSUE TITLE
Remove the class name "is-style-default"

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#249]
**Description**
The CSS lass name "is-style-default" is added by the block editor if a user selects a block style variation and then switches back to the default style.

Some patterns now have this class name in the markup, and it should be removed because it is not needed.
After updating the markup, the pattern must be tested in the editor so that there are no block validation errors, because typos happen easily. 😃 

**Example**
Image block:
`"className":"wp-block-image size-large is-style-default"` can be changed to `"className":"wp-block-image size-large"`.
`<figure class="wp-block-image size-large is-style-default">` can be changed to `<figure class="wp-block-image size-large">`

```
<!-- wp:image {"aspectRatio":"1","scale":"cover","linkDestination":"none","className":"wp-block-image size-large is-style-default"} -->
<figure class="wp-block-image size-large is-style-default"><img src="<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/location.webp" alt="The business location" /></figure>
<!-- /wp:image -->
```

**Comment by noruzzamans** [comment]
@carolinan I am interested in working on these issues.
