### ISSUE TITLE
List of relevant Gutenberg issues and pull requests

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#25]
## Hide the current post from the query loop
Needs dev.
https://github.com/WordPress/gutenberg/issues/42810

## Filter post formats in the query loop
Needs dev with REST API experience
Needs design
Needs tests and testing
https://github.com/WordPress/gutenberg/pull/64167
https://github.com/WordPress/gutenberg/issues/53049

## Enable creating post format archive templates in Site Editor
Needs dev.
https://github.com/WordPress/gutenberg/issues/53049

## Style Form elements in theme.json
Needs decision about which selectors to use. Should we target all inputs, or only specific types?
- If this can be implemented in 6.7, it can be used for the search block.
https://github.com/WordPress/gutenberg/pull/51337

**Comment by beafialho** [comment]
For the [FAQs pattern](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-2076&t=80iDW7uaB7dX9Xpa-4) this issue seems relevant: https://github.com/WordPress/gutenberg/pull/64119#top

https://github.com/WordPress/gutenberg/issues/21584

**Comment by carolinan** [comment]
Line height improvements https://github.com/WordPress/gutenberg/issues/56227

**Comment by beafialho** [comment]
Add Featured Image upload for Categories and Tags: https://github.com/WordPress/gutenberg/issues/64595

**Comment by carolinan** [comment]
Display caption for featured images
https://github.com/WordPress/gutenberg/issues/40946

**Comment by carolinan** [comment]
Featured image fallbacks (for the photo blog)
https://github.com/WordPress/gutenberg/issues/39170
https://github.com/WordPress/gutenberg/issues/34865

**Comment by efu98** [comment]
Hello! Are there any priority on which issues to solve first?

**Comment by carolinan** [comment]
> Hello! Are there any priority on which issues to solve first?

The first one on the list above.

**Comment by beafialho** [comment]
I'm not sure if this one is close to being implemented, but if it's not, we may consider adding similar code to TT5 to prevent widows and orphans in text: https://github.com/WordPress/gutenberg/issues/55190

**Comment by juanfra** [comment]
Standardized way to modify interactive states (:hover, :focus .etc) for button variations: https://github.com/WordPress/gutenberg/issues/38277

Context [here](https://github.com/WordPress/twentytwentyfive/pull/157#discussion_r1738104103).

**Comment by carolinan** [comment]
Presets for border radius: https://github.com/WordPress/gutenberg/issues/64041

**Comment by carolinan** [comment]
Add a z-index control for blocks where position is/can be set  https://github.com/WordPress/gutenberg/issues/60411

**Comment by juanfra** [comment]
Accordion block for FAQ https://github.com/WordPress/gutenberg/issues/21584

**Comment by carolinan** [comment]
Button: Add support for :hover in variation theme.json
https://github.com/WordPress/gutenberg/issues/55359

**Comment by efu98** [comment]
Hello! I have created two PR to closes the two issues about the post feature image Wordpress/gutenberg#65107 Wordpress/gutenberg#65022

**Comment by carolinan** [comment]
Allow pattern files in subfolders: https://github.com/WordPress/gutenberg/issues/50144

**Comment by jasmussen** [comment]
Section styles are stripped out of query loops: https://github.com/WordPress/gutenberg/issues/65644

**Comment by carolinan** [comment]
https://github.com/WordPress/gutenberg/issues/65812

**Comment by carolinan** [comment]
I am closing this since we have ran out of time to work on these in this release cycle.
