### ISSUE TITLE
Remove `queryId` from Query Blocks

### ISSUE THREAD

**Issue by codersantosh** [WordPress/twentytwentyfive#262]
**Description**
 The `queryId` parameter needs to be removed from most of the query blocks.

**Comment by derekhassan** [comment]
Hey Santosh,

I'd be happy to take care of this 🙌

**Comment by carolinan** [comment]
Please remember that there are patterns that are still being worked on, and patterns that will be iterated on before release, so this should be done late to avoid having to do it multiple times.

**Comment by derekhassan** [comment]
Thanks for the heads up, I'll hold off for now 👍

**Comment by carolinan** [comment]
I searched and did not find any "queryId" 's left, so I am closing this as completed.
