### ISSUE TITLE
Use Props Bot Action

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/twentytwentyfive#27]
The [WordPress Props bot Action](https://github.com/WordPress/props-bot-action) is designed to ensure a consistent contributor recognition.  I think this project should use it as well.

**Comment by aaronjorbin** [comment]
@carolinan @juanfra Assuming y'all are on board for this, I'm happy to write the PR to setup the action. 

You can read more about the action at https://make.wordpress.org/core/2024/02/01/new-commit-message-requirements-in-git-hello-props-bot/

**Comment by juanfra** [comment]
@aaronjorbin thanks so much for bringing this up, and it sounds great to me. Unless @carolinan has any observations, I'd say we could leverage the bot functionality to ensure contribution recognition consistently.  🚀
