### ISSUE TITLE
Add "Page with no title" template

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#272]
Similarly to Twenty Twenty-Four, we have some full page patterns in Twenty Twenty-Five that are intended to be used without a title when a page is created. The theme will benefit from a "page with no title" template taking the same approach, so we can have pages like the examples below:

![patterns](https://github.com/user-attachments/assets/7b776a3d-50f2-40c5-90f0-1f70cba45425)

This is what that template looks like in Twenty Twenty-Four:
```
<!-- wp:template-part {"slug":"header","area":"header","tagName":"header"} /-->

<!-- wp:group {"tagName":"main","style":{"spacing":{"margin":{"top":"0"}}}} -->
<main class="wp-block-group" style="margin-top:0">
	<!-- wp:post-content {"lock":{"move":false,"remove":true},"layout":{"type":"constrained"}} /-->
</main>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","area":"footer","tagName":"footer"} /-->
```

I can imagine the margins between these sections will have to be `0` for the template parts and content to have no awkward blank spaces between them.

**Comment by juanfra** [comment]
Thanks @beafialho!

As a reference, [this is](https://github.com/WordPress/twentytwentyfour/blob/trunk/templates/page-no-title.html) how it was done for Twenty Twenty-Four.

**Comment by noruzzamans** [comment]
@juanfra I have submitted a PR for this issue. Please review. Thanks
