### ISSUE TITLE
The Quote block style is not working properly.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfive#277]
**Description**
Hello Team,

I have reviewed the "Quote Block" into the twenty-twenty-five theme and found that its block style is not working as expected on editor side & front-end site.

**Step-by-step reproduction instructions**

- Go to admin and select the "Quote" block first.
- Add its paragraph text & citation text.
- Now, try to change it's block style from "Default" to "Plain"
- Update the page and check its admin text and front-end text.

**Expected behavior**
I think that the right border should be remove when we select block style "Plain".

Here, I have provided expected behaviour screenshots:

**Editor side:**
![quote_block_editor_side](https://github.com/user-attachments/assets/402f6958-512e-4ff7-884e-8d4084524f7c)

**Front-end side:**
![quote_block_front_end_side](https://github.com/user-attachments/assets/014d7053-3fd5-47ba-b6df-f956066580ad)

**Screenshots**

**Editor side:**
![quote_block_editor_side_border](https://github.com/user-attachments/assets/30cd8e3e-d4f8-4baa-b5d5-9fbf73842c7a)

**Front-end:**
![quote_block_front_end_border](https://github.com/user-attachments/assets/509b03fe-8f3b-4848-a786-a319207a0a07)

**Issue video:**

https://github.com/user-attachments/assets/5310a16b-3975-4de6-b851-1ff4efce60eb

**Environment info**

- Device: Macbook M1
- OS: 14.6.1 (23G93)
- Browser: Google Chrome
- Version 128.0.6613.120 (Official Build) (arm64)
- WordPress version: 6.6.2 running, Gutenberg 19.2.0 , Theme active: Twenty Twenty-Five,

**Additional context**
I have tested this issue with active and inactive Gutenberg plugin and I am getting this issue.

Thanks,

**Comment by carolinan** [comment]
Hi

The quote block styles are being added as part of this pull request: https://github.com/WordPress/twentytwentyfive/pull/118

**Comment by carolinan** [comment]
@viralsampat-multidots The new styles have been added, would you be able to test again?

**Comment by viralsampat-multidots** [comment]
@carolinan Thank you so much for the update.

Yes, sure. I will test it again and will provide details updates for the same.

Thanks,

**Comment by viralsampat-multidots** [comment]
Hello @carolinan 

I have tested the "Quote" block styling issue with latest theme. Now, its looks good. and its working for me.

Thanks,

**Comment by juanfra** [comment]
Thanks for the update. 

> I have tested the "Quote" block styling issue with latest theme. Now, its looks good. and its working for me.

Ok, I'm closing this issue.
