### ISSUE TITLE
Right aligned blog with vertical heading: Make sure there is only one H1 heading

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#279]
**Description**

On the right aligned blog with vertical heading, the site title is set to the H1 heading level.
The site title should not be used as the main H1 of the page, since it describes the site, not the content on the current page.
On some of the templates, there are currently two H1 headings.

Tasks:
- In the templates for this design, set the site title to a paragraph but make sure that it uses all the correct typography settings. The **look** of the site title mustnot change.
- Make sure each template has a single H1. In some of the templates, the H1 already exists, the others need to be updated.

**Comment by carolinan** [comment]
Actually, the "header" in these templates need to be added as a template part, otherwise, the navigation will not be the same  for the template set. The user may accidentally add one menu for the home and a different one for the single.

**Comment by KevinTaron** [comment]
> Actually, the "header" in these templates need to be added as a template part, otherwise, the navigation will not be the same for the template set. The user may accidentally add one menu for the home and a different one for the single.

Is that even possible? In the "header"-templatepart we have a row instead of a stack and the Navigation is not Overlay-Menu: "Always"

**Comment by carolinan** [comment]
It needs to be a new template part.

**Comment by KevinTaron** [comment]
added a pull request for this #285
