### ISSUE TITLE
Default single post: The category above the post title needs to be moved

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#291]
**Description**

In the default single post template / pattern, there is a category above the main heading.
This needs to be moved somewhere below the heading.
See https://github.com/WordPress/twentytwentyfive/issues/150

-Please await information about the new position for the category before starting to work on this.

**Comment by beafialho** [comment]
This is how it should look instead:

![Captura de ecrã 2024-09-13, às 10 02 29](https://github.com/user-attachments/assets/d302b465-7587-480c-8e90-d53fe202e78d)
