### ISSUE TITLE
Don't include left and right padding in fullwidth constrained patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#300]
WordPress will add the outer padding value of the site instead. If we fix these values, then the control in styles > layout will not change the outer padding. 

Here's what happens if the values are fixed: 

https://github.com/user-attachments/assets/94d91ad2-1375-46d2-99a9-e2ce8d2c633c

And here's when the fixed left/right padding values are removed: 

https://github.com/user-attachments/assets/bb43da31-d922-479b-a64c-74f65e3a0e16

**Comment by carolinan** [comment]
This is already a known issue for some patterns, as discussed in the open pull requests.

**Comment by carolinan** [comment]
Please motivate in detail why the patterns should change based on the _global spacing used to manage the spacing on the full pages._
Without a motivation it is difficult for other contributors to make informed decisions.

**Comment by richtabor** [comment]
> If we fix these values, then the control in styles > layout will not change the outer padding.

I did include motivation. If we provide fixed values, then the site's outer padding value will not apply. You can change this control value, but have almost no effect (or worse, a variable effect).

If we want people to be able to change the left/right padding of their sites (which we should, as core supports it) then we should make it possible.

**Comment by juanfra** [comment]
@richtabor can you please confirm if this one was fixed [here](https://github.com/WordPress/twentytwentyfive/pull/397)?
