### ISSUE TITLE
Audit featured patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#303]
Once we're settled on patterns let's audit which are featured. They should be the best of the best. 

![CleanShot 2024-09-13 at 16 43 42](https://github.com/user-attachments/assets/b7978331-a29c-4c4a-8c2a-09c1cb3999c1)

**Comment by beafialho** [comment]
I think **all** the Twenty Twenty Five patterns could be "Featured".

**Comment by jasmussen** [comment]
I'd agree that _most_ can be featured, but there are a couple of slightly more utilitarian patterns that may not be worth featuring, like "Comments":

![Screenshot 2024-09-24 at 13 54 15](https://github.com/user-attachments/assets/25ca6406-d0bc-475f-8af5-93f35554448f)

**Comment by carolinan** [comment]
@beafialho @juanfra  this issue needs more attention.

**Comment by beafialho** [comment]
Here's an idea for the featured patterns:

- [Coming Soon page](https://2025.wordpress.net/coming-soon-page/)
- [Link in bio one](https://2025.wordpress.net/link-in-bio-one/)
- [Link in bio two](https://2025.wordpress.net/link-in-bio-two/)
- [Banner with description images grid](https://2025.wordpress.net/banner-with-description-images-grid-pattern/)
- [Contact location and link](https://2025.wordpress.net/contact-location-and-link/)
- [Overlapping images and paragraph on the right](https://2025.wordpress.net/overlapping-images-and-paragraph-on-the-right/)
- [Cover with big heading](https://2025.wordpress.net/images-cover-with-big-heading/)
- [Grid layout with products and link](https://2025.wordpress.net/grid-layout-with-products-and-link/)
- [Instagram grid](https://2025.wordpress.net/instagram-grid/)
- [Services, team photos](https://2025.wordpress.net/services-team-photos/)
- [Short heading and paragraph with image on the right](https://2025.wordpress.net/short-heading-and-paragraph-and-image-on-the-left/)
- [CV/Bio landing](https://2025.wordpress.net/cv-bio-landing/)
- [Product/event landing](https://2025.wordpress.net/product-event-landing/)
- [Book landing](https://2025.wordpress.net/book-landing/)
- [Podcast landing](https://2025.wordpress.net/podcast-landing/)
- [Business home page](https://2025.wordpress.net/business-homepage/)

It would be ideal if we could show the section patterns first and the page patterns after, given its length, they'd take up a lot of space in the pattern sidebar list.

**Comment by juanfra** [comment]
I like the list Bea put together. I'm unaware if we have the ability to set an order, though.
