### ISSUE TITLE
Adjust opacity color to work better across light and dark variations

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#304]
The current opacity color only works great on light backgrounds. If we adjust it a bit I'm sure we can find a color (perhaps around `#7a7a7a33` that works better on light and dark.

The original is on the left: 

https://github.com/user-attachments/assets/35c732d0-704e-419e-91b0-9ba561ae06fd

cc @beafialho

**Comment by beafialho** [comment]
It's a little hard to see in both light and dark. Why can't the opacity color preset just use the opacity color tone from each style?

**Comment by carolinan** [comment]
> It's a little hard to see in both light and dark. Why can't the opacity color preset just use the opacity color tone from each style?

I am not sure I understand. "opacity color tone from each style" ?

I think you meant that the color palette presets have different colors for the opacity. For example sunrise has `DB9AB133`.
The section styles can only apply the current color palette.

**Comment by richtabor** [comment]
> The section styles can only apply the current color palette.

Section styles can't define new colors, only assign colors-and only when values are not applied directly to blocks (like the border color is).

**Comment by richtabor** [comment]
We can try using color-mix for that opacity color in theme.json using a % of the current color—rather than a fixed value. I think that could work.

**Comment by jasmussen** [comment]
The proposed solution can work, if we don't find better alternatives 👍 👍

**Comment by carolinan** [comment]
What about a block style for a column with border, to remove the color from the markup?

**Comment by carolinan** [comment]
So like this?  `color-mix(in srgb, currentColor 80%, transparent);`
or 20%?
