### ISSUE TITLE
Text styles

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#305]
Any reason why we wouldn't leverage more block style variations? 

I noticed a number of uses of this for example: 

![CleanShot 2024-09-13 at 16 49 50](https://github.com/user-attachments/assets/111c0616-e3a6-46fe-8b48-be0bda5625bd)

(XL font, 1.2 line height)

If we can identify a few candidates, it would be nice to share styles across headings, paragraphs, perhaps even quotes.

**Comment by carolinan** [comment]
Lets start with this one XL, 1.2 line height on the paragraph block, and test what the experience is like.

There are now **at least** 12 font sizes in the theme, and I think that replacing all 7 of the custom presets with style variations for the heading block would become too overwhelming. But to be clear, that is only my own subjective opinion.

**Comment by richtabor** [comment]
Yea, we don't need all these expressed as text styles-only the combination of font, size, and line heights that are commonly used and expected.
