### ISSUE TITLE
Media or Gallery category? 

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#306]
I noticed we're using "Media" category, for what looks like gallery type patterns. Any reason why we're not using the gallery category? Currently gallery is only core patterns: 

![CleanShot 2024-09-13 at 16 56 16](https://github.com/user-attachments/assets/ada74de6-b4bd-45c8-952e-30ee25e56ea2)

**Comment by carolinan** [comment]
All patterns have not been reviewed yet, as you can see from the ongoing work on the open pull requests and issues, the focus has been on creating the patterns.

**Comment by carolinan** [comment]
I think this is because none of them use the gallery block. I think the Instagram grid could be under the gallery category.

I don't think the "Event schedule" or "Grid with categories" fit under either of these.

**Comment by richtabor** [comment]
> I think this is because none of them use the gallery block. I think the Instagram grid could be under the gallery category.

Agreed. It doesn't matter what blocks are used, but rather the presentation of those blocks. If it's visually a gallery, it should render in this category.
