### ISSUE TITLE
Remove default presets for colors, gradients, and duotone filters

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#308]
We should remove the default presets for colors, gradients and duotones. They don't add to the experience; likely get in the way. 

![CleanShot 2024-09-13 at 17 02 16](https://github.com/user-attachments/assets/67034353-1b90-4627-94ef-469d24e0b1ca)
![CleanShot 2024-09-13 at 17 02 32](https://github.com/user-attachments/assets/25504aa6-ff38-4839-874f-bab008c14460)
![CleanShot 2024-09-13 at 17 03 01](https://github.com/user-attachments/assets/47bd2386-0296-4d31-838d-f1f62332e51d)

**Comment by carolinan** [comment]
@beafialho Wanted to keep them because there are no theme specific duotones and gradients*.

(Since then I believe one gradient was added to support one pattern)

**Comment by beafialho** [comment]
I don't have strong feelings about this. I thought keeping them would be fine since there are no specific duotones and gradients to the theme (besides one duotone effect from the "Midnight" variation). But I can also see how they can get "in the way".

**Comment by carolinan** [comment]
Some of the style variations uses a pure black #000 and white #FFF, those are part of the default color palette, but they can still be used _in the code_ if the default color palette is turned off.
