### ISSUE TITLE
Add, test, and adjust pattern viewport widths

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#310]
**Description**

Some of the template patterns which have previews in the Design panel are missing a viewport width setting in the pattern file header.
The viewport width setting is "An integer specifying the intended width of the pattern to allow for a scaled preview of the pattern in the inserter."
There may be some other patterns that benefit from the Viewport width setting, depending on their design.
Patterns that are never previewed do not need a viewport width setting; Patterns that are not used as a full page design and have Inserter set to no.

Whether a pattern needs a viewport width setting or not can be subjective; 
Preview the pattern in the inserter (or the Design panel, depending on pattern type) and confirm that wide or tall patterns do not look "squished". Add and adjust the viewport width until the pattern looks its best.
When submitting pull requests for this issue, it would be helpful to have before and after screenshots.

-I believe that the flickering that was seen in the Design panel in earlier versions of the theme has been fixed, but please test that there are no side effects when hovering over the patterns or when scrolling through the pattern lists.

Example:
```
<?php
/**
 * Title: Photo blog home
 * Slug: twentytwentyfive/photo-blog-home
 * Template Types: front-page, index, home
 * Viewport width: 1400
 * Inserter: no
 *
 * @package WordPress
 * @subpackage Twenty_Twenty_Five
 * @since Twenty Twenty-Five 1.0
 */

?>
```

**Comment by carolinan** [comment]
To clarify, I do not mean the example to be copied as is. It is an example of a pattern file header that has a Viewport width setting. The other settings must be unchanged.

**Comment by mathew-crisp** [comment]
I am working on this here at WordCamp
