### ISSUE TITLE
Task: Test responsiveness

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#311]
**Description**

Please hold off this testing until the "blocked" label has been removed, once the patterns have been added to the theme.

**Step-by-step reproduction instructions**
You can test the responsiveness on your devices on your own local network, a live hosted WordPress site, [or using this Playground link for the theme](https://playground.wordpress.net/?mode=seamless#{%22landingPage%22:%22/%22,%22phpExtensionBundles%22:[%22kitchen-sink%22],%22login%22:true,%22steps%22:[{%22step%22:%22installTheme%22,%22themeZipFile%22:{%22resource%22:%22url%22,%22url%22:%22https://github-proxy.com/proxy/?repo=WordPress/twentytwentyfive%22}}]})

Please test on a real device if possible, since the experience in for example the browser developer tools may differ.

Create new pages and posts.
Add both smaller patterns, full width patterns, and the different templates.
Try the menus.

Templates are changed by going to Appearance > Editor > Templates, selecting the template type, and changing the pattern in the Design panel in the settings sidebar.

Test on portrait and landscape modes.

Look for and report problems that are obvious issues.

**Comment by klf6890** [comment]
I'm working on this for Contributor Day

**Comment by klf6890** [comment]
I'm not sure if this is an intentional design choice but in the pattern Heading and Paragraph with Image on Right, at the mobile level, the padding on the left and right are not equal. Again, unsure if a design choice as the section is indented on larger sizes, but it does look odd when combined with other patterns which mostly seem to adhere to a standard padding on the left and right. Screenshot attached from an iPhone 13 with a browser width of 390px  ![IMG_4257](https://github.com/user-attachments/assets/c2db4288-1479-420c-82a8-90672c711e5b)

**Comment by klf6890** [comment]
All patterns were testing on an iPhone 13, screen size 390px wide, I'm flagging these issues and including screenshots as they really just need to be reviewed. Some could be design choices, but if it looked odd to me on the mobile level, it's included here.

- **Two Headings and a List** — larger spacing on mobile
![contributor-day-two-headings-list](https://github.com/user-attachments/assets/95535de0-59e0-4be6-8bf9-5bcf154936da)
- **Cover Image with Bold Heading and Button** - Heading cropped off on longer words that are longer than width of screen
![contributor-day-cover-image](https://github.com/user-attachments/assets/a0183529-a7ac-4589-931f-08ddaf08006d)
- **Event pattern** - padding on left and right is larger than most patterns
![contributor-day-event](https://github.com/user-attachments/assets/185314b0-4707-4c7a-87f8-cab0af52e4a9)
- **Three columns with offset images** - really large gaps between anything on mobile, may want to minimize this on mobile
![contributor-day-offset-images](https://github.com/user-attachments/assets/80c1e3cf-c31d-4cd5-85d4-816943b57152)
- **Posts - Grid pattern** - mobile patterns are larger than most sections
![contributor-day-post-grid](https://github.com/user-attachments/assets/1c70f88a-5551-4614-9343-d17f3b38cb36)
- **Two columns of text with offset heading** - no padding on left/right edge on mobile
![contributor-day-two-columns-of-text-with-offset-heading](https://github.com/user-attachments/assets/996db3e8-2457-4ef1-9444-9b08990ce036)

**Comment by carolinan** [comment]
@klf6890 Thank you for the testing and reports.

**Comment by kimclow** [comment]
I'm finding mobile a pretty solid experience! 
I have found two items which are very small, but not sure if they're worth mentioning: 

1. If WooCommerce is installed, the image in the default store page doesn't align with the content block. 
![371103510-0b6ced12-b0ec-46c3-9d23-b35922220ccc](https://github.com/user-attachments/assets/9d245529-2e40-4d0f-8c66-ddd41e5b8f6b)



2. The VideoBlock is displaying with a blank image on mobile: 
![IMG_6791](https://github.com/user-attachments/assets/6fd4351c-044f-4ee0-a644-8588ae220dcd)

Here's how it looks on desktop as a comparison (and yes, look how cute my dog was as a pup!)

<img width="1519" alt="Screenshot 2024-09-26 at 13 01 05" src="https://github.com/user-attachments/assets/d0d0b6c7-350c-4c5c-bf2a-b32bd0743345">

**Comment by carolinan** [comment]
@klf6890 @kimclowa8c What are your wordpress.org usernames?  I want to make sure you get props for testing.

**Comment by carolinan** [comment]
I tested 2025.wordpress.net on Pixel 8 pro, Chrome, and I did not see any obvious layout issues:
As I have already mentioned I struggle with the small default font size for the content, and it is even smaller in the cite of the testimonial patterns.

In the "Tell your story" "Hero with full width image" pattern, the button is cut off, half of it is below the fold which is not great.

**Comment by dugyen** [comment]
**Testing responsiveness for our awaited Twenty Twenty-Five Theme** 
 **Description**
Test responsiveness of WordPress 6.7 Twenty Twenty-Five Theme 

 **Environment**
- WordPress: 6.7-beta3
- PHP: 8.3.10
- Server: nginx/1.21.4
- Database: mysqli (Server: 5.7.44-log / Client: mysqlnd 8.3.10)
- Browser: Chrome 129.0.0.0
- OS: macOS
- Theme: Twenty Twenty-Five 1.0
- MU Plugins: None activated
- Plugins:
  * Gutenberg 19.4.0
  * Test Reports 1.1.0
  * WordPress Beta Tester 3.6.0

**Steps** 
1. Create new pages and posts.
2. Add both smaller patterns, full-width patterns, and the different templates.
4. Try the menus.
5. Templates are changed by going to Appearance > Editor > Templates, selecting the template type, and changing the pattern in the 
     Design panel in the settings sidebar.
6. Test on portrait and landscape modes.
7.  Look for and report problems that are obvious issues.

 **Expected Results**
1.  ✅ Twenty Twenty Theme is responsive with browsers, mobile, desktop and tablets

 **Actual Results**
1.   ✅ Twenty Twenty Theme is Responsive with WordPress 6.7-beta 3



### Supplemental Artifacts
![Image](https://github.com/user-attachments/assets/79e9b1b0-b698-4f49-9ad8-a69f0614c3d7)
https://vioo.cc/v/5ljTe

**Comment by carolinan** [comment]
We triaged this issue on Monday and agreed to close this as completed.

**Comment by kimclow** [comment]
> What are your wordpress.org usernames? I want to make sure you get props for testing.

Thank you @carolinan. Mine is `kimclow`

**Comment by klf6890** [comment]
> What are your wordpress.org usernames? I want to make sure you get props for testing.

Oh, thanks @carolinan! Mine is KristinCodesWP
