### ISSUE TITLE
Task: Test RTL, Japanese, Chinese, and Korean

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#312]
**Step-by-step reproduction instructions**
Look for and report problems that are obvious issues.

Create new pages and posts.
Add both smaller patterns, full width patterns, and the different templates.
Try the menus.

Templates are changed by going to Appearance > Editor > Templates, selecting the template type, and changing the pattern in the Design panel in the settings sidebar.

Make sure to test the "right-aligned blog" designs with the vertical header.

**Comment by carolinan** [comment]
Potential issues:

The link post format pattern has an arrow icon that I believe is pointing in the wrong direction on RTL? I don't know if it is solvable.

<img width="727" alt="link post format with a text, a custom link, and an arrow icon" src="https://github.com/user-attachments/assets/de282713-87a4-4974-aa01-e6450b18dcb6">

**Comment by juanfra** [comment]
I just asked a friend who's native in Hebrew (and a theme designer) and she told me that ideally it should point to the left.

**Comment by juanfra** [comment]
[Removed the icon](https://github.com/WordPress/twentytwentyfive/pull/446), for now. And we can revisit later to see if we find an elegant solution for it.

**Comment by beafialho** [comment]
@carolinan I've tried changing the site language but the patterns and templates are showing up in English, is this expected or am I missing a step?

**Comment by juanfra** [comment]
@beafialho the patterns will still be shown in English as the contents have yet to be translated to other languages, but the text orientation should change.

**Comment by beafialho** [comment]
Ok, I also assumed they have yet to be translated. Thanks!
