### ISSUE TITLE
Task: Test print styles

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#313]
**Description**
Try printing different templates from the front of the site and then report any obvious problems.

**Step-by-step reproduction instructions**
You can use Ctrl+ P or Ccommand + P to open the print preview.

**Comment by krismapp** [comment]
I'm working on this for contributor day

**Comment by krismapp** [comment]
| Page | Test Result |
|--------|--------|
| Event RSVP | looks good |
| CV | looks good |
| Podcast | Large white space between first two sections when printing in landscape |
| link in bio | large extra space below photo |
| landing page for events | spacing issues in grid section | 
| coming soon | looks good |
| blog homepage | looks good |

**Comment by carolinan** [comment]
Hi @krismapp 
What is your wordpress.org account name? I want to make sure you get the credit for testing.

**Comment by krismapp** [comment]
Hey Carolina!
I didn’t realize I didn’t have a .org account, but now I have made one 😊 .. the user name is kristymapp

Thanks!!

From: Carolina Nymark ***@***.***>
Date: Friday, October 18, 2024 at 2:55 AM
To: WordPress/twentytwentyfive ***@***.***>
Cc: Kristy Mapp ***@***.***>, Mention ***@***.***>
Subject: Re: [WordPress/twentytwentyfive] Task: Test print styles (Issue #313)

Hi @krismapp<https://github.com/krismapp>
What is your wordpress.org account name? I want to make sure you get the credit for testing.

**Comment by carolinan** [comment]
I have not been able to see how we can reduce the large space, mentioned above, which seems to be because of the position of the images / images being pushed to a second paper.

I recommend closing this @juanfra  @beafialho

**Comment by juanfra** [comment]
Sounds good, thanks Carolina!
