### ISSUE TITLE
Can the number of images be reduced?

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#314]
Some of the images are included more than once but in different formats / sizes.
Would it be possible to use the aspect ratio or sizing in the patterns instead of using separate image files?

**Comment by jasmussen** [comment]
Quick screenshot of the bundled images:

![Screenshot 2024-09-24 at 14 03 59](https://github.com/user-attachments/assets/941db10f-e0fc-4455-972e-4548f767253d)

From a quick glance, the images that can potentially be deduplicated are:

1. cv-bio / team-photo-1
2. team-photo-3-976x976 / team-photo-3

Of those, **1** is not trivial to duplicate becaues the manual crop is top aligned:

![Screenshot 2024-09-24 at 14 07 11](https://github.com/user-attachments/assets/4c45d6cc-4f38-4b75-9098-77d77fde4549)

With a square aspect ratio applied, the crop moves the eyes farther from the center and results in a poorer crop:
![Screenshot 2024-09-24 at 14 06 35](https://github.com/user-attachments/assets/3fada39d-657c-4c82-9e36-f1617cfab52b)

In the case of **2** it seems like we can definitely retire one or the other. I'll spin up a PR.
