### ISSUE TITLE
Task: Translatable text in the HTML files must be turned into patterns

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#323]
**Description**
All HTML files need to be reviewed to locate and fix any remaining text strings.
**All** the text in the theme needs to be translation ready, and text in HTML files can't be translated.
This includes texts inside attributes, such as placeholders and aria labels, and any other default texts that are added when a block is inserted in the editor.

If you find that a pattern is needed, **please check carefully if there is an existing pattern** that can be inserted in the template, before creating a new.

**Comment by carolinan** [comment]
Home.html: The Blog heading must be translatable
Index.html: The Blog heading must be translatable

single.html: The "written by" must be translatable. This is already in progress here: https://github.com/WordPress/twentytwentyfive/pull/320

**Comment by up1512001** [comment]
@carolinan can you please review this PR https://github.com/WordPress/twentytwentyfive/pull/335 for adding i18n to `Blog` heading string.
