### ISSUE TITLE
Task: Make the inclusion of the header and footer template parts consistent

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#325]
**Description**

In some of the patterns and templates, the header and footer parts are included with the `area` attribute:
`<!-- wp:template-part {"slug":"header","area":"header","tagName":"header"} /-->`
and in others without the `area` attribute:
`<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->`

As long as the part is registered to the area in theme.json, adding or removing the `area` or the `tagName` in the block markup, does not seem to make any difference.
A part simply included as `<!-- wp:template-part {"slug":"header"} /-->` also uses the correct area in the editor, and the `<header>` tag.

Task:
Update all instances of the template part inclusions to not use any other attributes than the `slug`:
`<!-- wp:template-part {"slug":"header"} /-->`
`<!-- wp:template-part {"slug":"footer"} /-->`

<details><summary>Old description</summary>

There are 4 themes in the theme directory that use all 3:
`<!-- wp:template-part {"slug":"header","area":"header","tagName":"header"} /-->`
https://wpdirectory.net/search/01J7WFDQ5R18YJGXQCMC1AQKKJ

202 that use
`<!-- wp:template-part {"slug":"header","tagName":"header"} /-->`
https://wpdirectory.net/search/01J7WFFP7VQKNA1ZDW9XDEFHHT

7 that use
`<!-- wp:template-part {"slug":"header","area":"header"} /-->`
https://wpdirectory.net/search/01J7WFJ62CV4FT8N0WHDJC50YH

44 only use `<!-- wp:template-part {"slug":"header"} /-->`

Of course this does not include any themes where the slug is something else.

The theme developer handbook uses the tagName but not the area :sweat_smile:
https://developer.wordpress.org/themes/templates/template-parts/#how-do-template-parts-work
Twenty Twenty-Four uses all 3, while Twenty Twenty-Two and three uses tagName but not the area.

So, which of these are correct?
</details>

**Comment by carolinan** [comment]
**_Without testing,_** I guess one of the few times this can go wrong is if someone replaces the theme.json and forgets to add template parts back, or changes it in a child theme.

**Comment by juanfra** [comment]
My vote is to avoid redundancy. Personally, if there's a default, I prefer not to add things as "parameters".

**Comment by carolinan** [comment]
Yeah lets go with that option, the theme is not planning to use any parts that are not listed in theme.json.

**Comment by alexandrebuffet** [comment]
Bonjour from the WordCamp Bretagne contributors day! I've just created #435 which removes "area" and "tagName" attributes in templates.

**Comment by juanfra** [comment]
Thank you!
