### ISSUE TITLE
Home: The "more posts" lists the same posts as the main query.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#326]
**Description**

On the default home template, the main query is set to inherit from the template (and this is correct) which means that
the number of posts shown is controlled by the setting in the admin area: Settings > Reading Settings > Blog pages show at most.
This means that the second query under the heading "More posts" shows the title and date of the same posts.
(Once you navigate to the second page of the result, this is a non issue, it is only a problem on the first page).

![home-more-posts](https://github.com/user-attachments/assets/1e1c47e1-3d5a-4d38-a775-780bd9b551c3)

There is no way to offset this query to same number as in the reading settings of the first query.
By changing the sorting order and use for example oldest to newest, the posts may be different, but it would also promote old content, which may be undesirable.

**Comment by beafialho** [comment]
Maybe we remove this pattern from the Blog templates to avoid this confusing situation and leave it only in the Single Posts.

**Comment by bobbylee-noble** [comment]
Working on this for contributor day :)

**Comment by carolinan** [comment]
Reopening this as a reminder to check if this should be removed from other blog templates.
