### ISSUE TITLE
Remove top and bottom margin 0 on full width patterns

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#328]
During development of the full width patterns, top and bottom margin was set to 0 because when the pattern has a background color, the sections are not "seamless": When the default global spacing between blocks is applied, there is a gap between the two colored sections:
<img width="1231" alt="gap between two patterns, where the body background is seen" src="https://github.com/user-attachments/assets/8251cb0a-b36a-4600-9c2e-e4b0ff55a638">

But removing margins had the side effect that the block is too close to other type of content:
<img width="1231" alt="no-top-margin" src="https://github.com/user-attachments/assets/e3ed23bf-eb10-4a65-b523-f29472cb6610">

There is no way to only remove the margin when two full width blocks follow eachother, without using custom CSS:
the better way would be for the user wrap to the two patterns inside another group and set the block spacing to 0.

I think the best would be to remove the margin setting from the patterns, and then on the full page patterns, where these full width patterns are combined into one cohesive layout, wrap them inside an extra group with block spacing set to 0.

**Comment by beafialho** [comment]
> I think the best would be to remove the margin setting from the patterns, and then on the full page patterns, where these full width patterns are combined into one cohesive layout, wrap them inside an extra group with block spacing set to 0.

I've done this as well in other themes. Perhaps it's the best workaround.

**Comment by maneshtimilsina** [comment]
I have removed the top and bottom margin 0 of the `Contact Location and Link` pattern. Please check this [PR](https://github.com/WordPress/twentytwentyfive/pull/356)
