### ISSUE TITLE
Using a Common Pattern to Eliminate Repeated Code in Templates

### ISSUE THREAD

**Issue by codersantosh** [WordPress/twentytwentyfive#332]
**Description**
The home, index, and archive templates share a similar code structure. To minimize code duplication, a shared pattern could be created and applied as needed. The archive template includes dynamic header text using the wp:query-title block, and since conditional tags don't seem to work in the editor, this can remain as is. However, the home and index templates appear to be identical, so unless there are plans to change the index template, both could utilize the same common pattern.

**Comment by carolinan** [comment]
I am not opposed of this, but I will close it only because I would consider it an enhancement and there is only a short time left until the theme needs to be released.
