### ISSUE TITLE
Copyright pattern

### ISSUE THREAD

**Issue by codersantosh** [WordPress/twentytwentyfive#337]
**Is your feature request related to a problem? Please describe.**
Currently, the copyright pattern displays the placeholder text `Type / to choose a block` in the editor, which may confuse users.

**Describe the solution you'd like**
Consider adding the placeholder text, for example:

`"placeholder":"<?php esc_attr_e( 'Dynamic copyright text', 'twentytwentyfive' ); ?>",`

Additionally, since copyright is primarily used in the footer section, consider adding the following block types to the pattern header:

`Block Types: core/template-part/footer`

**Comment by carolinan** [comment]
That is not what I am seeing in the editor.

Please make sure that you are testing with Gutenberg active. This is because changes to Gutenberg will be added to WordPress 6.7, which is the minimum WordPress version the theme will support on release.

**Comment by codersantosh** [comment]
@carolinan, Thank you for the reminder to install the [Gutenberg plugin](https://wordpress.org/plugins/gutenberg/). With Gutenberg active the text on the editor is `© YEAR`.  Unless there's a plan for copyright variations, this seems fine. In the variation, the title and description of the `core/paragraph` block could be updated to include the copyright details.

**Comment by jasmussen** [comment]
If any change here is needed, it seems like it should happen in the block itself, and not something Twenty Twenty-Five should override.

**Comment by codersantosh** [comment]
Alright, everything looks great to me. I have one last question.

> Additionally, since copyright is primarily used in the footer section, consider adding the following block types to the pattern header:
> 
> Block Types: core/template-part/footer

**Comment by jasmussen** [comment]
That might be a suggestion for https://github.com/WordPress/twentytwentyfive/issues/385, which considers exactly that.

**Comment by juanfra** [comment]
Copyright is no longer a pattern, the changes have been introduced [here](https://github.com/WordPress/twentytwentyfive/pull/396). I'm closing this one. Thank you all!
