### ISSUE TITLE
Add width, block gap and spacing presets

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#34]
Figma link: https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=77-7931&t=qC1CDiog2u4tpIsg-4

I am interpreting the Figma file as follows:

## Width
contentSize 645px
wideSize 1340px

## Block gap
- Unknown

## Spacing presets
_Note that the slugs must be numeric._

1) One spacing preset that results in 20px (1.25 rem) on small/mobile screens and 50px (3.125 rem) on desktop,
used to set the horizontal distance between the content and the edge of the browser.

2) Besides that, I do not know which of these must be fluid and what their min and max values need to be:

Extra tiny: 5px
Tiny: 10px
Extra small: 20px
Small: 30px
Regular: 50px
Large: 70px
Extra lage: 90px
XXL: 140px

**Comment by juanfra** [comment]
Pinging @beafialho @jasmussen @richtabor for visibility.

**Comment by richtabor** [comment]
Gaps should mostly be min/max values, not hard integers.

**Comment by beafialho** [comment]
Thanks for creating this issue. I confirm those are the widths.

Block gap I am still unsure if this will look as I intend in the editor, but we could try 20px and see how that looks.

Could you clarify what you mean with this? Do they have to be `rem` values?

> _Note that the slugs must be numeric._
> One spacing preset that results in 20px (1.25 rem) on small/mobile screens and 50px (3.125 rem) on desktop,
used to set the horizontal distance between the content and the edge of the browser.

I think only Large, Extra Large and XXLarge need to be fluid. I added min and max values in the Figma library, they can be seen in the right sidebar:

![Captura de ecrã 2024-08-16, às 14 48 37](https://github.com/user-attachments/assets/7d92e3b7-c5ab-4274-b649-b67276c21a46)
![Captura de ecrã 2024-08-16, às 14 48 01](https://github.com/user-attachments/assets/6699c4b5-3823-4e60-ad63-a432fc635b00)

**Comment by carolinan** [comment]
> Do they have to be rem values?

I thought it was best practice to use relative units.

**Comment by joedolson** [comment]
I generally prefer that fonts and vertical spacing is done in relative units, and gaps and horizontal spacing is done in fixed units. This is largely because if a font size is increased by the user, it can become very problematic if the gaps and margins grow in the same way, making text line lengths decrease to a point that they're simply unreadable.

**Comment by richtabor** [comment]
Fix units for spacing is fine, as long as they're using min/max.

**Comment by carolinan** [comment]
>I added min and max values in the Figma library, they can be seen in the right sidebar:

I don't know where in the Figma interface this is or if you are talking about something that is not already shared in this issue.
If I click on the Figma icon in the top left corner and select "Libraries" It only says "Includes two missing libraries" and it doesn't have anything related to spacing in it.

**Comment by carolinan** [comment]
If you already know which min() or clamp() values that are expected, kindly provide those.
Clamp needs a _preferred_ value and only 2 values are mentioned.

**Comment by carolinan** [comment]
One more question 😄 
7 is the max number of options that fits in the stepped control. 8 sizes or more will show as a drop down.
Should one of the sizes be a **custom** variable instead? One that can be used in templates but wont show in the spacing control. If so, which?

**Comment by beafialho** [comment]
Sorry for not being clearer @carolinan. Here's a quick screen recording of where those spacing presets are specified in the Figma file. I also just checked that these are published as a library, so you should be able to see them.


https://github.com/user-attachments/assets/6c2bc891-33ab-4812-977c-039316fd292b
