### ISSUE TITLE
Demo site (links) not working.

### ISSUE THREAD

**Issue by pronode** [WordPress/twentytwentyfive#342]
**Description**
Links in demo site not working.

**Step-by-step reproduction instructions**

1. Go to https://2025.wordpress.net/
2. Click on any link from "sample page" or "pull page patterns" menu.

**Expected behavior**
Links working.

**Screenshots**
Please. They are just not working.

**Environment info**
Google Chrome

**Comment by carolinan** [comment]
The demo site as well as the preview in the theme directory and the documentation will be complete when the theme is released with WordPress 6.7, which is in mid November.

**Comment by beafialho** [comment]
I've been adding content, but like Carolina said, it'll be one of the last things to be ready (mid November).
