### ISSUE TITLE
Default blog, archive and search templates: Featured image and title bump screen's edges

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#345]
On mobile, the featured image and title in the query loop go against the screen's edges.

https://github.com/user-attachments/assets/89767d2e-5290-4a0f-9d4c-280ccf68c0bd

![Captura de ecrã 2024-09-17, às 15 27 53](https://github.com/user-attachments/assets/8a1d28a4-cb38-40ec-a676-80d091746fa6)

**Expected behavior**

![Captura de ecrã 2024-09-17, às 15 24 09](https://github.com/user-attachments/assets/0702e194-8880-49e1-9468-52104a1b467e)

**Comment by dballari** [comment]
Hi, I can take care of this, if no one else is working on it

**Comment by dballari** [comment]
This is kind of interesting, if I go the the editor of my dev environment, not only the image is outside the edges but also the title. But looking at the web from a browser it looks good, in my environment and also in the demo site. I provide image of demo site. 

So it's only in the editor that does not work. I will try to findout why.

![Captura de pantalla 2024-09-18 a las 09 57 56](https://github.com/user-attachments/assets/78153eec-a9b5-43f3-9805-9b1e26256d7f)
