### ISSUE TITLE
Enhancement to reduce widows and orphans in the theme

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#346]
Sometimes text can have single lines of text (widows and orphans) from a paragraph that dangle at either the beginning or end of a block of text, which blocks readability. Unless [this Gutenberg issue](https://github.com/WordPress/twentytwentyfive/issues/25#issuecomment-2315517591) gets implemented, one solution could be adding the code below (or something similar that achieves the same) in `style.css` to prevent that from happening.

![image](https://github.com/user-attachments/assets/29179c15-1367-458e-88b0-e672f553c035)

```
/* Progresive enhancement to reduce widows and orphans.
/* <https://github.com/WordPress/gutenberg/issues/55190>
*/
h1, h2, h3, h4, h5, h6, blockquote, caption, figcaption {
		text-wrap: balance; /* Safari fallback */
		text-wrap: pretty;
}
p {
    text-wrap: pretty;
}

```

**Comment by carolinan** [comment]
The last Gutenberg release with enhancements for 6.7 is hours away, so it won't be implemented for this release.

**Comment by bobmatyas** [comment]
I will work on this one for contributor day 👍
