### ISSUE TITLE
Page templates should default to "Page No Title"

### ISSUE THREAD

**Issue by krismapp** [WordPress/twentytwentyfive#348]
A title is required for the page to show up in the navigation. But as a user who is selecting a template, it does not show the title, so when I publish, and it is there, I become confused. As a user, I may not understand how to change page types to make the title disappear from the page. When I select a template I expect it to look exactly as it was shown when published.

The template options and pages should be set by default to "Page No Title". This way a user can name their page, and see it show up in the navigation. Also when they go searching for their pages, they will be named. Otherwise, a user is tempted to NOT add a title to get around this problem.

**Comment by carolinan** [comment]
I do not understand what you mean. Is this issue specific to this theme?
Perhaps it easier if you include a recording.

Pages without titles show the placeholder title "(No title)" in the navigation **block**. 
I also recently solved this for the [page list](https://github.com/WordPress/gutenberg/pull/64297).

When a user creates a new page or template, they have several choices. I don't think that "page without title" is the most common choice, and there for it should not be the default template.

**Comment by krismapp** [comment]
Sorry.. I know my writing was confusing.. here is a recording :)
I had to make it tiny cuz this will only let me upload 10mb files.
https://github.com/user-attachments/assets/6d939496-651f-4284-a6f6-f1ba97a5687a

**Comment by beafialho** [comment]
> When a user creates a new page or template, they have several choices. I don't think that "page without title" is the most common choice, and there for it should not be the default template.

I agree. "Page no title" should not be the default. The most common choice is to have a page title.

**Comment by juanfra** [comment]
Thanks for opening this issue.

I second Carolina and Bea, I don't think that "Page not title" should be the default.

**Comment by carolinan** [comment]
There is a "Template Types" parameter when registering patterns, but as far as I can tell from my testing, it does not work for this scenario, because when creating a new page, the template is already selected.
