### ISSUE TITLE
Request to add dropdown menu on mobile devices

### ISSUE THREAD

**Issue by phanduynam** [WordPress/twentytwentyfive#367]
I am using WordPress 6.6.2 and the latest Twenty Twenty Four 1.2 theme. I am having trouble creating a menu on mobile. You can see the menu is not collapsing but always pops out of the sub-menu items. I tried searching but Gutenberg does not have an option to collapse the entire menu. It will be a disaster if the site has many sub-category products. Hopefully this issue will be resolved in the Twenty Twenty Five theme.
![image](https://github.com/user-attachments/assets/a6cf41ef-f83e-47ee-8492-c0b2f2105ed7)

**Comment by carolinan** [comment]
@phanduynam The theme can not add features that are not supported by WordPress.
Themes are for presenting content, not add functionality.
If you need a feature that is not available in the editor, you need to use a plugin.
