### ISSUE TITLE
H1 missing in landing page patterns

### ISSUE THREAD

**Issue by ddewan-git** [WordPress/twentytwentyfive#369]
The following landing page patterns currently contain no H1:

- [Landing page for Book](https://github.com/WordPress/twentytwentyfive/blob/trunk/patterns/page-landing-book.php)
- [Landing page for Podcast](https://github.com/WordPress/twentytwentyfive/blob/trunk/patterns/page-landing-podcast.php)

Their hero sections use H2 instead, since that's how the source patterns—[hero-book](https://github.com/WordPress/twentytwentyfive/blob/trunk/patterns/hero-book.php) and [hero-podcast](https://github.com/WordPress/twentytwentyfive/blob/trunk/patterns/hero-podcast.php) respectively—have been designed.

Perhaps it would be ideal if the landing page patterns had custom hero sections with H1. 

This issue is related to #186.

**Comment by juanfra** [comment]
Re-opening this one, as we introduced "[Shop home](https://github.com/WordPress/twentytwentyfive/pull/434)" and it's missing an H1

**Comment by carolinan** [comment]
I am going to close this because there are multiple issues open regarding the H1 headings.
