### ISSUE TITLE
Add headers

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#37]
Figma link:
https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3056-195&t=qClGa6ofM1L6v4bG-4

I would recommend starting with two template parts: One for the horizontal header and one for the sidebar.
Each header can then be separate patterns, with the default headers placed in the respective template part.

- [x] Header (Main): Site title and navigation
- [x] Header: Site title and hamburger menu
- [x] Header: Columns with site title, tagline and vertical nav
- [x] Header: Big type

Sidebars
- [x] Header as sidebar 
- [ ] Header as sidebar with navigation

**Comment by carolinan** [comment]
> Header: Site title and hamburger menu

Core already provides a header pattern called "centered header with logo", Should we use that instead?
https://wordpress.org/patterns/pattern/centered-header-with-logo/
Its markup uses spacing preset 30, 40, and the link color with the slug "contrast"

```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","right":"var:preset|spacing|30","bottom":"var:preset|spacing|40","left":"var:preset|spacing|30"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--30)"><!-- wp:group {"align":"wide","layout":{"type":"flex","justifyContent":"center","orientation":"vertical"}} -->
<div class="wp-block-group alignwide"><!-- wp:site-logo /-->

<!-- wp:site-title {"style":{"elements":{"link":{"color":{"text":"var:preset|color|contrast"}}}},"textColor":"contrast","fontSize":"large"} /-->

<!-- wp:navigation {"layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"center"}} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

```

**Comment by juanfra** [comment]
A PR with the four headers that are not "sidebar" has been merged [here](https://github.com/WordPress/twentytwentyfive/pull/52).

**Comment by carolinan** [comment]
For now, the plan is to not include Header as sidebar with navigation, so I am closing this as complete.
