### ISSUE TITLE
The "Quote Block" border issue.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfive#370]
**Description**
I have reviewed the "Quote" block and found that it's right border is not displaying when we set its border from the block settings.

**Step-by-step reproduction instructions**

- Go to admin and select the "Quote" block first.
- Add its paragraph text & citation text.
- Now, set border to 1 or 2 px
- Update the page and check its admin text and front-end text.

**Expected behavior**
I think that if user add border to "Block" then it should be add border to entire block.

**Screenshots**

Here, I have provided its screenshots:

**Editor-end:**
![quote-block-editor](https://github.com/user-attachments/assets/6da573bc-eeab-4008-84cd-1b10fd925557)

**Front-end:**
![quote-block-front-end](https://github.com/user-attachments/assets/2c074ded-2c8e-4b56-bf11-07847ebfa65e)

**Environment info**

- Device: Macbook M1
- OS: 15.0 (24A335)
- Browser: Google Chrome
- Version 128.0.6613.138 (Official Build) (arm64)
- WordPress version: 6.6.2 running, Gutenberg 19.2.0 , Theme active: Twenty Twenty-Five,

**Additional context**
I have tested this issue with active and inactive Gutenberg plugin and I am getting this issue.

Thanks,

**Comment by ddewan-git** [comment]
### Additional Information

The issue persists with the right-aligned and center-aligned Quote block as well.

### Screenshots

**Right-aligned Quote Block - Editor-end**

![Block Quote Default – Right Aligned – 2px Custom Border Added - Editor-end](https://github.com/user-attachments/assets/68f66f50-53e2-41f5-a02c-51dae8b6b2e2)

**Right-aligned Quote Block - Front-end**

![Block Quote Default – Right Aligned – 2px Custom Border Added - Front-end](https://github.com/user-attachments/assets/dc34a8f5-84e5-4c28-91b5-ae9da66b241b)

**Center-aligned Quote Block - Editor-end**

![Block Quote Default – Center Aligned – 2px Custom Border Added - Editor-end](https://github.com/user-attachments/assets/4cfafd71-1311-4d0c-af5b-4308eefb2ba6)

**Center-aligned Quote Block - Front-end**

![Block Quote Default – Center Aligned – 2px Custom Border Added - Front-end](https://github.com/user-attachments/assets/90c187b9-8f7c-4343-a3ab-0a405bb343e2)

**Comment by ddewan-git** [comment]
### Follow-up

In case anyone wants to work on this issue, the approach that worked for me is applying the following change to the Quote block style (please note that unmodified properties are truncated here for readability):

```
...

"core/quote": {
	"border": {
		"style": "solid",
		"width": "0 0 0 2px",
		"color": "var:preset|color|contrast"
	},
	"spacing": { ...
	},
	"typography": { ...
	},
	"elements": { ...
	},
	"css": "&.has-text-align-right { border-width: 0 2px 0 0; } &.has-text-align-center { border-width: 0; }",
	"variations": { ...
	}
},

...
```
#### Limitation of this approach

The end result preserves the spacing presets and does not remove padding based on the alignment. So it slightly deviates from the [current design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3155-1729).

#### Testing instructions for the approach

**Updating theme.json**
- Change the border-width to "0 0 0 2px" in styles/blocks/core/quote.
- Replace the custom CSS with "&.has-text-align-right { border-width: 0 2px 0 0; } &.has-text-align-center { border-width: 0; }".
- Save theme.json.

**Using the Quote block - Default - No Custom Border Added**
- Add a Quote block to any post/page.
- Publish/update the post/page and check the default left alignment.
- Change the alignment to Center.
- Update the post/page and and check the alignment on both the Editor-end and front-end.
- Change the alignment to Right.
- Update the post/page and and check the alignment on both the Editor-end and front-end.

**Using the Quote block - Default - 2px Custom Border Added**
- Add a Quote block to any post/page.
- Set Border to 2px without changing the left/default alignment.
- Update the post/page and check the borders on both the Editor-end and front-end.
- Change the alignment to Center.
- Update the post/page and and check the alignment (and borders) on both the Editor-end and front-end.
- Change the alignment to Right.
- Update the post/page and and check the alignment (and borders) on both the Editor-end and front-end.

#### Screenshots after following this approach

**Quote Block - Default - Left/Default Alignment - No Custom Border Added - Editor-end**
![Block Quote Default – Left Aligned – No Custom Border - Editor-end](https://github.com/user-attachments/assets/89ce8104-bc8c-4829-80cc-ad1ffe90e9e5)

**Quote Block - Default - Left/Default Alignment - No Custom Border Added - Front-end**
![Block Quote Default – Left Aligned – No Custom Border - Front-end](https://github.com/user-attachments/assets/87e3d63c-ab52-4847-9cca-424724694277)

**Quote Block - Default - Left/Default Alignment - 2px Custom Border Added - Editor-end**
![Block Quote Default – Left Aligned – 2px Custom Border - Editor-end](https://github.com/user-attachments/assets/ee12c968-1ee3-4f5e-ac8a-b2281fec0784)

**Quote Block - Default - Left/Default Alignment - 2px Custom Border Added - Front-end**
![Block Quote Default – Left Aligned – 2px Custom Border - Front-end](https://github.com/user-attachments/assets/0134ea9f-7051-4601-8a64-d8518b366ab6)

**Quote Block - Default - Center Alignment - No Custom Border Added - Editor-end**
![Block Quote Default – Center Aligned – No Custom Border - Editor-end](https://github.com/user-attachments/assets/84fde36e-04e6-4ebc-b09b-44effec95fc1)

**Quote Block - Default - Center Alignment - No Custom Border Added - Front-end**
![Block Quote Default – Center Aligned – No Custom Border - Front-end](https://github.com/user-attachments/assets/d38b25fe-7f59-4a0b-bbdc-05fdd7b1e9c6)

**Quote Block - Default - Center Alignment - 2px Custom Border Added - Editor-end**
![Block Quote Default – Center Aligned – 2px Custom Border - Editor-end](https://github.com/user-attachments/assets/e907d61f-9160-4a0b-a90e-7f4b78532d59)

**Quote Block - Default - Center Alignment - 2px Custom Border Added - Front-end**
![Block Quote Default – Center Aligned – 2px Custom Border - Front-end](https://github.com/user-attachments/assets/e93c1c4b-c9bb-451d-8dc6-8977a400567d)

**Quote Block - Default - Right Alignment - No Custom Border Added - Editor-end**
![Block Quote Default – Right Aligned – No Custom Border - Editor-end](https://github.com/user-attachments/assets/d97176e5-905d-4910-9f8b-7a06b8dbe0c6)

**Quote Block - Default - Right Alignment - No Custom Border Added - Front-end**
![Block Quote Default – Right Aligned – No Custom Border - Front-end](https://github.com/user-attachments/assets/f63da84d-218a-44ff-bdf5-266ca9cfc5d5)

**Quote Block - Default - Right Alignment - 2px Custom Border Added - Editor-end**
![Block Quote Default – Right Aligned – 2px Custom Border - Editor-end](https://github.com/user-attachments/assets/043127ef-3d1c-4e8a-a5ad-a5b3cbf5baa8)

**Quote Block - Default - Right Alignment - 2px Custom Border Added - Front-end**
![Block Quote Default – Right Aligned – 2px Custom Border - Front-end](https://github.com/user-attachments/assets/5b79711e-83d3-4a77-8861-c7dc8276de9a)

**Comment by jasmussen** [comment]
I can reproduce, though I can't quite figure out why this is happening, whether it's a bug in Twenty Twenty-Five or in the gutenberg project itself. I lean towards this being a Twenty Twenty-Five issue since I tried re-creating this issue in Twenty Twenty-Four, and could not. 

It seems related to the border definition in theme.json. Relatedly, I noticed that the change to using shorthand, [here](https://github.com/WordPress/twentytwentyfive/commit/98ddcae3233eb853048b6f7dd918d173b26dcb24#commitcomment-147124882), caused the global styles interface to be less intuitive, so it may be worth auditing similar instances of using shorthand, and make sure that the theme.json values always are stored in a format that the block editor is able to map to a design tool.

**Comment by ddewan-git** [comment]
> I lean towards this being a Twenty Twenty-Five issue since I tried re-creating this issue in Twenty Twenty-Four, and could not.

@jasmussen It does seem to be a Twenty Twenty-Five issue. As far as I've experimented, the custom CSS is causing it. For context, the Twenty Twenty-Three theme's Quote block has a similar design, but the style can be easily modified via the Site/Block Editor.

Agreed on the use of shorthand.

**Comment by jasmussen** [comment]
I only took a superficial look at it, so I may be missing something obvious. But what custom CSS are you referring to? Agreed if we can use global styles, solely, to style the quote block, that's ideal.

**Comment by ddewan-git** [comment]
This is the custom CSS that I was referring to:

```
...

	"core/quote": {
		"border": { ...
		},
		"spacing": { ...
		},
		"typography": { ...
		},
		"elements": { ...
		},
		"css": "&.has-text-align-right { border-left: 0; padding-left: 0; } &.has-text-align-center { border-inline: 0; padding-inline: 0; } &:not(.has-text-align-right):not(.has-text-align-center) { border-right: 0; padding-right: 0; }",
		"variations": { ...
		}
	},
...
```
