### ISSUE TITLE
Showcasing the different blog alternatives with Playground

### ISSUE THREAD

**Issue by dballari** [WordPress/twentytwentyfive#375]
Hi, I keep on wondering how we are going to showcase the different blog alternative designs.

In the demo site (https://2025.wordpress.net/) I see some blog templates menu options. Will these be links to a different WordPress sites? In my opinion there should be as many blogs as blog alternatives we want to showcase.

As @carolinan explained me, templates may be customized from the Template – Design settings section, where the different alternative designs may be chosen. But these customizations are saved in the database, not in the theme folder, that’s why we need several blogs.

![Screenshot from 2024-09-20 09-53-41](https://github.com/user-attachments/assets/c0a9cac5-adf8-42e6-8569-e823b777265f)

I would suggest to make a Playground demo for each blog: the personal, the news blog and the photo blog. It could be done in a Github repo where the different playground configurations and demo content could be stored. We could make really short video tutorials on how to customize templates and people would just have to click on the desired Playground demo link to see them in action.

Apart from this, the Playground demo could be used to showcase other things that need customizations like, for instance, synced patterns with overrides.

If you guys think is a good idea, I volunteer to help there. I have already done a Playground demo for my theme and it works great. I think I migrated the links of the xml demo content and did not have images to import.

In the case of TT5 there are a lot of images. I think in this case It would be good to keep the images in the xml demo content files pointing to the original demo site so that the Playground demo loads faster.

What do you think?

**Comment by carolinan** [comment]
I believe this is solved for the demo, by using different sites and linking to them.
But I am not sure how to set up **persisting** playground examples.

**Comment by dballari** [comment]
Hi @carolinan , sorry I have not been available for several weeks. I have just seen you mentioned this issue in slack. It's duable, but not necessary so, please, feel free to close it if you want. It was just and idea. The 3 demo sites look great. I just visited them.

To do it with playground, a xml export file of each demo needs to be exported and uploaded, for instance, in a publicly accessible Github repo. Then there is a trick that I think was explained by Nick Diego in a video, which consisted in changing the url of the files, in the playground.json file.

It looks something like this:

```
{
            "step": "importWxr",
            "file": {
                "resource": "url",
                "url": "https://raw.githubusercontent.com/.......demo-content.xml"
            }
        }
```

And that's it. I have done it for a theme of mine and have it in my github account. It works.

In the TT5 case, the demo has a lot of images and we need to tell the export tool not to upload images to speed up. And here I have doubts. Do not know how to do it or if it's possible at all. But the solution would be not to export the images in the xml file. The posts containing the images would go to the original image url and I think it would work.



But, again, feel free to close the issue if you want. I'm sure there are more important things to do.

**Comment by dballari** [comment]
I see it looks like this has already been done by either Rich or Nick. Here is the link https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa1BhLXFoV2ZabGhMR2kwQXdjVzFNRDRZLV9iQXxBQ3Jtc0ttUzV4X01rRzlCQnZEVDIwR0VnVGJMR1BEZ1RsYjhvWTVxalNYQWFrZ25CVTl3anBTeGQ2Qm9qcTI2cmk1U3BxdFBib25ZWVdaVk9IZ3FLSUVDMXRRYTc0anYwMWJEYm9qUUgzdngzejZxQUd0b2NjWQ&q=https%3A%2F%2Fplayground.wordpress.net%2F%3Fblueprint-url%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2Fwordpress%2Fblueprints%2Ftrunk%2Fblueprints%2Ftt5-demo%2Fblueprint.json&v=K6N098ElnYU

It's found here https://www.youtube.com/watch?v=K6N098ElnYU

So I guess no need for this ticket anymore

**Comment by juanfra** [comment]
Thanks for the heads' up @dballari 

I'm assuming this is the link you are referring to https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fraw.githubusercontent.com%2Fwordpress%2Fblueprints%2Ftrunk%2Fblueprints%2Ftt5-demo%2Fblueprint.json

I'm closing this issue.
