### ISSUE TITLE
Discussion: Replace hardcoded `Twenty Twenty-Five` in footers.

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#385]
**Description**

This is a follow-up of https://github.com/WordPress/twentytwentyfive/pull/372#issuecomment-2367817972.

We currently have three footers using `Twenty Twenty-Five` as a string, using the paragraph block. We're not using the site title or anything dynamic. As a result, any user who won't like having the theme name in the footer, will have to manually and purposefully edit the footer to change it.

- [patterns/footer.php](https://github.com/WordPress/twentytwentyfive/blob/trunk/patterns/footer.php#L75)
- [patterns/footer-columns.php](https://github.com/WordPress/twentytwentyfive/blob/trunk/patterns/footer.php#L75)
- [patterns/footer-newsletter.php](https://github.com/WordPress/twentytwentyfive/blob/trunk/patterns/footer-newsletter.php#L45)

Having the site title where we now have `Twenty Twenty-Five` can be redundant in some of these footers (default and columns), as it's already being used. 

A good candidate to fill this space could be the [copyright pattern](https://github.com/WordPress/twentytwentyfive/blob/trunk/patterns/copyright.php) we're introducing with the block binding that will print `© YEAR`.

<img width="1432" alt="Screenshot 2024-09-23 at 15 32 55" src="https://github.com/user-attachments/assets/1f1dcfb0-c65a-4d16-91bd-cdb1dd0b113d">

In the screenshot, `Stories®` is the site title, and `The new WordPress default theme pays homage to history and ancestry.` the tagline.

**Comment by jasmussen** [comment]
Copyright might work. Or something else, the key is to not duplicate the site title again.

**Comment by carolinan** [comment]
I think that if the content was just removed, it would look imbalanced, so lets test the copyright.
In worst case if we find it doesn't look and feel good and we can try something else.
