### ISSUE TITLE
Footer Template: Site title wrapping

### ISSUE THREAD

**Issue by t-hamano** [WordPress/twentytwentyfive#389]
**Description**

The site title in the footer template may wrap unnaturally.

![image](https://github.com/user-attachments/assets/6897e754-e7d7-4a7b-979c-20420767c110)

**Step-by-step reproduction instructions**

Change your site title. Results will vary depending on the length of the text, but the short site title will likely highlight this issue.

**Expected behavior**

There is enough space to the right of the site title that I would expect the text to not wrap:

![image](https://github.com/user-attachments/assets/0a9952f4-241f-4a5c-9ce5-9a70445fd012)

**Environment info**

**Comment by YukinobuAsakawa** [comment]
Hello.
I was interested, so I tried it out using the link below: Preview changes for twentytwentyfive.
It seems that the problem has been resolved.

https://github.com/WordPress/twentytwentyfive/pull/392#issuecomment-2371224685
