### ISSUE TITLE
Add 404 template

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#39]
Figma Link:

https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3142-998&t=qClGa6ofM1L6v4bG-4

- Use the default header and footer template parts
- Create the content as a pattern since the text needs to be translation ready.
   - The pattern should have "Inserter" set to "no" in the pattern file header
  - The name of the file should be hidden-404.php and should match the slug: twentytwentyfive/hidden-404.php

**Comment by up1512001** [comment]
Hi @carolinan, can I work on this `404` pattern?

**Comment by carolinan** [comment]
Yes, no need to ask.

**Comment by carolinan** [comment]
Someone else already started working on it, perhaps you can collaborate and help with the review.

**Comment by carolinan** [comment]
This template has been added, thanks everyone.
