### ISSUE TITLE
Use standard page category slug for pages

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#398]
Why use a bespoke category for TT5's pages? TT4 just used `page` — [source](https://github.com/WordPress/twentytwentyfour/blob/trunk/functions.php#L197). Seems like unnecessary complexity that also puts TT5 at risk if core does more for page categories in the future. 

![CleanShot 2024-09-24 at 16 25 35](https://github.com/user-attachments/assets/a7d07b42-b818-45cd-9e4d-8875de9cdc53)

**Comment by carolinan** [comment]
Page is not an existing [block pattern category](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-patterns.php).

If you look at WordPress trunk instead, TT4 does not use `page` anymore:  https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwentyfour/functions.php#L194

Here is the [Trac ticket](https://core.trac.wordpress.org/ticket/59839).

**Comment by richtabor** [comment]
Why did that change? There's no reason to be unique? Does it matter if the label is changed by a plugin to "Pages" or else? Seems an over-optizimation. 

It just makes things more complicated for future iteration on "page" patterns, as they're not categorized consistently. :/ 

If core adds a page category, these themes will be left out of the loop.

**Comment by carolinan** [comment]
If core adds a page category, TT5 and the older bundled themes will not be able to support it fully, because they have a minimum required WordPress version which matches the version the theme was first released with.

**Comment by carolinan** [comment]
Is there an open Gutenberg issue or core ticket to add the page category and what would updating the themes involve?

**Comment by richtabor** [comment]
> If core adds a page category, TT5 and the older bundled themes will not be able to support it fully, because they have a minimum required WordPress version which matches the version the theme was first released with.

It's unfortunate. I'd expect that any theme that supports patterns should be able to. Just like how "My Patterns" was added.

**Comment by carolinan** [comment]
I will take it upon myself to follow up if there are changes to core, as part of my role as one of the bundled theme component maintainers.
