### ISSUE TITLE
Copyright "pattern" should not be a pattern

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#399]
Let's be a bit more opinionated on what constitutes a pattern. A copyright text is not an ideal component for building out pages with—we should remove it as a standalone pattern and instead use it within patterns/templates that make sense. 

![CleanShot 2024-09-24 at 16 39 12](https://github.com/user-attachments/assets/42942ec9-ddfb-4cd4-84d3-a04525be90f4)
![CleanShot 2024-09-24 at 16 39 15](https://github.com/user-attachments/assets/8b624622-77d4-4056-9d0e-4f1a100f32df)

**Comment by carolinan** [comment]
We can hide it from the inserter. But there is no reason to repeat the code in each use case, using the pattern is not a performance issue.

**Comment by richtabor** [comment]
> We can hide it from the inserter. But there is no reason to repeat the code in each use case, using the pattern is not a performance issue.

It's more or less the same complexity as any other block with a few attributes; not worth abstracting as a standalone pattern, making it more difficult to trace for curious eyes.
