### ISSUE TITLE
Add templates for Personal Blog

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#40]
Figma File:
https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3155-1264&t=qClGa6ofM1L6v4bG-4

The index/home, archive, and search templates use the same design for the list of posts,
so one pattern can be created and re-used in all these templates.

All templates except page has a section called "Other posts". This should be a pattern, created separately from the templates, basically to avoid multiple people working on the same part at the same time (speaking from past experience =D ) 

- [x]  Index (possibly Home?)
- [x] Single
- [x] Archive
- [x] Search
- [x] Page

**Comment by beafialho** [comment]
I can work on these.

**Comment by carolinan** [comment]
These are already in the theme...

**Comment by beafialho** [comment]
I just confirmed that as I looked, the tasks were unselected...

**Comment by carolinan** [comment]
I expect them to be edited after the design review. 

A solution is needed for the "other posts", as per the discussion on Figma, there is no way to exclude the current post in the query loop.

**Comment by beafialho** [comment]
I have created an issue to discuss a solution: https://github.com/WordPress/twentytwentyfive/issues/134

**Comment by carolinan** [comment]
I removed the pattern from the checklist above.
