### ISSUE TITLE
Reduce zip file size

### ISSUE THREAD

**Issue by t-hamano** [WordPress/twentytwentyfive#401]
When I removed the files necessary for development from this repository and converted it to a zip file, I found that the file size in my environment was 14.711 MB.

The theme directory does not mention any [requirements](https://make.wordpress.org/themes/handbook/review/required/) regarding file size, but the maximum size of a zip file that can actually be uploaded to the theme directory is 10 MB:

https://wordpress.org/themes/upload/

![upload](https://github.com/user-attachments/assets/f8c4d777-cf13-4443-8f8c-7d86053e69a2)

Although there is a file size limit for the theme directory, it seems strange that the default theme exceeds that size.

One approach to reducing the size might be to convert to the AVIF image format proposed in #383.

The `/assets/fonts` directory (about 8 MB) and `/assets/images` directory (about 6 MB) take up most of the overall size.

Incidentally, the file sizes when downloading [the wordpress-develop theme directory](https://github.com/WordPress/wordpress-develop/tree/trunk/src/wp-content/themes) and converting each theme to zip are as follows:

| Theme Name          | Zip File Size |
| ------------------- | ------------- |
| Twenty Twenty-Four  | 2.896MB       |
| Twenty Twenty-Three | 2.160MB       |
| Twenty Twenty-Two   | 5.818MB       |
| Twenty Twenty-One   | 2.783MB       |
| Twenty Twenty       | 1.005MB       |
| Twenty Nineteen     | 0.620MB       |
| Twenty Seventeen    | 2.115MB       |
| Twenty Sixteen      | 1.807MB       |
| Twenty Fifteen      | 4.230MB       |
| Twenty Fourteen     | 2.173MB       |
| Twenty Thirteen     | 1.764MB       |
| Twenty Twelve       | 1.192MB       |
| Twenty Eleven       | 1.238MB       |
| Twenty Ten          | 1.097MB       |

**Comment by carolinan** [comment]
I am not opposed to the using AVIF, core also has a script for reducing the image sizes that will be ran before commit.
I believe the font families are set though as part of the design and style variations.

**Comment by t-hamano** [comment]
Now that this theme has shipped into core, I zipped [this directory](https://github.com/WordPress/wordpress-develop/tree/ff3bb8d6d08f4e3fa75c56d53a4843662b0014d7/src/wp-content/themes/twentytwentyfive) and measured its size, finding it to be **11.4MB**.

**Comment by carolinan** [comment]
I reduced some of the image size https://github.com/WordPress/twentytwentyfive/pull/475/files but I was in a hurry.

**Comment by carolinan** [comment]
@juanfra @beafialho This issue needs more attention.
Can the number of images, image duplicates, and image sizes be reduced further please?

**Comment by beafialho** [comment]
Taking a look at the heavier images, I think their size can be reduced they don't need to be as big.

We can remove this image from the theme `image-from-rawpixel-id-8803077-original.webp` and replace it with `image-from-rawpixel-id-8802835-jpeg-scaled.webp` in this pattern:

![Image](https://github.com/user-attachments/assets/e93b8e2f-5fe8-4ed0-afcd-8a4286d73c05)

We can replace `location.webp` with a cropped version export from the [Figma comp](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1815&t=hF3HJeTuwkQyKLmx-4).

**Comment by beafialho** [comment]
We could also remove this image:

![Image](https://github.com/user-attachments/assets/6fdf53ac-76be-4158-b48a-6d4051c4a6d8)

And replace it in the pattern with the one below:

![Image](https://github.com/user-attachments/assets/bcf5218b-c112-4d8e-a79a-06eadc3856a2)

![Image](https://github.com/user-attachments/assets/3284282f-863b-479f-9148-bb5cf92a3101)

**Comment by juanfra** [comment]
We recently merged some changes to improve this, but apparently, we still need to continue reviewing and seeing how we can reduce the zip size. From what I tested with the files in beta 3, the zip size is over **12MB**.
