### ISSUE TITLE
Clean up posts patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#411]
Many of the posts patterns display quite poorly. What can we do to clean these up?

![CleanShot 2024-09-25 at 15 00 08](https://github.com/user-attachments/assets/f4c8d251-33f5-4f9e-a2c2-a4cc8cafaba4)
![CleanShot 2024-09-25 at 14 59 55](https://github.com/user-attachments/assets/741e037c-7f1a-489e-9776-0ea41e15c468)

**Comment by carolinan** [comment]
The patterns from the .org pattern directory can be disabled, but I do not think there is a way to only disable a few of them.

**Comment by carolinan** [comment]
Which patterns are these? I only see two that are part of the theme?

**Comment by carolinan** [comment]
I suggest that this pattern, the query for the design with the right aligned posts, can be hidden. It is a simple query, and it may be confusing that it is called "right-aligned" when the posts are not right-aligned outside of its template.

![posts-right-aligned](https://github.com/user-attachments/assets/f046626f-170a-4c6a-8eaa-9264be6a90d9)

**Comment by richtabor** [comment]
They're all present: 

Portfolio Homepage
Photo blog posts
List of posts, 1 column
...

![CleanShot 2024-09-26 at 11 57 18](https://github.com/user-attachments/assets/21be18c0-5142-469c-b42f-d95166e25658)

**Comment by carolinan** [comment]
Maybe hide all except for "more posts" ?

**Comment by carolinan** [comment]
@beafialho @juanfra This issue needs more attention.

**Comment by juanfra** [comment]
I believe we can do the following:

- Remove "Business homepage" from that list.
- Remove "Shop homepage" from that list.
- Improve the way the "Photo blog posts" is displayed there.

The first two do not list posts, so having them there doesn't make sense.

 https://github.com/user-attachments/assets/4262edc5-2b22-4372-8d62-1c08c872bb5c

**Comment by juanfra** [comment]
I just merged [this PR](https://github.com/WordPress/twentytwentyfive/pull/532). If we're good with this solution we should be good to close this issue.

@richtabor when you have time can you please check and see if there's anything else that you wanted to clean up here? Thanks 🙌

**Comment by juanfra** [comment]
I'm closing this one as resolved via https://github.com/WordPress/twentytwentyfive/pull/532

Please feel free to re-open if you believe there's something else we should address.
