### ISSUE TITLE
Remove custom focus style

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#412]
If this is necessary it should be done from the core perspective: 

```
/* Focus styles */
:where(.wp-site-blocks *:focus) {
	outline-width: 2px;
	outline-style: solid;
}
```

**Comment by carolinan** [comment]
This has been discussed among contributors since January and as separate issue in this repository.
https://github.com/WordPress/twentytwentyfive/issues/6

**Comment by richtabor** [comment]
So it's ok to add a focus style to every block? How do we know this doesn't conflict with _any_ block? Why isn't this pushed into core? 

These questions remain.

**Comment by richtabor** [comment]
This suggests it is needed for relevant elements, not every block. https://github.com/WordPress/twentytwentyfive/issues/6#issuecomment-2259484213

**Comment by richtabor** [comment]
My goal is to prevent and reduce conflicts (like was introduced with Twenty Twenty-Four).
