### ISSUE TITLE
Remove custom outline button styles

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#413]
We should use theme.json to style variations instead. Otherwise it complicates how styles are accounted for. 

```
.wp-block-button.is-style-outline
	> .wp-block-button__link:not(.has-text-color, .has-background):hover {
	background-color: var(--wp--preset--color--contrast, transparent);
	color: var(--wp--preset--color--base);
	border-color: var(--wp--preset--color--contrast, currentColor);
}

```

**Comment by carolinan** [comment]
Yes this is in progress.

**Comment by carolinan** [comment]
I think this is part of https://github.com/WordPress/twentytwentyfive/pull/414. / #407

**Comment by richtabor** [comment]
I'm questioning if this is necessary to include as a separate stylesheet here. If we're ok accepting the complexity with this.
