### ISSUE TITLE
Inconsistencies between parent, color and type style variations

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#423]
Now that we've been tightening up type (https://github.com/WordPress/twentytwentyfive/pull/422) and colors (https://github.com/WordPress/twentytwentyfive/issues/415) there are many inconsistencies between the color and typography variations, alongside the full style variations. 

I propose we tighten up the color and typography variations individually (removing any values that don't need overriding, fixed typography values—they should use presets like any other style variation—etc), then compose a few for the full style variations. 

Each style variation should be a combination of typography presets and color presets. Otherwise it's very difficult to keep a high bar for these. If we can't do that, then we should only move forward with individual typography and color variations.

**Comment by richtabor** [comment]
### Typography 

Noted that the typography style variations are quite different from the typography values in the full style variations. The same applies for any type style in a full style variation. Those should be available in the typography variations. 

If font sizes change, then the font size presets should be included in the typography variation (just like how color palettes are included in color variations).

**Comment by richtabor** [comment]
If section styles are adapted, like they are in some theme style variations, those same color declarations should be made in the /styles/colors/* style variations. 

If colors are applied to specific blocks, then those should also exist in these color variations.

**Comment by richtabor** [comment]
It may be best to start just with the individual typography and color variations.

**Comment by carolinan** [comment]
The final variation is merged so this work can continue 👍

**Comment by richtabor** [comment]
> The final variation is merged so this work can continue 👍

What do you mean?

**Comment by richtabor** [comment]
For instance, if a full theme style variation is defining a different set of values for section styles, those should be in the color variations as well. As-is, it's going to be very challenging fixings things with so many variables. 

![CleanShot 2024-09-26 at 11 51 12](https://github.com/user-attachments/assets/b6b1445d-2f8c-4cb6-988b-d94b0f191f78)

**Comment by carolinan** [comment]
> > The final variation is merged so this work can continue 👍
> 
> What do you mean?

When this issue was created, all full / combined / theme style variations were not in trunk. Now they are.

**Comment by carolinan** [comment]
The inconsistencies should all be solved (according to the diffs between the files).
There may still be some work left regarding removing duplicate styles, especially as there may be need to be some changes for the search block across all variations.
