### ISSUE TITLE
Posts on the default home template are displayed at content width instead of wide width

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#428]
**Description**

@jasmussen Commented on a pull request that full width patterns no longer seemed to display correctly.
I wrongly dismissed this, because I was unsure of which of the templates that were active during testing.
I am running into the same or similar issue.

**Step-by-step reproduction instructions**
I added the CTA: Grid layout with products and link pattern to a single post:
<img width="1511" alt="cta-product" src="https://github.com/user-attachments/assets/f574f11c-a431-4095-9718-5f110b287dd2">

And on the default home template, the post looks like this:
![home-width](https://github.com/user-attachments/assets/cb3cc94d-c6e1-4e37-8c42-a3f7ff70f346)

In this test, I am using a small screen with a resolution of 1512x982.

**Expected behavior**
I am expecting the result to be more similar to this:
![home-expected-width](https://github.com/user-attachments/assets/285cdf37-b982-4db2-b6f8-97b3b55f4c76)

Next, I created a post with default, wide and full width group blocks to hopefully illustrate the problem better.
As a user, I would prefer to have more variation of widths on the home.
![width-test](https://github.com/user-attachments/assets/69d7f778-92fc-48a0-b029-4d3b92c4ccd5)

**Comment by carolinan** [comment]
Same on the default archive:
![category_uncategorized_](https://github.com/user-attachments/assets/7fbb9d1a-0c9d-4cc6-b3fa-67f86200ece4)

**Comment by carolinan** [comment]
I think I also broke the news blog when adding the `<main>`.

**Comment by jasmussen** [comment]
Thanks for the clear steps, I wasn't quite sure how to articulate this, but it felt off. I would expect that the _container_ when set to "Inner blocks use content width", then the content widths, including wide and full, still work.
