### ISSUE TITLE
Midnight: Can we utilize section style 3 better?

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#448]
**Is your feature request related to a problem? Please describe.**
In midnight, `base` and `accent-1` has the same color, `#4433A6`.

Section style 3 has the same background color and text color as the body:
![image](https://github.com/user-attachments/assets/18487230-8618-4d0c-98f6-f14cfd5411ba)

Can we update `accent-1` for more variety?

**Comment by carolinan** [comment]
Perhaps with a white background?

**Comment by beafialho** [comment]
Yes, we could add a lighter shade of the purple tone, so it could look as the following:

This would only replace the Accent 1 color with `#5644BC`. Looks like it passes contrast checks in my accessibility checker.

![Image](https://github.com/user-attachments/assets/939bcd60-e98f-4bd2-924b-60831240986f)
