### ISSUE TITLE
Tags overlap when extending to two lines

### ISSUE THREAD

**Issue by unscripted** [WordPress/twentytwentyfive#465]
**Description**
When the number of tags extend to two lines or more, the pills overlap with the row above/below.

**Step-by-step reproduction instructions**

1. Go to https://2025.wordpress.net/2024/09/06/vash-gon-jicarilla-by-edward-s-curtis/ on a mobile device. 
2. Scroll down to the tags section. 
3. See error

**Expected behavior**
The x and y spacing should be the same. 

**Screenshots**

![image](https://github.com/user-attachments/assets/79cab302-5cb6-40cc-926e-d04b7ed7648a)

**Environment info**

 - Device: iPhone 16 Pro
 - OS: iOS 18
 - Browser: Safari
 - Version:

**Comment by kartikmehta8** [comment]
Hey @unscripted! I would love to work on this issue.
