### ISSUE TITLE
Multi-word tags break to multiple lines

### ISSUE THREAD

**Issue by unscripted** [WordPress/twentytwentyfive#466]
**Description**

When the tags extend to multiple lines, there is a possibility that the tag at the end of the first row is split between two lines if it is a multi-word tag.

Because the tag is styled like a pill, it appears broken. 

**Step-by-step reproduction instructions**

1. Go to https://2025.wordpress.net/2024/09/06/vash-gon-jicarilla-by-edward-s-curtis/ on a mobile device. 
3. Scroll down to the tags. 

**Expected behavior**

If the tag is styled as a pill, the pill should remain connected. 

**Screenshots**

![image](https://github.com/user-attachments/assets/05133fe2-c4a8-4f43-829b-af293d731d32)

**Environment info**

 - Device: iPhone 16 Pro
 - OS: iOS 18
 - Browser: Safari

**Comment by kartikmehta8** [comment]
Hi @unscripted! I would love to work on this issue.
