### ISSUE TITLE
The instagram pattern is broken in the Site Editor inside the post content block

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#469]
**Description**

Do we know why it looks like the grid CSS is missing in the post content block?

**Step-by-step reproduction instructions**
Create a new post. Add the Instagram grid pattern. Save.
Open the Blog Home template in the Site Editor.
The first post in the query, shown with the post content block, should be the post you just created.
Confirm if the Instagram Grid pattern looks correct.

**Screenshots**

https://github.com/user-attachments/assets/f7b23cc4-6be4-4e98-8d10-f83fe31aae63

**Comment by juanfra** [comment]
I was able to reproduce.

https://github.com/user-attachments/assets/7b7efacc-3bf4-46c9-96cb-7fe8fb47ecf2

**Comment by beafialho** [comment]
The "Instagram @ example" square should be yellow according to the original designs, not black as I'm seeing now.

**Comment by carolinan** [comment]
@beafialho I understand this was the desired design, but those color combinations were not accessible in all style variations, which they must be, see https://github.com/WordPress/twentytwentyfive/issues/468

**Comment by carolinan** [comment]
This issue is about the styles not showing in the post content block.

**Comment by sudip-md** [comment]
@carolinan The "Instagram @ example" square should be yellow according to the original designs - True, it is part of style. It is changed based on style.
![Image](https://github.com/user-attachments/assets/a9450157-6454-492d-adf2-2cda2ac30e76)

**Comment by sudip-md** [comment]
### Test Report

Original Issue has been fixed. Now The instagram pattern is not broken in the Site Editor inside the post content block

Environment
- WordPress: 6.7-beta2-59195
- PHP: 8.1.23
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.23)
- Browser: Chrome 129.0.0.0 (macOS)
- Theme: Twenty Twenty-Five 1.0
- MU-Plugins:

Video - https://github.com/user-attachments/assets/738f41e2-f875-49ec-9065-570ffb7314ea

**Comment by beafialho** [comment]
> [@beafialho](https://github.com/beafialho) I understand this was the desired design, but those color combinations were not accessible in all style variations, which they must be, see [#468](https://github.com/WordPress/twentytwentyfive/issues/468)

Ok, that should be ok then. Thanks.

**Comment by carolinan** [comment]
The layout problem with the blocks in the post content block in the site editor has been fixed in Gutenberg and the fix will be in WP 6.7 Beta 3. So I am closing this issue.
