### ISSUE TITLE
Set up 2025.wordpress.net

### ISSUE THREAD

**Issue by bbeyss** [WordPress/twentytwentyfive#47]
We should set up a development site + a github action that deploys trunk of this theme.

For reference, here's the same discussion for Twenty Twenty-Two: WordPress/twentytwentytwo#21

**Comment by juanfra** [comment]
Thanks for opening this issue. Indeed, it'll be helpful and we could start working on it.

👋 @kraftbj - I saw you helped with this for the previous default themes. Is this something you could help us with again? Or do you know who the right person to ping would be? I really appreciate any help you can provide.

**Comment by kraftbj** [comment]
Hey hey! I can handle this if it is okay to wait until Sept 1 to spin it up (I'm on leave but checked in just for this when I saw dev starting up). If it can't wait, lmk and I'll make it happen.

**Comment by juanfra** [comment]
Hey @kraftbj!

Yes, absolutely. September 1st sounds perfect; thank you so much!

**Comment by karmatosed** [comment]
Adding task to this as it will be something to be done.

**Comment by SRIIAKHILLESSH** [comment]
Hello, I'm willing to help as I completed these things on my project earlier. Please feel free to ping me for  tasks if you need my assistance.

**Comment by beafialho** [comment]
> Hey hey! I can handle this if it is okay to wait until Sept 1 to spin it up (I'm on leave but checked in just for this when I saw dev starting up).

Thank you! Once it's spun up I'll add the demo content.

**Comment by kraftbj** [comment]
The site is now ready. Akismet is active using the wordpress.org account and set to auto-update. The theme itself will `git pull` from trunk every 5 minutes. I've sent DMs to @beafialho and @juanfra to spin up accounts for them. Leaving this open for any discussion of the demo content.

**Comment by beafialho** [comment]
Thank you @kraftbj!

**Comment by juanfra** [comment]
Thanks so much @kraftbj 🥇

**Comment by beafialho** [comment]
@kraftbj even though you mentioned the theme will pull from trunk every 5 minutes, I see the demo site isn't showing the latest changes. Do you know why that is?

**Comment by kraftbj** [comment]
@beafialho Sorry about that. Not sure what I messed up, but it's working now. Reset the cronjob and monitored to make sure it pulled.

**Comment by beafialho** [comment]
No worries @kraftbj thank you so much, it's working now on my end too!

**Comment by unscripted** [comment]
I noticed several navigation links in the demo site are not resolving. How can we edit these URLs?

**Comment by kraftbj** [comment]
They can be edited via the Site Editor (they're custom links in a nav block). I'm not sure where they should be pointing to or if they're still pending.

**Comment by beafialho** [comment]
> I noticed several navigation links in the demo site are not resolving. How can we edit these URLs?

This is work in progress. I will address this soon.

**Comment by beafialho** [comment]
@juanfra could you please update the theme in the demo site to use the latest version? I just tried resetting templates and styles, but I'm still seeing the issue fixed in #616.

**Comment by juanfra** [comment]
@beafialho unfortunately I don't have access to do that.

@kraftbj is the theme itself still running the `git pull` every five minutes? I see that the WordPress install is in 6.7-RC2, and maybe the theme version is the one included there and not the latest from `trunk`? Or perhaps the cron stopped working.

**Comment by kraftbj** [comment]
@juanfra @beafialho give it a go now. I think the update that included the theme in core caused a bit of havoc in the repo, causing some git conflicts, which caused the pull to fail.

**Comment by beafialho** [comment]
Thank you @kraftbj, it seems like it's showing the latest version now!

**Comment by bbeyss** [comment]
Everything works perfectly before the release.
Thanks to everyone for the help!

**Comment by juanfra** [comment]
Thank you all, I'm closing this one.

**Comment by kraftbj** [comment]
Thanks all. If y'all think about it, give me a shout when the repo is archived and work is svn first, etc. I'll enable auto-updates for the theme from the w.org API and disable the git pull.

🥳
