### ISSUE TITLE
Color problems with "CV/bio" pattern

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#471]
**Description**

In some style variations, the text is not visible enough.

**Step-by-step reproduction instructions**
Select the Twilight style variation.
Insert the pattern "CV/bio"
Confirm if the text is visible enough and follow the contrast ratio requirement (4.5:1)
![image](https://github.com/user-attachments/assets/42075539-061a-42b2-bb2d-edefbb8276cd)

Repeat the test with Twilight:
![image](https://github.com/user-attachments/assets/b59176e8-5d13-4dc2-831c-f55d71032914)

Sunrise:
![image](https://github.com/user-attachments/assets/b509339b-04ad-4794-85d0-a202b8f6774e)

Midnight: 
![image](https://github.com/user-attachments/assets/c27a2749-00ce-4f56-8a6b-f191cdaa8d0e)

**Comment by troychaplin** [comment]
## Review Notes:

### Evening

- 2 errors related to text, expected ratio of 3:1, current ratio is 1.22.1
- links do not create additional errors

### Twilight

- 7 errors all related to text, expected ratio of 3:1, current ratio is 1.13.1
- added links in large and regular sized text to test link contrast, accounted for 2 errors

### Sunrise

- 2 errors related to text, expected ratio of 3:1, current ratio is 1.18.1
- links do not create additional errors

### Midnight

- 7 errors all related to text, expected ratio of 3:1, current ratio is 2.27.1
- added links in large and regular sized text to test link contrast, accounted for 2 errors
