### ISSUE TITLE
WP 6.7 Beta1 - Patterns shows JS error in Admin panel

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/twentytwentyfive#481]
Check https://wordpress.slack.com/archives/C02RQBWTW/p1727756569547209?thread_ts=1727756378.145009&cid=C02RQBWTW

When i click on Patterns in admin Editor got JS error for TT5.

`Warning: Style property values shouldn't contain a semicolon. Try "borderTopColor: color-mix(in srgb, currentColor 20%, transparent)" instead.`

<img width="1717" alt="Screenshot 2024-10-01 at 9 52 26 AM" src="https://github.com/user-attachments/assets/3c33e6ae-cc7d-4a02-a5c3-434f06b5a7e1">

**Comment by franzaurus** [comment]
I cannot replicate this. Perhaps it is browser or server-related.

**On Localwp**
![TT5-on-wp-67beta1-localwp](https://github.com/user-attachments/assets/1adc01ac-c4be-43bf-ad30-b09ef019768c)

**On Instawp**
![TT5-on-wp-67beta1-instawp](https://github.com/user-attachments/assets/43f6e3de-877b-4e1c-95aa-3453756c92a1)

**Environment**
**Localwp**
WP 6.7-beta1
Theme: Twenty Twenty-Five (twentytwentyfive)
Local Version 9.0.5+6706
Browser: Chrome Version 129.0.6668.70

**InstaWP**
WP 6.7-beta1
Theme: Twenty Twenty-Five (twentytwentyfive)
server_architecture: Linux 5.4.0-172-generic x86_64
Browser: Firefox Developer 131.0b9 (64-bit)

**Comment by PGeorgiev** [comment]
Joining the test squad here, I can't reproduce these JS errors either

![CleanShot 2024-10-01 at 11 15 51](https://github.com/user-attachments/assets/cb16356f-312b-43c9-bdc4-7899eea493dd)


**Environment**
MAMP Pro
WP6.7-beta1
Theme: Twenty Twenty-Five (twentytwentyfive)
PHP Version: 8.1.13
Browser: Google Chrome — Version 129.0.6668.59

**Comment by t-hamano** [comment]
Since this is a script warning, you can reproduce it by enabling `WP_SCRIPT_DEBUG`.

I think this needs to be fixed.
