### ISSUE TITLE
Inconsistent search block styles in the style variations

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#485]
**Description**
There are some differences in styling of the button blocks and the search form when the different style variations are applied.

According to [the design in Figma](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=77-7923&m=dev), these variations should have input elements and buttons with a border radius that is not the same as the default:

- Dusk: 4px
- Afternoon: 0
- Morning: 0
- Sunrise: 0
- Midnight: 0

**Step-by-step reproduction instructions**
Add button block.
Add a couple of search form blocks with different button settings:
Outside, inside, with icon, etc.

**Expected behavior**
For the theme to match the design in Figma.

**Screenshots**
Noon:
Missing shadow (maybe intentional?)
Different font size: the search form button has larger text and a different font family (maybe intentional?)
![image](https://github.com/user-attachments/assets/e3ab9184-9cea-4057-8d9a-33d109c3c599)

Dusk:
Different border radius
![image](https://github.com/user-attachments/assets/da8f1e90-bc5b-4e04-bc70-cdef9ea54182)

Afternoon:
Different border radius
![image](https://github.com/user-attachments/assets/4f141038-38a9-4277-a13f-4abf4b2fa9e3)

Morning:
Different border radius
![image](https://github.com/user-attachments/assets/aa5aa0dd-ba64-4f2b-95a9-5609a9e95238)

Sunrise:
Different border radius
![image](https://github.com/user-attachments/assets/d3f8ced6-e013-4919-b694-41c8dfc36c1e)

Midnight:
Different border radius
![image](https://github.com/user-attachments/assets/f12d58d5-8a92-4596-89bb-619ab8aecff3)

**Comment by beafialho** [comment]
Yes, correct. I believe this is a Gutenberg bug. What other design feedback is helpful here?

**Comment by carolinan** [comment]
I'll try to fix the radius.

Noon:
Is the missing shadow on the search form button intentional?
The search form button has larger text and a different font family, is it intentional?

**Comment by beafialho** [comment]
> Is the missing shadow on the search form button intentional?
> The search form button has larger text and a different font family, is it intentional?

The missing shadow isn't intentional, it should have it. The font family and size should also be the same as the other buttons.

**Comment by carolinan** [comment]
I am not sure about setting the border radius of the inputs to 0 anymore.
If it is set to 0, it won't match the comments form inputs. I found that WP sets these to a border radius of .25rem. With a 16 px base font size .25rem is 4px, which is the same as for the dusk variation.

**Comment by carolinan** [comment]
Here is a screenshot of the Midnight variation with the border radius set to 0 only on the button and search block.
It would probably be better to manage all these styles together with https://github.com/WordPress/twentytwentyfive/issues/484
because then we could decrease the amount of CSS and manage it from one place, one file.

![Image](https://github.com/user-attachments/assets/a2526b35-20c2-44ce-bb36-4785211662cf)

**Comment by carolinan** [comment]
Ah, I just remembered that the style variations do not output a class name, so it is not straight forward to add custom CSS to a style variation in a CSS file.
Sigh.

**Comment by carolinan** [comment]
It really feels like we are going in circles trying to solve the same problems over and over because something is not supported in Gutenberg.

**Comment by carolinan** [comment]
Closing this as wont fix, this can be addressed once either of these are fixed in Gutenberg:
- The CSS in theme.json is updated correctly when style variations are switched
- The active style variation can be identified with a CSS class name that can be used as a selector for the styles.
