### ISSUE TITLE
Will the theme ship with a comment block in the Pages template

### ISSUE THREAD

**Issue by unscripted** [WordPress/twentytwentyfive#490]
**Description**

While testing the 6.7 Beta 1, I encountered a "Page with comments" in the About The Tests dropdown. Since the Pages template doesn't have the comments block, it was not displayed. However, it works as expected after adding the block to the Pages template.

My expectation is that the theme does not ship with the comment block in the Pages template, but I wanted to confirm.

**Comment by carolinan** [comment]
Pages will not have the comments area by default. But there is a pattern that users can insert so that the comments area on posts and pages will look the same.

**Comment by unscripted** [comment]
Thank you, @carolinan. Based on your answer, I've closed this issue.
