### ISSUE TITLE
Use of $ in sample content

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#493]
**Description**

If the demo flower shop is based in the EU:
`Fleurs is a flower delivery and subscription business. Based in the EU, our mission is not only to deliver stunning flower arrangements across but also foster knowledge and enthusiasm on the beautiful gift of nature: flowers.`

Why are dollar signs used?

![Image](https://github.com/user-attachments/assets/4ed66efe-c8f6-4a05-95e1-d800b9205552)

**Comment by unscripted** [comment]
@carolinan Can you provide a link to the demo for this issue?

**Comment by carolinan** [comment]
A _demo_? No.
You can view the theme code or insert the "Call to action with grid layout with products and link" pattern.

**Comment by carolinan** [comment]
OH!
You thought I was talking about an actual demo of a working shop.
I am talking about how the text content, the sample text in the patterns, talks about a flower shop in EU while this pattern for the flower shop, uses the dollar sign.

No: -I reached out to the WooCommerce theme people during one of their open office hours and they said they would get back to us but they never did. So I guess they want to do their own thing.

**Comment by beafialho** [comment]
> Why are dollar signs used?

A dollar sign is used clearly by mistake. It should be replaced by an `€` sign.
