### ISSUE TITLE
A header may be missing for the news blog alternative templates

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#498]
In Figma some of the news blog templates have a vertical menu, not horizontal.
This design and this header is not part of the theme.
_If_ this is correct, can the Figma files please be updated so that more time is not spent on it?

I don't mind how the vertical menu looks. But I am concerned that if it is implemented, it will only work as long as the user keeps the menu short.
It is not possible for the theme or the block to limit the number of menu items.

News blog with featured posts grid
![Image](https://github.com/user-attachments/assets/b34c6150-511d-4911-bdc3-bb6181ecc2bd)

News blog with sidebar
![Image](https://github.com/user-attachments/assets/73712b60-efbf-42b1-bec4-2964ecd21b84)

Left-aligned content
![Image](https://github.com/user-attachments/assets/d9a1348b-acbb-462e-b321-3ff8eb9280ca)

**Comment by carolinan** [comment]
OK, I found it: header-large-title.php. It does not seem to be used anywhere in the theme. Perhaps someone can remind me if this was a conscious decision. @beafialho @juanfra.

**Comment by beafialho** [comment]
This header should be a part of the theme, since it gives users an opinionated header layout option to use where they see fit.

**Comment by carolinan** [comment]
OK, but it is not supposed to be used in these templates by default? If that's the case we don't need to make any other changes <del>than adding it to theme.json</del>.

**Comment by beafialho** [comment]
It was intended to be used in these 3 templates by default. I can't exactly recall why it wasn't added in the first place.

![Image](https://github.com/user-attachments/assets/7fee13f9-316b-45a1-9d90-7f8c00c5ea9e)

**Comment by carolinan** [comment]
Let's leave this until last, if there is time left we can look at it then.

**Comment by kirtangajjar** [comment]
@carolinan I can take a shot at it!

**Comment by carolinan** [comment]
This is not as simple as it may appear, and there are valid reasons not to do it.
Just like with the vertical header,  if this is created into a template part to be used as the default, the end result is going to be confusing for the visitor of the site **unless there is a complete set of templates.**
Otherwise you end up with home having one header, 404 another, and single posts a third header, which makes it dififcult to navigate the site.

Creating a full set of templates increases the number of files and designs to maintain, and makes the theme more difficult to use.

Without a way to apply the entire template set across the site, switching all the templates starts to get overwhelming.

**Comment by carolinan** [comment]
It's already kind of confusing since the theme is basically 1 parent theme and multiple child themes in one.

**Comment by carolinan** [comment]
Closing in favor of https://github.com/WordPress/twentytwentyfive/issues/591
