### ISSUE TITLE
Quote & Pullquote visual adjustments

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#501]
We've come down to the finest details. While testing the theme, I noticed the quote isn't looking as it was before. The font size is smaller than the rest of the text, and it should be the same size. It's also using Semi Bold font weight, this was probably intentional, but if possible, let's make the change to use the same weight as the rest of the text as well.

| Currently      | Improved |
| ----------- | ----------- |
|![Image](https://github.com/user-attachments/assets/ffc4502d-56e5-41e6-9644-9e57ae2bed38)    |    ![Image](https://github.com/user-attachments/assets/55262c3f-7c4e-4869-95dc-e8ab65015acf)  |

Citation is also looking different in quote and pull quote. They should look similar in both. Notice the differences in the two citations: 

![Image](https://github.com/user-attachments/assets/fa2a5c37-3b6a-4977-9c45-551fa3eb53c5)

This bit that's applied to the pull quote seems good to be applied to both. We should however apply `-0.1px` letter spacing to both.
```
"elements": {
	"cite": {
		"typography": {
			"fontSize": "var:preset|font-size|small",
			"fontStyle": "normal"
				}
```

**Comment by troychaplin** [comment]
@beafialho is the idea here that the citations would look the same in both? IMO it certainly looks better than the pullquote citation being a large font with a matching -0.1. Adding a couple attachments

![Image](https://github.com/user-attachments/assets/fb633003-5442-49e2-b318-c01bf0944414)

![Image](https://github.com/user-attachments/assets/766e6587-8c40-4992-9dc8-5eab3403c30f)

**Comment by troychaplin** [comment]
I have a branch in my fork ready to PR in depending on which style is needed here. Branch currently setup with have citations matched up on both blocks -- https://github.com/troychaplin/twentytwentyfive/tree/update/quote-pullquote-visuals

**Comment by beafialho** [comment]
Yes, citation should look the same size and letter spacing in both, not huge like the quote.

**Comment by beafialho** [comment]
Closing as this has been addressed.
