### ISSUE TITLE
New Feature: Expanding mobile menue for submenus

### ISSUE THREAD

**Issue by hagege** [WordPress/twentytwentyfive#503]
I know that the problem is certainly related to the navigation block (see https://wordpress.slack.com/archives/C015GUFFC00/p1728199401850279), but I would like to point out this improvement again.
Twenty Twenty-Five does not offer the option of expanding the mobile menu for submenus - In my opinion, this would be a great advantage, especially for longer submenus.
![Image](https://github.com/user-attachments/assets/265237d4-7cdc-48e1-a03c-4f1886c33495)

**Comment by carolinan** [comment]
Hi @hagege, the theme will only use the features that are already built in to the navigation block. The deadline for adding features to WordPress 6.7 has passed. I am closing this issue as not planned.
Once or if WordPress supports this feature, the theme will support it too.

**Comment by hagege** [comment]
Hi @carolinan 
Thank you for the information.
I fully understand that it is too late for this feature.
