### ISSUE TITLE
Is a bit hard to add a custom link in the navigation menu.

### ISSUE THREAD

**Issue by alexcu21** [WordPress/twentytwentyfive#524]
**Is your feature request related to a problem? Please describe.**

It is currently difficult to add a custom link to the navbar in the header template part. Every time I need to add a custom link it doesn't allow adding the url in the link field. The only way I've found to do it is adding a page link and change the url in the link field. Is this an expected behavior, or it is included in the roadmap.

Also, I'm providing a loom video with an example. 

[Loom video with example](https://www.loom.com/share/2c50de9325f0497bbc3ff3f6e8d0e060?sid=ba014b7a-cd56-413b-bb93-e736ca67afb5)

**Describe the solution you'd like**
It should allow me to add a url in the link field when I add a custom link in the navbar block.

**Comment by carolinan** [comment]
Hi @alexcu21, thank you for testing the theme.

The theme can only use the features that are available in the navigation block.
Any problems with the block needs to be reported and solved in the Gutenberg GitHub repository.

Here is the current list of open issues for the navigation block: https://github.com/WordPress/gutenberg/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22%5BBlock%5D%20Navigation%22

**Comment by alexcu21** [comment]
Thank you very much for clarification @carolinan, I'll check if somebody already reported.
