### ISSUE TITLE
Photo single post: It is difficult to edit content in the post editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#529]
**Description**

When the Photo blog single post template is used, the content in the post editor (block editor) is touching the edge of the editor. It makes the content more difficult to edit.

Because there is no space between the text and the edge, some letters are difficult to read.

**Step-by-step reproduction instructions**
Go to Appearance > Editor > Templates.
Select the single post template.
In the settings sidebar, open the template tab.
In the template tab, open the design panel.
Select the photo blog single post template.
Save.

Create a new post.
Add some text content.

**Expected behavior**
I expect the content to be easy to edit and read.

**Screenshots**

![Image](https://github.com/user-attachments/assets/8db9a29a-40d4-4791-890b-6022b9e3d5cc)

**Comment by carolinan** [comment]
Another unexpected result is that the content and the editor do not match.

Here is the pricing pattern with 3 columns in the editor, with the two sidebar open, to show the pattern in a narrow area:
![Image](https://github.com/user-attachments/assets/38602b63-7c04-4f32-9d23-3d87a7cc9c67)

And on the front:

![Image](https://github.com/user-attachments/assets/e5c58f8c-9de3-49bd-a8be-ef8428d12fb4)

**Comment by carolinan** [comment]
What if instead of this editor experience
![Image](https://github.com/user-attachments/assets/b6998d46-1cf5-4933-b118-37c1925e97fc)
and this front view:
![Image](https://github.com/user-attachments/assets/a0a83f37-1d4d-4319-a47e-2d594bdf79da)

It could be one of these?

Editor:
![Image](https://github.com/user-attachments/assets/79f6c2ae-6b37-4a9d-bb5a-21b93ea0f337)

Front:
With the columns intact
![Image](https://github.com/user-attachments/assets/56665056-7f29-4297-b44a-48fbe5faafbe)

Without the columns
![Image](https://github.com/user-attachments/assets/80848e84-cd11-4766-bd22-726e88b6fd0c)

----

## Left-aligned, but allowing wide (not full though)

Editor
![Image](https://github.com/user-attachments/assets/f3195a23-bb3c-43e8-af8a-591e9e5b2caa)

Front:
![Image](https://github.com/user-attachments/assets/0f6c9046-fcf9-4a4c-a102-693492d46a1d)

**Comment by beafialho** [comment]
> When the Photo blog single post template is used, the content in the post editor (block editor) is touching the edge of the editor. It makes the content more difficult to edit.

I agree. The experience is bad and shouldn't appear like that.

This workaround seems like it provides a good alternative. I thought this was an editor issue, but if we can improve it via the theme, great.

My only comment/advice is for us to keep the default content aligned with the rest of the template elements to stick with the design intention (see the line on the left of the screenshot), but it seems you're taking that into consideration here.

![Image](https://github.com/user-attachments/assets/27b6a167-ced5-4cd3-baea-e4e8c8cab16a)
