### ISSUE TITLE
List block: polish spacing between indented items

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#531]
Currently, the list indented items seem to have less line height (or padding, or margin) than the default list items. Here's a comparison of the current and intended spacing:

| Current      | Intended |
| ----------- | ----------- |
|![Image](https://github.com/user-attachments/assets/e6a3daf9-70ce-479b-ac45-9a30125ecfae)  |    ![Image](https://github.com/user-attachments/assets/7eadf6b3-450e-44a0-914a-1a1030df4885)   |

**Comment by carolinan** [comment]
Good catch, I might even consider this a bug since the nested items are bit harder to read.

**Comment by carolinan** [comment]
I think switching the existing margin-bottom style in theme.json to margin-top might work.
![Image](https://github.com/user-attachments/assets/86edaa8e-01a2-4174-8256-9357319042f7)

**Comment by sudip-md** [comment]
### Test Report

**Tested Patch** - https://github.com/WordPress/twentytwentyfive/pull/544/files

**Screenshot** - ![Image](https://github.com/user-attachments/assets/c76e9faa-ffe0-4070-b9b6-77ba4c4912e0)


Now, the default list items have proper space

 **Environment**
- WordPress: 6.7-beta2-59195
- PHP: 8.1.23
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.23)
- Browser: Chrome 129.0.0.0 (macOS)
- Theme: Twenty Twenty-Five 1.0
- MU-Plugins:
  * Testing 10up's Ad Refresh Control Plugin
