### ISSUE TITLE
Afternoon: List of elements to adjust

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#538]
While testing **Afternoon variation and its typography preset**, I noticed some size issues that make it look bad.

![Image](https://github.com/user-attachments/assets/150c6fbd-58e1-45f7-8402-8f9284be396b)

I tried to edit the files myself but the chance of messing them up was high, so I tried my best to enumerate the following changes I made in Global Styles in the editor, which I kindly ask be taken to a PR.

- Change font preset XXL: min `2rem`, max `2.6rem`
- Change font preset XL: min `1.4rem`, `1.8rem`
- Text: set to `font-weight: 300`, line height to `1,5`
- Headings: set to `font-weight: 400`, letterSpacing: -0,1px , line-height: 1.2
- H1: XXL font size
- H2: XL font size
- H3: L font size
- H4: M font size
- H5: M font size
- H6: S font size + (remove uppercase, letter spacing, remove specific font weight, it should be `400` same as others)
- Site Title: set to Large font size
- Post author, post author name, post date, post terms: remove font size preset added globally
- Titles (Post Titles): any specific settings should be removed, they should inherit the headings settings

Here's how it's supposed to look with these changes:

![Image](https://github.com/user-attachments/assets/e6fc1794-47c0-4856-b9a9-4b8d3a8fa187)
![Image](https://github.com/user-attachments/assets/f0c11572-38d2-45ec-a59b-175300a728c0)
![Image](https://github.com/user-attachments/assets/de8bd91e-e1d2-4ba9-ae10-066c3f2bf54a)
![Image](https://github.com/user-attachments/assets/f551f4bb-fb6f-4af3-92e1-87bd5935576d)
![Image](https://github.com/user-attachments/assets/57fc8208-4a20-47af-ae37-613e467135fb)

cc: @juanfra @carolinan @richtabor

**Comment by carolinan** [comment]
Is it intentional the H4 and H5 should be identical? I am not sure that is ideal.

**Comment by beafialho** [comment]
Yes, it is intentional. I assumed we'd prefer to use font size presets in the headings.

**Comment by carolinan** [comment]
I wish I could get 100 likes on https://github.com/WordPress/gutenberg/issues/65108

**Comment by troychaplin** [comment]
@carolinan @beafialho I just submitted PR #564 to fix some of the items in the original list

> Change font preset XXL: min 2rem, max 2.6rem
> Change font preset XL: min 1.4rem, 1.8rem
> Text: set to font-weight: 300, line height to 1,5
> Headings: set to font-weight: 400, letterSpacing: -0,1px , line-height: 1.2
> Site Title: set to Large font size\
> Titles (Post Titles): any specific settings should be removed, they should inherit the headings settings

Items that I'm not sure how or where to address (apologies, just learning block themes, I've only used some of their features in hybrid themes so far, so TT5 to me is a whole new experience)

> H1: XXL font size
> H2: XL font size
> H3: L font size
> H4: M font size
> H5: M font size
> H6: S font size + (remove uppercase, letter spacing, remove specific font weight, it should be 400 same as others)

Question about the following:

> Post author, post author name, post date, post terms: remove font size preset added globally

In the primary `04-afternoon.json` I see `core/post-author`, `core/post-author-biography` and `core/post-author-name` and each of them have `"fontSize": "var:preset|font-size|medium"`. Is this what needs to be removed, or is that done elsewhere?

Happy to fix anything i missed with some feedback, just point me in the right direction and I'm on it :)

**Comment by karmatosed** [comment]
Looks like this has a partial PR so will focus over there.

**Comment by troychaplin** [comment]
> Looks like this has a partial PR so will focus over there.

I have added a series of screenshots for all the changes I have made, as well as adding additional comments and screenshots to for additional work. Unless I missed or misunderstood something, this should be a completed PR now.

**Comment by juanfra** [comment]
Closed as completed via https://github.com/WordPress/twentytwentyfive/pull/564
