### ISSUE TITLE
Twilight: List of elements to adjust

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#540]
While testing the **Twilight variation and its typography preset**, I noticed some size issues that make it look awkward.

![Image](https://github.com/user-attachments/assets/5b7e3a26-b3a7-4ddc-be6b-adf364c945a2)
![Image](https://github.com/user-attachments/assets/f288e70d-494f-42f1-a09f-7d076cea7df5)

I tried to edit the files myself but the chance of messing them up was high, so I tried my best to enumerate the following changes I made in Global Styles in the editor, which I kindly ask be taken to a PR.

- Title: remove all specific customizations
- Text: set to `font-weight: 300`, letter spacing: 0, `line-height: 1.4`
- Headings: set to `font-weight: 300`
- Post terms: remove uppercase setting
- H5: remove all custom settings
- H6: remove all custom settings
- Font size XXL: min `2.15rem`, max `2.4rem`
- Pullquote: use XXL font size

Here's how it's supposed to look with these changes:

![Image](https://github.com/user-attachments/assets/4fda08c6-5635-47a7-afee-93913b97092d)
![Image](https://github.com/user-attachments/assets/f9d5b780-183e-408f-b8f9-4186cd652de4)
![Image](https://github.com/user-attachments/assets/b33428c4-074a-4762-acfc-1f2f0298ad7c)
![Image](https://github.com/user-attachments/assets/ebadf1f6-0bf7-4b29-9910-5093cc52d02f)
![Image](https://github.com/user-attachments/assets/6475cd0b-2ed3-4d63-b2e0-88229cc0cd47)
![Image](https://github.com/user-attachments/assets/797cb428-964e-409d-af6e-7bc37cf2ef15)
![Image](https://github.com/user-attachments/assets/d63d1342-4937-470e-8407-6d8f5925c29c)

cc: @juanfra @carolinan @richtabor

**Comment by sudip-md** [comment]
### Test Report

I have tested various typography with various styles, including Twilight style and it is working as expected.

**Environment**
- WordPress: 6.7-beta2-59195
- PHP: 8.1.23
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.23)
- Browser: Chrome 129.0.0.0 (macOS)
- Theme: Twenty Twenty-Five 1.0
- MU-Plugins:
  * Testing 10up's Ad Refresh Control Plugin

Video - https://drive.google.com/file/d/1Ct-9ota2nSqaO7Wf5zp3nrZ1HzAWJ8vh/view?usp=sharing
