### ISSUE TITLE
Verse block - background image does not have overlay or filter option

### ISSUE THREAD

**Issue by severine-pozzo** [WordPress/twentytwentyfive#542]
Currently, when adding a background image to the Verse block, the user does not have the option to add an overlay or a filter to the image. Adding this option might also help on that same block to have a better interaction between the background image and the background color of the Verse Block. 
 
https://github.com/user-attachments/assets/49071d26-a168-4b70-bf8b-7f0fb4b5be48

**Describe the solution you'd like**
An overlay and filter option like we have on other blocks
![Image](https://github.com/user-attachments/assets/79064eb7-b513-4fda-8d24-c66f51d4c70f)

**Comment by carolinan** [comment]
Hi @severine-pozzo 
The theme can only use the features that are built in to the block and WordPress.
Any enhancements or bug reports for the blocks themselves needs to be opened in the GitHub repository for Gutenberg.
These type of enhancements are not specific to Twenty Twenty-Five, they affect all themes.

**Comment by severine-pozzo** [comment]
Hello @carolinan 
Thank you for your answer. I did just that and I will close this current issue.
