### ISSUE TITLE
Noon: List of elements to adjust

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#547]
While testing the **Noon variation and its typography preset**, I noticed some elements could be improved:

![Image](https://github.com/user-attachments/assets/768593c5-dde0-4e04-8741-b80b81703ba8)
![Image](https://github.com/user-attachments/assets/736a3edc-5e36-4aa2-beeb-a78e62718b25)

Here are the changes that can improve the look of the variation & typeset:

- Reset Post Author styles
- Reset Post Date styles
- Post Terms: reset font and font size
- Reset Titles typography styles
- Text: set letter spacing `-0.01em` and line height `1,6`
- All Headings: set letter spacing `-0.02em` , line height `1,02`
- H3: set to L font size
- H5: remove custom letter spacing
- Text preset size XL: min `2rem`, max `2.8rem`
- Text preset size XL: min `1.8rem`, max `2.2rem`
- Text preset size L: min `1.6rem`, max `1.8rem`
- Text preset size Medium: min `1rem`, max `1.2 rem`
- Quote: remove line height (it should be the same as text)

How it's expected to look with the changes applied.

![Image](https://github.com/user-attachments/assets/54453f52-c8ed-486c-8201-2284f617a73a)
![Image](https://github.com/user-attachments/assets/82448a86-13a9-4e1f-870c-11add06cec54)
![Image](https://github.com/user-attachments/assets/f63d3ba3-7400-4db5-b587-2e3029217b8b)
![Image](https://github.com/user-attachments/assets/ed1616c1-8d72-4a5b-914b-99ace2443533)
![Image](https://github.com/user-attachments/assets/8c4c7a9e-0b46-4409-8d3f-3cf150b0294d)

cc: @juanfra @carolinan @richtabor

**Comment by juanfra** [comment]
@beafialho I have a question for you:

1. `H3: set to L font size` - This would mean that H3 and H4 will have the same size. Should we review this?

**Comment by beafialho** [comment]
> [@beafialho](https://github.com/beafialho) I have a question for you:
> 
> 1. `H3: set to L font size` - This would mean that H3 and H4 will have the same size. Should we review this?

I expected they'd be the same size since there are only 5 font size presets :(

**Comment by juanfra** [comment]
Perfect, thanks for the clarification.
