### ISSUE TITLE
Midnight: List of elements to adjust

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#549]
While testing the **Midnight variation and its typography preset**, I noticed some elements could be improved:

![Image](https://github.com/user-attachments/assets/41b2a7cb-8e78-4da0-ab62-d7725fbd0189)
![Image](https://github.com/user-attachments/assets/f3123704-2885-4bc1-b2c3-596eabc08dcc)

Here are the changes that can improve the look of the variation & typeset:

- Post Author Name: reset styles
- Post Terms: reset styles
- Font size preset XXL: min `2rem`, max `2.8rem`
- Font size preset XL: min `1.8rem`, max `2.2rem`
- Font size preset L: min `1.2rem`, max `1.8rem`
- Font size preset M: min `0.9rem`, max `1.2rem`
- Font size preset S: `0.9rem`
- Text: set to font size preset M, letter spacing `-0,01em`, line height `1.5`
- Quote: reset font size (it should use the same preset as Text)
- Pullquote: remove specific line height
- Headings: line height `1.24`
- H6: remove specific font-weight (it should be the same as other headings, 300)
- Buttons: set to font size preset M, `font-weight: 400`, letter spacing `-0.01em`
- If it’s possible, can we remove Fira Sans Bold from the theme and whenever the Bold typography setting is selected and applied, it falls back to Fira Sans Medium? Mostly because Fira Sans Bold is appearing a bit harsh visually, probably because there’s no font smoothing, like there is on Figma.

How it's expected to look with the changes applied.

![Image](https://github.com/user-attachments/assets/0d828a2f-5387-4f8d-a4cc-9255bdb0ffe8)
![Image](https://github.com/user-attachments/assets/6d823ad9-e1ee-4f52-93da-ccb5005398e5)
![Image](https://github.com/user-attachments/assets/ace21598-b226-4963-9936-60c16c710e77)
![Image](https://github.com/user-attachments/assets/2b120666-ed45-4d89-9b4e-6dbec65081d9)

**Comment by carolinan** [comment]
> If it’s possible, can we remove Fira Sans Bold from the theme and whenever the Bold typography setting is selected and applied, it falls back to Fira Sans Medium? Mostly because Fira Sans Bold is appearing a bit harsh visually, probably because there’s no font smoothing, like there is on Figma.

Interesting question; yes it can be removed, I am not sure what it will fall back to 🤔
