### ISSUE TITLE
Arrow icon outside of anchor tag

### ISSUE THREAD

**Issue by ariful93** [WordPress/twentytwentyfive#553]
This issue found in single blog post 
![Image](https://github.com/user-attachments/assets/120571c8-a043-4151-a1ff-ac22ecc38238)

**Comment by carolinan** [comment]
Hi @ariful93 
The theme can only use the settings and features that are built into the blocks.
Any enhancements or bug reports for the blocks themselves needs to be opened in the GitHub repository for Gutenberg.
These type of enhancements are not specific to Twenty Twenty-Five, they affect all themes.

**Comment by ariful93** [comment]
Thanks for suggestion
I am closing this issue
