### ISSUE TITLE
Color problems with the link in the "Link Format" pattern

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#558]
**Description**
The link in the "Link Format" pattern has a color contrast ratio that is too low against the pattern background, in _some_ style variations.

**Step-by-step reproduction instructions**
Insert a "Link Format" pattern.
Go to Appearance > Editor > Styles 
Select each of the different combined styles to test the pattern colors.

**Screenshots**

Evening:
![Image](https://github.com/user-attachments/assets/597d5651-820e-4271-9171-764a88a66040)

Morning:
![Image](https://github.com/user-attachments/assets/87ae493a-088b-49b5-bf31-e01b761149ca)

Sunrise:
![Image](https://github.com/user-attachments/assets/2d89a034-75f1-488d-981e-1d9a93b89405)

**Comment by carolinan** [comment]
Removing the custom color on the link  (the second paragraph block) should solve it, the color would use whatever is set as the link color for section style 3.

**Comment by beafialho** [comment]
> Removing the custom color on the link (the second paragraph block) should solve it

Thank you for reporting. This solution seems like a good one to me.
