### ISSUE TITLE
Please make official theme useable and good quality...

### ISSUE THREAD

**Issue by erikdemarco** [WordPress/twentytwentyfive#565]
Currently when you see 2024 theme, its very popularly downloaded. But its very unusable. For example when you see the header part in tablet or mobile it looks very ugly. See this:

https://www.loom.com/share/0711fc5166814f7bb200bcb97c5c38eb?sid=f5cb4a73-4e74-4c7f-a153-0a7142f49508

It will give impression to the users, that this theme just made to finish the development task fast without any care to the quality of the development at all.

How the quality control in the development process works? How can such UI be released to the production?

**Comment by t-hamano** [comment]
Thanks for the report.

The issue you're having is a Gutenberg issue, not a theme-specific issue. I think the underlying issue is that device preview is enabled even though you can resize the editor canvas via the left and right handles.

I've already submitted a PR to fix this issue: https://github.com/WordPress/gutenberg/pull/65970

**Comment by karmatosed** [comment]
Whilst I want to respect this comment I also want to consider what is a bug and what is looking at as noted the application of WordPress itself. For now, I think closing this and ensuring that PR gets attention feels right so thank you @t-hamano for persuing that. We can always reopen and revisit. I just want to ensure we have focus on things can be shipped in theme.

**Comment by erikdemarco** [comment]
@t-hamano Actually my issue not about the editor layout. Its more how user see our site from frontend. just see from front end in multiple device width you will understand. Even you can see it alredy in the video how it looks like in front end

**Comment by erikdemarco** [comment]
@t-hamano Actually its not about the editor layout. Its about the theme. just see this 2 headers looks in some device width. especially the second picture. I never see such alignment like that in all site. [Logo - Action Button - Menu]. 


![Image](https://github.com/user-attachments/assets/2424a41a-8406-4a08-aac0-9f9f202e95f3)

![Image](https://github.com/user-attachments/assets/64d1d009-1bce-4926-bbd0-98a20626ca7c)

**Comment by erikdemarco** [comment]
> Whilst I want to respect this comment I also want to consider what is a bug and what is looking at as noted the application of WordPress itself. For now, I think closing this and ensuring that PR gets attention feels right so thank you [@t-hamano](https://github.com/t-hamano) for persuing that. We can always reopen and revisit. I just want to ensure we have focus on things can be shipped in theme.

Im really sorry for misunderstanding, as far as i remember i didnt post it as bug or labeled it as a bug.

**Comment by t-hamano** [comment]
Thanks for the reply.

In your screenshot, I see a cart icon and a people icon that shouldn't be present in the default themes (both Twenty Twenty-Four and Twenty Twenty-Five).

Do you have any plugins active? If so, try disabling all plugins for a moment.

In any case, since you're mentioning the Twenty Twenty-Four theme, it doesn't seem like a problem with the Twenty Twenty-Five theme.

**Comment by carolinan** [comment]
WooCommerce automatically inserts the account and cart buttons either inside, before, or after the main menu in the header.

The theme wraps the main menu inside a row block to try to ensure that the buttons are aligned with the menu, but the theme can not control **exactly where** the plugin inserts the buttons in the different headers.

In Twenty Twenty-Five, when you change the header design from the default to for example the header with the centered menu, you also need to manually position (center) the WooCommerce icons.

These icons are not locked, you can move them to the position that you want.
