### ISSUE TITLE
Block Patterns - Testimonials - Review with large image on the right

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#57]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Testimonial - Review with large image on the right` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1810&t=IqDHO3nwfV13Hcvm-1)

![Testimonials_ Review with large image on the right](https://github.com/user-attachments/assets/1ae53330-c9df-4d03-8cf3-881ef3ea296f)

**Comment by g-elwell** [comment]
I'd like to give this one a go if that's alright
