### ISSUE TITLE
Changing the font breaks the design

### ISSUE THREAD

**Issue by 369work** [WordPress/twentytwentyfive#580]
**Description**

I am using the twentytwentyfive theme on Wordpress 6.7 beta3.
When I select certain typography in the theme customization, the header design falls apart.
The affected fonts are (robot slab&manrope) and (volkorn).
When I select it, the brand name and menu in the header drop by one line.
Is this a bug? Or is it by design?
![Image](https://github.com/user-attachments/assets/a70022b9-68bd-4503-b34a-4fcd5c2efe51)
![Image](https://github.com/user-attachments/assets/8158725a-af97-440f-97ed-125714b0c9ca)

**Comment by carolinan** [comment]
The different size of the fonts makes the text in the navigation larger or smaller, so all the menu items do not fit on one line.
You can make the menu shorter or use more sub menus.

**Comment by 369work** [comment]
Of course I agree with that idea.
However, since this only happens with two fonts, I would like to find a fundamental solution.

**Comment by hanneslsm** [comment]
> However, since this only happens with two fonts

It happens with all fonts, because it's dependent on the font-size and available space. Resize your browser window and you'll see it happens also with other designs. 

>I would like to find a fundamental solution. 

Related Discussion: https://github.com/WordPress/gutenberg/discussions/53475
