### ISSUE TITLE
Not possible to upload  a HEIC image in Post Editor through "Upload button"

### ISSUE THREAD

**Issue by oksanayoast** [WordPress/twentytwentyfive#583]
**Description**
It's not possible to upload  a HEIC image in Post Editor through "Upload button" , but you can drag and drop it or Upload through Media Library.

**Step-by-step reproduction instructions**

**Expected behavior**

You can upload a HEIC image n Post Editor through "Upload button". 

**Screenshots**

**Environment info**

**Additional context**

**Comment by juanfra** [comment]
Thank you. Support for HEIC images is one of the features that will be added in WordPress 6.7, so I'd recommend you trying the theme in an environment where the WordPress install is the latest (right now beta 3) and where you're also using Gutenberg in its latest version. You can install the [WordPress Beta Tester](https://wordpress.org/plugins/wordpress-beta-tester/) plugin to use WordPress beta versions.

If you're still having problems with the use of heic images in the context of the editor, I'd recommend you open the issue in the Gutenberg repository as the functionality lives there and we can't fix it in the theme.

**Comment by carolinan** [comment]
How can I test this without an iphone or ipad?

**Comment by carolinan** [comment]
It is not perfectly clear to me what is supported in 6.7.

This post says "This allows you to view HEIC images in WP Admin and use them in posts"
But does not clarify if by "WP Admin" it also includes the editor? Or perhaps only the media library admin screens?
https://make.wordpress.org/core/2024/08/15/automatic-conversion-of-heic-images-to-jpeg-in-wordpress-6-7/

**Comment by carolinan** [comment]
Either way, the HEIC upload problem it is not an issue with the theme itself, I am trying to determine if it needs to be reported in a new Trac ticket. 

@adamsilverstein May know more about what is supported.

**Comment by ndiego** [comment]
HEIC images are disabled for me as well when using the Upload button. This should work IMO.

![Image](https://github.com/user-attachments/assets/aed8f4ea-2db1-4788-9374-5e928afa5c51)

**Comment by ironprogrammer** [comment]
I agree that this isn't an issue with TT5 itself. I've opened https://core.trac.wordpress.org/ticket/62268 and assigned it to the 6.7 milestone for consideration (this will get more visibility, even if ultimately reported upstream).

Thank you for reporting and confirming this, @oksanayoast and @ndiego!

**Comment by adamsilverstein** [comment]
> Either way, the HEIC upload problem it is not an issue with the theme itself, I am trying to determine if it needs to be reported in a new Trac ticket.
> 
> [@adamsilverstein[<img alt="" width="15" height="15" src="chrome-extension://dlebflppeeemcdpidccbiblndppbmjmh/ospo-chrome-ext-logo.png">](https://teams.googleplex.com/adamjs@google.com)](https://github.com/adamsilverstein)[<img alt="" width="12" height="12" src="chrome-extension://hgomfjikakokcbkjlfgodhklifiplmpg/images/wp-logo.png">](https://profiles.wordpress.org/adamsilverstein) May know more about what is supported.

missed this earlier @carolinan - looks like we got it figured out on the other ticket and the bug also fixed upstream with Chromium.
