### ISSUE TITLE
Newly chosen options while editing the theme style aren't selected right away

### ISSUE THREAD

**Issue by sannevndrmeulen** [WordPress/twentytwentyfive#584]
**Description**

While adjusting the **Twenty Twenty-Five** style my newly chosen option does not get selected immediately, but instead I jump back to a previously made selection. If I select my newly chosen option a second time it works, but it does impact the user experience.

**Step-by-step reproduction instructions**

1. Activate the **Twenty Twenty-Five** theme
2. Go to **Appearance** -> **Editor**
3. Select **Styles**
4. Pick a style combination
5. Pick a palette or typography
6. Instead of the palette/typography being selected I jump back to the previous selected option (in this case style combination)

**Expected behavior**

My chosen option is confirmed and selected.

**Screenshots**

**Environment info**

**Additional context**

**Comment by juanfra** [comment]
Thank you. I can't replicate

https://github.com/user-attachments/assets/20f2c60b-813c-45c9-b9b1-b300ab8865aa


I'd recommend you try the theme in an environment where the WordPress install is the latest (right now beta 3) and where you're also using Gutenberg in its latest version. You can install the [WordPress Beta Tester](https://wordpress.org/plugins/wordpress-beta-tester/) plugin to use WordPress beta versions.

**Comment by sannevndrmeulen** [comment]
@juanfra I'm on version: **6.7-beta3-59243**.

Perhaps an extra reproduction instruction is required. I noticed that you picked options while the previously selected one is still in view, but I picked options while my previously selected one is no longer visible.

Unfortunately, I can't seem to upload my screen recording.

**Comment by juanfra** [comment]
@sannevndrmeulen thanks for the follow-up. Can you maybe upload it to a different service and share the link? GitHub only allows files that are less than 100mb.

**Comment by carolinan** [comment]
I can reproduce this.
Windows 11, chrome, 6.7-beta3-59248, Gutenberg is not active.

I select a style variation at the top of the list for example "Noon".
Then I scroll down to the bottom. Now, "Noon" is no longer visible in the list of theme theme style variations.
I click on the color palette called "Sunrise".
The color palette is not selected. Instead, when I click on the palette, it seems focus is only moved to the "Noon" theme variation.
Clicking on the color palette a second time applies the palette.

I don't think this is a problem with the theme. I will check if it is already reported in the Gutenberg GitHub repository.

https://github.com/user-attachments/assets/3926dda3-b664-46f8-a71f-954110f72470

**Comment by carolinan** [comment]
Can reproduce it with Gutenberg active, but I have not found any other theme to test that has this amount of style variations and palettes.

**Comment by carolinan** [comment]
@andrewserong Hi, do you know if this issue is reported, I think it may be the same as https://github.com/WordPress/gutenberg/issues/61841 ?

**Comment by andrewserong** [comment]
Thanks for the ping @carolinan!

> Hi, do you know if this issue is reported, I think it maybe the same as https://github.com/WordPress/gutenberg/issues/61841 ?

Yes, I believe it's the same issue based on that screengrab. It was also discussed and raised in https://github.com/WordPress/gutenberg/issues/65686.

I've tried a couple of times to dig into this without much luck unfortunately, so I doubt there'll be a fix in time for WP 6.7.

**Comment by carolinan** [comment]
I was able to confirm that I can not reproduce it in Firefox

**Comment by carolinan** [comment]
Thank you, I will close this issue as it is reported upstream.
