### ISSUE TITLE
Switching to "annotation" style does not preserve alignment

### ISSUE THREAD

**Issue by mhkuu** [WordPress/twentytwentyfive#585]
**Description**
When switching to the "annotation" style for a paragraph (or heading) block, the alignment is not preserved. 

**Step-by-step reproduction instructions**
1. Create a new post.
2. Add a paragraph block. 
3. Change the alignment ("text align center" or "text align right")
4. Switch to the "annotation" style.

**Expected behavior**
1. The paragraph block preserves the alignment when switching style (as is the case for the "display" and "subtitle" style)

**Actual behavior**
1. The paragraph block is aligned left when switching to the "annotation" style. 

**Screen capture**
https://github.com/user-attachments/assets/6ef703a6-742e-4588-a0c3-af00072b9f8f

**Environment info**
- Device: Desktop
- OS: Mac
- Browser: Chrome
- Version: 129.0.6668.101

**Comment by mhkuu** [comment]
Sorry, seems like this was already fixed through #581. Now the paragraph block is always aligned centered when switching to the "annotation" style, which I think can also qualify as expected behaviour.

**Comment by juanfra** [comment]
Thanks. Yes, that's the tradeoff we faced.

The easiest way to align the annotation would be to put it inside a stack/group and align it through that element (the parent).
