### ISSUE TITLE
Appearance and Settings panel overlaps Patterns page header while scrolling down

### ISSUE THREAD

**Issue by hardikgohil7988** [WordPress/twentytwentyfive#587]
**Description**

Appearance and Settings panel overlaps Patterns page header while scrolling down

**Step-by-step reproduction instructions**

1. Open the Site Editor from the dashboard.
2. Navigate to the Pattern section.
3. Click on the settings icon to open the appearance and settings panel.
4. Scroll down the page

**Expected behavior**

Scrolling should be disabled when the settings panel is open.

**Screenshots**

https://github.com/user-attachments/assets/eacba10a-5dde-430a-b6a2-7668de8eb7f4

**Environment info**

 - Device: MacBook Pro
 - OS: Sequoia 15.0.1
 - Browser: Chrome 
 - Version: 129.0.6668.101 
 - WordPress version: 6.7 beta-3
 - Gutenberg version: 19.4.0

**Additional context**

**Comment by juanfra** [comment]
Thank you for reporting.

The issue is related to DataViews and the codebase lives in Gutenberg. Can you please open an issue in that repository? I'd encourage you to search if it was already reported.
