### ISSUE TITLE
Broken styling in the navigation sub items

### ISSUE THREAD

**Issue by Jordi-PV** [WordPress/twentytwentyfive#588]
**Description**

The sub items styling in the navigation bar when the header has a background image is broken. 

**Step-by-step reproduction instructions**

1. Go to Appearance > Editor.
2. Select the menu option Navigation
3. Create or drag a new navigation sub page
4. In the editor, open the Settings sidebar.
5. Select the Block tab > Header > Design tab 
6. Select a header with a background image
7. Save the changes.
8. Go to "View site" 
9. Check the broken styling of the sub items in the navigation

**Expected behavior**

The sub items are visible and have the same style as the rest of the navigation items. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/407afa64-91ee-4ef8-a645-babb9e994bdc)

![Image](https://github.com/user-attachments/assets/4f82427e-c87c-4361-8151-1d58f07417ca)

![Image](https://github.com/user-attachments/assets/3af64ff3-76d4-4cc3-aad3-28c6cf71a1bf)

**Environment info**

**Additional context**

**Comment by juanfra** [comment]
Thank you for reporting.

Twenty Twenty-Five has four headers: Default, centered, with columns and with large title. I see that you have a few more headers there and it's likely that's coming from a plugin or some customization you have on your site. TT5 doesn't have "header with a background image".

**Comment by beafialho** [comment]
This header pattern is a core pattern, I believe coming from the Pattern Directory.

**Comment by carolinan** [comment]
I have been able to confirm that this is a problem with the pattern in the pattern directory.  It happens in every theme I tested. This has probably been happening since the pattern was introduced, since the default background color of the submenu is white, and the pattern sets the text color to white.

**Comment by carolinan** [comment]
I have reported it using the form on the pattern directory site.
