### ISSUE TITLE
Nit: Use neater image names

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#589]
Maybe it is just me? But these kind of names feels so untidy and sloppy and are not descriptive. `image-from-rawpixel-id-8802835-jpeg-scaled.webp`

**Comment by beafialho** [comment]
I agree, thank you for noticing and opening the issue. I will take a look at the image files and suggest names in a comment here.

**Comment by juanfra** [comment]
I definitely agree, thank you!

**Comment by troychaplin** [comment]
I’d be happy to take on this task when the list is ready, feel free to assign me.

**Comment by beafialho** [comment]
Here are name change suggestions:

- `image-from-rawpixel-id-13029755.webp` -----> `404-image.webp`
- `image-from-rawpixel-id-8802835-jpeg-scaled.webp` -----> `ruins-image.webp`
- `image-from-rawpixel-id-8812207.webp` -----> `botany-flowers-closeup.webp`
- `image-from-rawpixel-id-8799471.webp` -----> `red-hibiscus-closeup.webp`
- `image-from-rawpixel-id-2224378.webp` -----> `delphinium-flowers.webp`
- `image-from-rawpixel-id-2222755.webp` -----> `campanula-alliariifolia-flower.webp`
- `image-from-rawpixel-id-2211732.webp` -----> `star-thristle-flower.webp`
- `image-from-rawpixel-id-8802845.webp` -----> `akaka-falls-state-park-flora.webp`
- `image-from-rawpixel-id-8799918.webp` -----> `malibu-plantlife.webp`
- `image-from-rawpixel-id-8802603-original.webp` -----> `northern-buttercups-flowers.webp`
