### ISSUE TITLE
Dusk: Site title is colored

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#604]
**Description**
The site title for Dusk is purple, but in the design, it's not colored.

**Step-by-step reproduction instructions**
1. Activate the dusk variation.
2. Check the site title color, and confirm it's not like in the designs.

**Expected behavior**

The expectation would be to match the designs.

**Screenshots**

![Image](https://github.com/user-attachments/assets/4bffd919-3c79-4561-b185-f54a58e43576)

**Comment by troychaplin** [comment]
Just looking at this, I though removing the color references for site-title and the link element in `styles/03-dusl.json` would do the trick but it appears to not be the fix.

```
"core/site-title": {
	"color": {
		"text": "var:preset|color|accent-3"
	},
	"typography": {
		"fontFamily": "var:preset|font-family|vollkorn",
		"fontSize": "var:preset|font-size|x-large"
	},
	"elements": {
		"link": {
			"color": {
				"text": "var:preset|color|accent-3"
			}
		}
	}
}
```

**Comment by juanfra** [comment]
@troychaplin thank you for looking at this! That should be in combination with changes in `styles/colors/03-dusk.json`

**Comment by troychaplin** [comment]
@juanfra turns out it was an element style for links on the paragraph block
