### ISSUE TITLE
Dusk: Annotation vertical padding looks uneven

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#605]
**Description**

The annotation style in the dusk variation looks a bit uneven. It looks like it has more padding-bottom.

**Step-by-step reproduction instructions**

1. Activate dusk.
2. Try out a pattern including the annotation style, or the "Photo blog home"
3. Confirm that the annotation style is looking uneven.

**Screenshots**

![Image](https://github.com/user-attachments/assets/089067d3-becb-4796-b49c-f99bbf35c330)

**Comment by carolinan** [comment]
I can reproduce this, I think it may just be a typo:
I think the bottom padding should just be 0.2rem

```
    padding-top: 0.2rem;
    padding-right: 0.6rem;
    padding-bottom: 0.25rem;
    padding-left: 0.6rem;
```

**Comment by carolinan** [comment]
But it may be better to only update it for this style variation.

**Comment by carolinan** [comment]
Meh, now when I have switched computer, 0.2rem is also too large, and I need to set it to 0 bottom padding for the text to align. 🤷‍♀

**Comment by carolinan** [comment]
Ignore me, it is the same on both the mac (small screen resolution) and PC (large screen resolution), when 0.2 rem is used, the text is still miss-aligned.

**Comment by troychaplin** [comment]
@carolinan setting the padding bottom to 0.2rem seems to be fine, at least to me. Top example is 0.2, while bottom is original of 0.25

![Image](https://github.com/user-attachments/assets/03cb852e-5608-4667-a826-51ce4dad7aa4)

**Comment by juanfra** [comment]
@troychaplin It looks like the problem is with the headings' typography. The paragraph is using Fira sans, and it seems to work fine there. It looks off when the annotation is applied to a heading (using Vollkorn) like the one we have for the home page.

https://github.com/user-attachments/assets/c67c45cd-360a-4bf9-a834-bc2597f44398

**Comment by troychaplin** [comment]
Removing me as assignee in case someone else wants to take a look and has another approach to solving this issue. Notes around what has been attempted to date can be seen in close PR #636
