### ISSUE TITLE
"Poster-like" section looking broken in the front-end

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#606]
**Description**

When adding the poster-like section pattern in a page, and then viewing the page in the front-end (in large viewports > 1900px width), the text is breaking in several lines and the design looks broken.

**Step-by-step reproduction instructions**
1. Add a page.
2. Add the "Poster-like section" pattern.
3. View the page in a viewport that's bigger than 1900px width.

**Expected behavior**

**Screenshots**

![Image](https://github.com/user-attachments/assets/2f0b3993-9d09-460b-ad1e-ef6108327ad5)

**Comment by troychaplin** [comment]
Column widths changing to 80 / 20 fixes this issue, I put in a PR for this in case it's an acceptable solution from a design point of view. Visually, nothing else changes.

**Comment by juanfra** [comment]
Fixed via https://github.com/WordPress/twentytwentyfive/pull/611
