### ISSUE TITLE
Difficult to modify colors when a section style is applied

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#620]
In some variations, the section styles are forcing an explicit color values. The result of this is that the colors are visually the same to start with, but when you change the "Text" color in the inspector, the links, headings, etc values all remain using the fixed value. 

Wherever possible, these should reference the current text color, rather than explicit colors.

**Comment by richtabor** [comment]
We should be as testing themes more from a users' perspective, not just a technical one. I see this as a must-fix, as the current implementation makes modifying colors very difficult when a section style is applied.

**Comment by carolinan** [comment]
Do I understand correctly that you are changing the color on the container, the parent, and not selecting the individual block before changing the color?

**Comment by carolinan** [comment]
Please the issue description needs to be complete for anyone else to be able to understand what is and what is not working, and to re-test it.
