### ISSUE TITLE
Page with comments does not display comments

### ISSUE THREAD

**Issue by HeatherActon** [WordPress/twentytwentyfive#621]
**Description**
Page with comments doesn't show comments or comment form.

**Step-by-step reproduction instructions**
1. Ensure theme unit test data is imported.
2. Go to /about-2/page-with-comments/
3. See no comments and no comment form.

**Expected behavior**
Comments should be visible, as they are in test data.

**Screenshots**
[Image](https://github.com/user-attachments/assets/0598b5c7-13b9-4864-b3ec-7dbab2751c58)

**Environment info**
- MacBook Pro 
- WordPress Playground
- Chrome 129.0.6668.101
- PHP 8.2
- WP 6.7-beta3

**Additional context**
This is my first submitted issue! Open to any feedback!

**Comment by HeatherActon** [comment]
I'm not sure if I did this right, but I put in a PR that should fix this https://github.com/WordPress/twentytwentyfive/pull/622

**Comment by juanfra** [comment]
Thank you @HeatherActon - This was brought up [here](https://github.com/WordPress/twentytwentyfive/issues/490), and @carolinan shared that pages will not have the comments area by default. There is a pattern that users can insert so that the comments area on posts and pages will look the same.

**Comment by HeatherActon** [comment]
Ok, thank you!
