### ISSUE TITLE
"Call to action with grid layout with products and link" title displays in two lines for some variations.

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#627]
**Description**

When inserting the  "Call to action with grid layout with products and link" pattern, the title displays in two lines for the following variations:

**Afternoon**

![Image](https://github.com/user-attachments/assets/998a339f-f7dd-47a7-9e4f-ef27acb3ef45)

**Twilight**

![Image](https://github.com/user-attachments/assets/2a334b38-9004-4393-aa90-8492deee65f7)

**Morning**

![Image](https://github.com/user-attachments/assets/8aa584d5-292c-48e0-95a6-72412832c0f5)

**Sunrise**

![Image](https://github.com/user-attachments/assets/d19c6866-1995-4aee-a6d0-a9be8e5f95fa)

**Comment by juanfra** [comment]
@beafialho can you please take a look at this one when you have time? Thanks 🙌

**Comment by beafialho** [comment]
@juanfra I created a PR with a suggested change.

**Comment by juanfra** [comment]
Thank you!
