### ISSUE TITLE
Substitute Post Content block with Excerpt block in `template-query-loop.php`

### ISSUE THREAD

**Issue by michalczaplinski** [WordPress/twentytwentyfive#628]
### **Description**

The `template-query-loop.php` pattern should use the Excerpt block instead of the Post Content block. Otherwise, the "Reload full page" toggle is **enabled** and the Query Loop cannot use enhanced pagination. 

That's because the Post Content block is incompatible with the enhanced pagination of the Query Loop block. The Post Content block could contain any arbitrary content, and there is currently no reliable way to detect if it doesn't have content that might be incompatible. See https://github.com/WordPress/gutenberg/pull/55539 for more context.

### **Step-by-step reproduction instructions**
1. Open the site editor for the Home template.
2. Open the block inspector.
3. Observe that the "Reload full page" toggle is **enabled**.

### **Expected behavior**
The "Reload full page" toggle should be **disabled** thus allowing for enhanced pagination.

### **Screenshots**
![Image](https://github.com/user-attachments/assets/76752318-ec93-44a2-b15a-2266cbb192fd)

**Comment by beafialho** [comment]
Is this the pattern used in the default "Blog Home" template? If that's the case, we want this template to show the entire blog post, not the excerpt. This is a fundamental characteristic of the theme.

**Comment by carolinan** [comment]
I agree with @beafialho. It also helps show the post formats. If the excerpt was used, the posts with formats would always be identical to the other posts.

Users who needs to use this pagination can update the block in the template, or choose one of the other template designs.

**Comment by michalczaplinski** [comment]
Gotcha, thank you for clarifying 🙂 . I think we can close the issue then!
