### ISSUE TITLE
Heading h6 is looking bigger than the heading h5.

### ISSUE THREAD

**Issue by NidhiDhandhukiya74** [WordPress/twentytwentyfive#629]
**Description**

When you choose heading block and check it with h5 and h6 then h6 looks bigger than the h5.

**Step-by-step reproduction instructions**

1. Take Heading block.
2. Add some text.
3. check it the same text with the h5 and h6

**Expected behavior**

h6 had to be smaller than the h5.

**Screenshots**

![Image](https://github.com/user-attachments/assets/d8717656-905b-4d0d-a503-46397ee8a499)

**Environment info**

**Comment by troychaplin** [comment]
There seems to be some inconsistencies in heading sizes across the various themes. In some case h1 and 2 are x-large, 3 and 4 are large, and 5 is medium, 6 is small. In other cases 5 is med, 6 is small. And I think there are a couple more cases like this.

@juanfra @beafialho is there a conssitent pattern we want for headings? I can review and update those accordingly.

**Comment by beafialho** [comment]
@troychaplin I believe all style variations heading sizes have been reviewed, already. But just to double check, from which variation is the screenshot you shared in the issue?

**Comment by beafialho** [comment]
This is how it's looking and this is how it should look.

![Image](https://github.com/user-attachments/assets/da3692ae-9c59-4633-bbc1-bad26727946d)

**Comment by troychaplin** [comment]
@beafialho That looks like the default style, I didn't create the issue originally. I did notice that there are some differences in the afternoon theme, the h5 is set to medium and it looks bigger than the h4

![Image](https://github.com/user-attachments/assets/073fc98e-3c57-48bc-94db-05ec57c94926)

**Comment by juanfra** [comment]
@NidhiDhandhukiya74 thanks for creating the issue. 

Can you please share which style variation you are seeing this in? I'm assuming it's the default, as it's a white background. But maybe you can share more information on what you are doing to see things like that. Can you also confirm you don't have any customization in place? I believe there's no style variation where the heading is pink.

Thanks.

**Comment by sabernhardt** [comment]
The screenshots below ~should~ have no customizations, and they are taken at a width of ~480 pixels.~ 1,200 pixels and cropped. 
(I created a new set of screenshots with a fresh installation of WordPress RC and TT5 trunk. I added links to each original 480px screenshot below the related embedded image.)

#### Default

H6 same size as H5, heavier weight, uppercase, wider letter spacing

![Default headings at 1,200 pixels wide](https://github.com/user-attachments/assets/350f5277-227d-4968-91e7-eb1764772b66)

[Default style at 480px](https://github.com/user-attachments/assets/f078c88c-f5bf-463e-b791-b24c20ae9584)

#### Evening

H6 same size as H5, heavier weight, uppercase, wider letter spacing

![Evening headings at 1,200 pixels wide](https://github.com/user-attachments/assets/7ee7c738-ffe2-490e-baaf-323030981576)

[Evening style at 480px](https://github.com/user-attachments/assets/14eeae36-de81-49ad-a247-f058c9560553)

#### Noon

H6 smaller size than H5, heavier weight, uppercase, wider letter spacing

![Noon headings at 1,200 pixels wide](https://github.com/user-attachments/assets/10cd8268-b0f0-40ee-ac63-cfc838186b8c)

[Noon style at 480px](https://github.com/user-attachments/assets/1685e6b3-520e-4227-9c50-7dec58d9a7da)

#### Dusk

H6 smaller size than H5, heavier weight, uppercase, wider letter spacing

![Dusk headings at 1,200 pixels wide](https://github.com/user-attachments/assets/568026d2-598a-410a-8b99-868c8fb20557)

[Dusk style at 480px](https://github.com/user-attachments/assets/6942679e-d00e-4594-9dca-a2a25665496b)

#### Afternoon

H6 smaller size than H5, same `400` weight, less letter spacing, no `text-transform`

![Afternoon headings at 1,200 pixels wide](https://github.com/user-attachments/assets/701b6301-a2ca-4368-ab73-50a19d99adee)

[Afternoon style at 480px](https://github.com/user-attachments/assets/4b8be1b2-f8ac-416e-8ec3-169cf26ca541)

#### Twilight

H6 same size as H5, heavier weight, uppercase, wider letter spacing

![Twilight headings at 1,200 pixels wide](https://github.com/user-attachments/assets/8b43b6af-e138-41d9-95f9-3415b9631c0c)

[Twilight style at 480px](https://github.com/user-attachments/assets/03b4237c-cb3e-44dc-9860-125b472b63e5)

#### Morning

H6 same size and weight as H5, uppercase, with normal letter spacing for both

![Morning headings at 1,200 pixels wide](https://github.com/user-attachments/assets/7427b275-7708-4b2b-b905-daee0fd9c0bd)

[Morning style at 480px](https://github.com/user-attachments/assets/3bf837ff-1c34-4ece-928b-99aecf2206be)

#### Sunrise

H6 same size as H5, lighter weight, uppercase, wider letter spacing

![Sunrise headings at 1,200 pixels wide](https://github.com/user-attachments/assets/fc34d099-18bf-49bd-bab0-60c892ad6993)

[Sunrise style at 480px](https://github.com/user-attachments/assets/822b8a62-7230-41c2-84be-a9da06dd7e54)

#### Midnight

H6 same size and weight as H5, uppercase, wider letter spacing

![Midnight headings at 1,200 pixels wide](https://github.com/user-attachments/assets/205bff9a-2cf2-40cf-b9fc-5807641c8d11)

[Midnight style at 480px](https://github.com/user-attachments/assets/2577c446-37ba-498d-ada6-4beb4e69daaa)

**Comment by beafialho** [comment]
The sizes and appearance in the screenshots in the comments above are all intended, they use font size presets and Heading 6 has specific letter case occasionally.

The only thing I noticed was Afternoon's H5. It looks bigger because it has `letter spacing 0,5px`. That could be removed, since it creates an illusion that H5 is bigger than H4.

Everything else is looking as expected.

**Comment by troychaplin** [comment]
> The sizes and appearance in the screenshots in the comments above are all intended, they use font size presets and Heading 6 has specific letter case occasionally.
> 
> The only thing I noticed was Afternoon's H5. It looks bigger because it has `letter spacing 0,5px`. That could be removed, since it creates an illusion that H5 is bigger than H4.
> 
> Everything else is looking as expected.

After looking through your screenshot I do see one of the inconsistencies relating to what I mentioned early. In each style the h4 is slightly larger than the h5, except in the afternoon styles. Once the letter spacing is fixed, both the h4 and h5 are the same size, which is inconsistent with every other style option.

That doesn't strike me as being intentional

![Image](https://github.com/user-attachments/assets/5d1dcb4d-139f-4c18-ae2e-2a4af0ac1af3)

**Comment by troychaplin** [comment]
@beafialho Wanted to provide more detail on what might be a needed change. In each theme style the headers get smaller as we go down the list, except for `Noon` and `Afternoon` (note: this screenshot of noon would include the letter spacing changes from #633)

In all the other styles this is the default size of each level of header:

- H1: `var(--wp--preset--font-size--xx-large)`
- H2: `var(--wp--preset--font-size--x-large)`
- H3: `var(--wp--preset--font-size--large)`
- H4: `var(--wp--preset--font-size--medium)`
- H5: `var(--wp--preset--font-size--small)`
- H6: `var(--wp--preset--font-size--small)`

In `Noon` both the H3 and H4 are set as `large`.

In `Afternoon` both the H4 and H5 are set as `medium`

**Proposed change:** make the H4 in Noon medium, and the H5 in afternoon small.

|    | |
| -------- | ------- |
| ![Image](https://github.com/user-attachments/assets/8fc67230-cb59-4272-901a-fe84e64418ac) | ![Image](https://github.com/user-attachments/assets/fd6ff743-0df2-4026-a35e-83b162201a4f) |
| ![Image](https://github.com/user-attachments/assets/81ce1c2b-4d57-4a5b-a965-3110a52287f0) | ![Image](https://github.com/user-attachments/assets/36d3fd96-9d8f-4368-aa42-c1fb9236ce7e) |
| ![Image](https://github.com/user-attachments/assets/d7929468-fe03-40d5-b641-998dbbb05348) | ![Image](https://github.com/user-attachments/assets/3ca6b09f-3d05-4d50-bf90-c2b05ad25b8b) |
| ![Image](https://github.com/user-attachments/assets/7f80fff5-0a08-4aad-900f-9e290675d52d) | ![Image](https://github.com/user-attachments/assets/caec0e82-fe0b-4267-a5ae-e2c37a7f5622) |
| ![Image](https://github.com/user-attachments/assets/16acfb74-28c0-4d30-b222-ee32cc20c044) | |

**Comment by juanfra** [comment]
This one was closed once we merged [#633](https://github.com/WordPress/twentytwentyfive/pull/633)

> The sizes and appearance in the screenshots in the comments above are all intended, they use font size presets and Heading 6 has specific letter case occasionally.

According to @beafialho , the sizes are intended. Like for example, in this [review round](https://github.com/WordPress/twentytwentyfive/issues/538).

@troychaplin please feel free to reopen this issue or create a new one to talk about the proposed changes.

**Comment by troychaplin** [comment]
> This one was closed once we merged [#633](https://github.com/WordPress/twentytwentyfive/pull/633)
> 
> > The sizes and appearance in the screenshots in the comments above are all intended, they use font size presets and Heading 6 has specific letter case occasionally.
> 
> According to [@beafialho](https://github.com/beafialho) , the sizes are intended. Like for example, in this [review round](https://github.com/WordPress/twentytwentyfive/issues/538).
> 
> [@troychaplin](https://github.com/troychaplin) please feel free to reopen this issue or create a new one to talk about the proposed changes.

I'm good to leave this closed, perhaps there's a reason, I just found this to be an odd one.
