### ISSUE TITLE
Post Formats: Consider hiding the post titles

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#631]
While testing out post formats which are a really cool part of the theme, I was wondering if we can find a solution to avoid the following result. If a user creates a **Quote** post format, for example, and they add a pullquote block because they want to use that style, visually, this result is not ideal because the content, title and date are misaligned. They can always left-align it of course, but the default isn't great.

![Image](https://github.com/user-attachments/assets/a40f6ce2-80b8-4c91-b70d-77e6fe5e7100)

Secondly, the **Aside** post format currently shows a title, and it is [typically styled without one](https://justintadlock.com/archives/2012/09/06/post-formats-aside).

![Image](https://github.com/user-attachments/assets/0fd81a84-8ae8-4f43-9966-5d3013f94330)

Perhaps there's a way to hide post titles?

**Comment by juanfra** [comment]
@beafialho, in which context is that? Loop or singular? I believe the answer would be loop, but I just want to confirm.

**Comment by carolinan** [comment]
The editor does not support either.

**Comment by carolinan** [comment]
To clarify:
The query loop can not have different blocks for different formats, post types etc, **within the same loop**.
WordPress does not support  / include a single post template that is only applied to a format. It is not part of the template hierarchy.
The reason why classic themes can do this, is that they use PHP conditions to display different things depending on if a format is used or not.

In theory, a theme can use a render_block filter to change the output of the post title block. But it would take away the option from the user, and it may not be suitable to use this type of filter in a default theme.

**Comment by beafialho** [comment]
> @beafialho, in which context is that? Loop or singular? I believe the answer would be loop, but I just want to confirm.

This would be loop, yes.

Alright, I imagined something like this wouldn't be possible, but thought of raising it up regardless. Thank you for your input.

**Comment by carolinan** [comment]
Hopefully next year. Because right now with these limitations, post formats are not that usable.
