### ISSUE TITLE
Color palette and font presets are not shown as selected when the combined variation is active

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#634]
**Description**

I am lifting this out of https://github.com/WordPress/twentytwentyfive/pull/237
In this issue I am trying to summarize and find out why the matching color and typography presets are not showing as selected under
Appearance > Editor > Styles.

But I am hesitant to address this if the colors are going to be changed in any of the open pull requests, it will create more work and merge conflicts.

---
**Dusk:**
I made a file comparison and the color preset and the combined variation do match, so I can't tell why the Dusk color palette is not selected when the Dusk theme variation is selected.

---

**Morning**
I made a file comparison, and in the color preset, there is a difference in the button styles for **section style four**:

Theme variation:
```
"button": {
						"color": {
							"background": "var:preset|color|accent-1",
							"text": "var:preset|color|contrast"
						},
						":hover": {
							"color": {
								"background": "color-mix(in srgb, var(--wp--preset--color--accent-1) 85%, transparent)",
								"text": "var:preset|color|contrast"
							}
						}
					},
```
Color preset:

```
					"button": {
						"color": {
							"background": "var:preset|color|accent-1",
							"text": "var:preset|color|contrast"
						},
						":hover": {
							"color": {
								"background": "color-mix(in srgb, var(--wp--preset--color--accent-1) 85%, transparent)"
							}
						}
					},
```

If the button text color is added to the color preset, then the Morning color palette shows as selected when the Morning theme variation is selected.

---

**Midnight**

I did a file comparison and in the Midnight color preset file, the duotone is missing.
If the duotone is added to settings > colors, then the Midnight color palette shows as selected when the Midnight theme variation is selected.

**Comment by carolinan** [comment]
@beafialho @juanfra 
As Bea noted in #237, Afternoon and the preset does not match, but I found that it is not related to 237, it also happens on "trunk".
When I did a file comparison between the Afternoon theme style variation and its typography preset, the typography styles are very different.
I believe that when Afternoon was updated in https://github.com/WordPress/twentytwentyfive/pull/564, the typography preset was simply missed.

**Comment by juanfra** [comment]
Thanks Carolina, I'll be working to fix this.

**Comment by carolinan** [comment]
When I do I file comparison between the Sunrise theme style variation and typography preset 6, 
the typography preset has this extra block style, which is not present in Sunrise:
```
			"core/query-title": {
				"typography": {
					"fontWeight": "800"
				}
			},
```

**Comment by carolinan** [comment]
And finally, when comparing Midnight with typography preset 7, the` elements > button > typography` is not the same:

Midnight:
```
				"typography": {
					"fontFamily": "var:preset|font-family|literata",
					"fontSize": "var:preset|font-size|medium",
					"fontWeight": "400",
					"letterSpacing": "-0.01em",
					"textTransform": "uppercase"
				},
```
Preset 7:
```
			"button": {
				"typography": {
					"fontFamily": "var:preset|font-family|literata",
					"fontWeight": "400",
					"textTransform": "uppercase"
				}
			},
```

**Comment by beafialho** [comment]
Thanks for opening this issue, Carolina.

That's right, they were perhaps missed when I did the reviews to each variation, so let's make sure they match with the following descriptions I left when I reviewed them:

- #549: Midnight
- #538: Afternoon
- #613: Sunrise
