### ISSUE TITLE
Main Footer: Missing theme name

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#637]
The main footer is currently missing the theme's name. After removing the copyright (original intention), the footer was mistakenly left with a white space on the left. The fact that there's nothing on the left makes the footer's design unbalanced.

If this is happening in other footers, we should replace what previously had `© 2025` with `Twenty Twenty-Five`.

| Currently      | Intended |
| ----------- | ----------- |
|  ![Image](https://github.com/user-attachments/assets/44e40dd3-51c7-4030-b513-0a9a95ba8be8) | ![Image](https://github.com/user-attachments/assets/71ed9a46-c74f-4f74-90d0-a551cfb8ff3e)    |

**Comment by carolinan** [comment]
Please make sure that you have reset the footer template part to use the footer from the theme, not one that was previously saved.
I am not able to reproduce this.

**Comment by alaminfirdows** [comment]
I also can't reproduce this. Perhaps you have templates saved from an earlier version.

**Comment by beafialho** [comment]
This is happening in 2025.wordpress.net.

**Comment by juanfra** [comment]
@beafialho I just checked and the theme name is included by resetting the template there. The one tiny side effect is that the site logo looks big now. What's the desired size there?

**Comment by beafialho** [comment]
Thank you for checking @juanfra! I have updated the size of the site logo.

I'll close this issue, since it's not a bug.
