### ISSUE TITLE
Block Patterns - About -  Overlapping images and paragraph on the right

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#64]
**Description**

🛠️ The goal of this issue is to track the implementation of the `About -  Overlapping images and paragraph on the right` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1817&t=IqDHO3nwfV13Hcvm-1)

![About_ Overlapping images and paragraph on the right](https://github.com/user-attachments/assets/3f81f15d-a94b-4881-801e-d046c1ca0f0d)

**Comment by shail-mehta** [comment]
I would like to work on this pattern.

**Comment by shail-mehta** [comment]
Can we use css in this pattern to overlap images ?

**Comment by hanneslsm** [comment]
> Can we use css in this pattern to overlap images ?

It can be done with negative margin.

**Comment by shail-mehta** [comment]
PR: https://github.com/WordPress/twentytwentyfive/pull/252
