### ISSUE TITLE
"Skip to content" should have an ID

### ISSUE THREAD

**Issue by philliproth** [WordPress/twentytwentyfive#643]
For accessibility it would be nice to have a "skip to content" link with an ID. This way if a "back to top" link is implemented in any way it can target the button and the very top of the page. "#" or "#top" usually works in every browser visually, but nothing would get focus.

Simply add an id="skip-link".

**Comment by carolinan** [comment]
Hi
Skip to content links in block themes targets the ID `#wp--skip-link--target`.  This ID is added to the `<main>` element and this is a built-in functionality in WordPress core, it is not specific to this theme.

**Comment by philliproth** [comment]
Ah wrong repo then. And I meant the other way around: when one wants to target the top of the page. Closing, I'll open an issue in core. Thank you!

**Comment by carolinan** [comment]
Please see https://github.com/WordPress/gutenberg/issues/50433 I actually built this for Gutenberg, but people downvoted it because they did not see the need for this block to be in core.

**Comment by philliproth** [comment]
While I like the idea of such a block (would definitely use it often!) it would not solve the issue that it needs a focusable target.
