### ISSUE TITLE
Default single post template: "Post meta" Layout breaks when there are many categories

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfive#644]
**Description**

By chance I was testing a Gutenberg PR with the theme test data installed.
In the theme test data there is a post with many categories. This is an edge case, but in this post,
the number of categories breaks the layout of the row block that displays the author name and categories below the featured image.

**Step-by-step reproduction instructions**
Install https://github.com/WordPress/theme-test-data
View the Edge Case: Many Categories post.

**Screenshots**

![Image](https://github.com/user-attachments/assets/87ac4619-5ea4-40e3-a65e-99131b971a70)

**Additional context**

By enabling the option "Allow to wrap to multiple lines" on the parent row block, the design could be preserved like this:
![Image](https://github.com/user-attachments/assets/c77ed6f5-5406-4474-8087-7dc8b4f0673e)

**Comment by beafialho** [comment]
Good catch!

**Comment by alaminfirdows** [comment]
@carolinan I've resolved this by following your hints; simply changing the flexWrap from `nowrap` to `wrap` fixed it.

I've already modified this and can push it immediately. May I submit a PR for this?

**Comment by juanfra** [comment]
@alaminfirdows yes please, open a PR with the fix if you have it ready.

**Comment by alaminfirdows** [comment]
@juanfra I've submitted the PR (#648)
Thank you.

**Comment by juanfra** [comment]
Thanks!
