### ISSUE TITLE
Can't change the color of a single part?

### ISSUE THREAD

**Issue by 369work** [WordPress/twentytwentyfive#647]
**Description**

When customizing a theme, I want to set individual background colors and text colors for the header and footer of template parts.
When I make changes and save them, the colors of all template parts change to the same color I just saved.
I get the same result (all the same color) whether I use a pattern or a template.
What should I do?

https://github.com/user-attachments/assets/9cf5958d-47cc-4c5a-9187-c0db1d96e224

**Comment by juanfra** [comment]
Hi @369work - Thank you for opening the issue.

The section that you're opening to change the header and footer background color is the "Styles" section. That means that anything that you change there will have an impact on the entire site. The background color for footers and headers can be set individually. You can check how to do it in the following screencast.

https://github.com/user-attachments/assets/5c29d7cc-fae8-4b8f-99b8-dc4494a7e913

I'm using section styles in the screencast, but you can also use the color section to pick any color from the colorpicker.

**Comment by 369work** [comment]
Thank you.
I finally understand it.
Now I can use the block editor with confidence.
I would be happy if it was more intuitive for beginner users who want to customize themes.

**Comment by juanfra** [comment]
Thank you!
