### ISSUE TITLE
Block Patterns - About - Image on the right, heading and paragraph

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#65]
**Description**

🛠️ The goal of this issue is to track the implementation of the `About - Image on the right, heading and paragraph` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1767&t=IqDHO3nwfV13Hcvm-1)

![About_ Image on the right, heading and paragraph](https://github.com/user-attachments/assets/33698b16-d268-4611-b575-93ebd9c6ae29)

**Comment by shail-mehta** [comment]
@juanfra I would like to work on this pattern.

**Comment by shail-mehta** [comment]
PR: https://github.com/WordPress/twentytwentyfive/pull/137
