### ISSUE TITLE
Too many "no results found" messages

### ISSUE THREAD

**Issue by annezazu** [WordPress/twentytwentyfive#651]
In testing both on my own and with some friends/family, I noticed that there are many different "no results found" messages in the different versions of the homepage. I worry about this as the new default theme in terms of folks just starting out vs folks with content switching to this theme:

https://github.com/user-attachments/assets/69bb73fa-e7d3-4435-a3b2-616112395f5c

Can we reduce the number of these at all? It creates a rough initial experience for someone just starting out but I am not deeply involved in this work to understand why and if we would provide more default content somehow to work around this.

**Comment by jasmussen** [comment]
I don't think Twenty Twenty-Five can fix this, so I opened [this issue](https://github.com/WordPress/gutenberg/issues/66548) instead.

**Comment by carolinan** [comment]
Yes, the short message "No results found" is from the query loop block and can not be removed or edited by the user.

The longer "Sorry, but..." is from the no results block, which has already been reduced to one per "section".
Perhaps it could also be removed from the sidebar.

**Comment by annezazu** [comment]
Thank you for figuring out the root! Let's close this out in favor of https://github.com/WordPress/gutenberg/issues/66548
