### ISSUE TITLE
The borders of the quote block are not visible for some color variations and sections.

### ISSUE THREAD

**Issue by alaminfirdows** [WordPress/twentytwentyfive#653]
**Description**
The borders of the quote block are not clearly visible with certain color themes and in different sections.

For the default color theme, the borders appear fine, but when I switch to a different color theme or change the section color, they become hard to see. The borders should be visible across all themes. It looks like this block is using the contrast color for the border, but I think it would be better to use the `currentColor` instead.

**Expected behavior**
The borders should be visible across all themes.

**Reproduction Instructions:**

1. Start by creating a new page or post.
2. Add a "Group" block and apply "Section Style 5" to it.
3. Within this group, insert a "Quote" block.
4. Preview the page or post.

**Screenshots**
![Image](https://github.com/user-attachments/assets/03f68a39-a272-433e-abc7-95685d2c94c1)
![Image](https://github.com/user-attachments/assets/bae01381-913e-4b9c-8312-dd53b9bfa61e)

**Comment by alaminfirdows** [comment]
I'm working on this and will submit the PR once I receive confirmation from the maintainer.

**Comment by carolinan** [comment]
Does the border even need a color defined? If it is not defined it will always inherit the text color.

**Comment by alaminfirdows** [comment]
Yes, you’re correct. Removing the color attribute should fix this issue.

**Comment by alaminfirdows** [comment]
However, I discovered additional issues with the Sunrise style. It is overriding the color, border-color, and some other attributes. This creates visibility problems due to the accent-2 color.

Additionally, the pullquote block is experiencing the same issue.

```./twentytwentyfive/styles/07-sunrise.json```
![Image](https://github.com/user-attachments/assets/d4a9d0b6-6101-4312-9a05-0a33633792cb)

**Comment by carolinan** [comment]
Yes the text color problem is more serious, the border is not necessary for understanding the content.

**Comment by juanfra** [comment]
Closed as fixed with https://github.com/WordPress/twentytwentyfive/pull/619
