### ISSUE TITLE
Post Date block color are not visible for some color variations and sections style 5.

### ISSUE THREAD

**Issue by ariful93** [WordPress/twentytwentyfive#657]
**Description**
The post date block text color are not visible for Afternoon, Twilight, Midnight variation and section style 5

**Step-by-step reproduction instructions**

1. Start by creating a new page or post.
2. Add a "Group" block and apply "Section Style 5" to it.
3. Within this group, insert a "Post Date" block.
4. Preview the page or post.

**Expected behavior**
The post date block text color should be visible across Afternoon, Twilight and Midnight themes.

**Screenshots**
![Image](https://github.com/user-attachments/assets/7838da62-55e4-4cbc-a15b-8ff30179db38)

**Comment by carolinan** [comment]
Thank you I was just about to open this issue.
It is also not visible in the default variation in section style four and five.

The first date is the plain text. The second date is with the link option enabled:
![Image](https://github.com/user-attachments/assets/aef3597c-c585-491d-ac54-d59602ce9aa9)

**Comment by carolinan** [comment]
Evening:
![Image](https://github.com/user-attachments/assets/b0e173a2-5563-4c5b-9674-639ecd72c345)
Noon:
![Image](https://github.com/user-attachments/assets/de861f1c-e495-46ad-bc55-c8aeb680b943)
Dusk:
![Image](https://github.com/user-attachments/assets/c90cbfc8-bf75-4d4c-a79a-4c9f2baecb8d)

Perhaps it may be most suitable to solve this in https://github.com/WordPress/twentytwentyfive/pull/619

**Comment by beafialho** [comment]
This has been addressed in #619.
