### ISSUE TITLE
Comment form button border radius doesn't work properly for some color variations

### ISSUE THREAD

**Issue by ariful93** [WordPress/twentytwentyfive#659]
**Description**
Comment form button border radius doesn't work properly for Dusk, Afternoon, Morning, Sunrise, and Midnight color variations

**Step-by-step reproduction instructions**

1. Start by creating a new page or post.
2. Within this, insert a "Comment form" block.
3. Preview the page or post.

**Expected behavior**
Comment form button border radius doesn't work properly for Dusk, Afternoon, Morning, Sunrise, and Midnight color variations

**Screenshots**
Default, Evening, Noon, Twilight
![Image](https://github.com/user-attachments/assets/986d529d-9666-4ed3-8b02-1892686e99bf)

Dusk, Afternoon, Morning, Sunrise, Midnight
![Image](https://github.com/user-attachments/assets/f2cc0628-c597-49ba-8aa7-58c8fcaa05c4)

**Comment by juanfra** [comment]
Hi @ariful93 - Thanks for opening the issue.

The border radius for those variations is intended. You can see the designs [here](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=77-298&t=JUwznlNgSAcGtHkz-1). I'm closing this issue for now.
