### ISSUE TITLE
Block Patterns - About - Detailed description with bullets

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#66]
**Description**

🛠️ The goal of this issue is to track the implementation of the `About - Detailed description with bullets` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1768&t=IqDHO3nwfV13Hcvm-1)

![About_ Detailed description with bullets](https://github.com/user-attachments/assets/6ca6f0d1-faf8-4769-9fb6-9c486c9a721f)

**Comment by shail-mehta** [comment]
PR: https://github.com/WordPress/twentytwentyfive/pull/120
