### ISSUE TITLE
The footer rises on a 4K monitor

### ISSUE THREAD

**Issue by 369work** [WordPress/twentytwentyfive#661]
If the amount of content is small, the footer will be at the bottom in Full HD and there will be no problem, but in 4K there will be blank space below the footer.
Can this be fixed with a CSS media query?

WordPress6.7 RC2
TwentyTwentyfive![Image](https://github.com/user-attachments/assets/69c1d280-6f88-4dc9-84ed-ebacce04198a)

**Comment by carolinan** [comment]
Hi, this type of footer is already being discussed here https://github.com/WordPress/gutenberg/issues/47043

**Comment by 369work** [comment]
Thank you for always teaching me so many things. I appreciate it.
