### ISSUE TITLE
Expected patterns to be fullwidth so that section styles work

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfive#665]
**Description**
I expected these patterns used would be full width, so that one could apply section styles to them without the patterns looking broken. Reviewing based on [this Playground link](https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fraw.githubusercontent.com%2FWordPress%2Fblueprints%2Ftt5demo%2Fblueprints%2Ftt5-demo%2Fblueprint.json). 

**Screenshots**

![Image](https://github.com/user-attachments/assets/db3f5467-0eda-4379-8fde-f592c5ce1324)

**Comment by carolinan** [comment]
Please, I am asking you again to please write complete issues and include the names of  the patterns that are problematic, thank you.

**Comment by juanfra** [comment]
Thanks! That playground link isn't working for me, it's taking me to a site where TT5 is not installed. 

I've created a PR to address this on the news blog home, [here](https://github.com/WordPress/twentytwentyfive/pull/666).
