### ISSUE TITLE
Block Patterns - About - FAQs

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#67]
**Description**

🛠️ The goal of this issue is to track the implementation of the `About - FAQs` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-2076&t=IqDHO3nwfV13Hcvm-1)

![About_ FAQs](https://github.com/user-attachments/assets/ed315603-8b81-4ec2-80b9-d7bd894b841f)

**Comment by iamsam2e** [comment]
Going to tackle this

**Comment by juanfra** [comment]
Thank you.

**Comment by juanfra** [comment]
Unfortunately, the "Accordion" block will likely not land in 6.7. Therefore, we need to move forward using the "Details" block for this pattern.

cc @beafialho @carolinan

**Comment by beafialho** [comment]
I have replaced the previous design with [a new one](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-2076&t=x3ohS9FzCA6av35S-4) using the details block on Figma.

**Comment by juanfra** [comment]
Thanks Bea!
