### ISSUE TITLE
WooCommerce: Cart page text color & border color are not visible for some color variation

### ISSUE THREAD

**Issue by ariful93** [WordPress/twentytwentyfive#672]
**Description**
WooCommerce cart page change address text color and product cart item border color are not visible for some color variation

**Step-by-step reproduction instructions**
1. WooCommerce cart page
2. Cart totals 'Change Address' text
3. Product cart item border
4. Preview WooCommerce cart page

**Expected behavior**
WooCommerce cart page change address text color and product cart item border color are not visible for color variation Evening, Twilight, Sunrise & Midnight

**Screenshots**

Default, Noon, Dusk, Afternoon & Morning
![Image](https://github.com/user-attachments/assets/4d5400b1-fe2d-4cd9-8725-065b46c42b74)

Evening, Twilight, Sunrise & Midnight
![Image](https://github.com/user-attachments/assets/40c6a34d-78d3-46cb-ad8b-cbc79237e119)

**Comment by carolinan** [comment]
Hi
It is not possible for the theme to adapt to individual plugins. Please re-open any issues related to WooCommerce in the WooCommerce GitHub repository instead:
https://github.com/woocommerce/woocommerce/
