### ISSUE TITLE
Mobile Navigation Modal trends towards being obscured by body content / restricted by containing DIV

### ISSUE THREAD

**Issue by quix-cafe** [WordPress/twentytwentyfive#673]
**Description**
Upon customization of the 2025 Theme Navigation, I keep having to chase down bugs that result in the Modal pop-up of the Mobile-version "hamburger" menu being either restricted by the containing DIV of the Nav, or being z-indexed below the body content. I believe this is because the Modal tag is being placed within the Nav, rather than separately after the Body tag. 

**Step-by-step reproduction instructions**

**Expected behavior**
A full-screen modal menu pops up

**Screenshots**
The portion that intersects with the Header is the only part visible.

**Environment info**
Reproducible on Firefox, Chrome, Mobile Firefox, Mobile Chrome

**Comment by carolinan** [comment]
I am afraid I am struggling to understand what you mean.

Without more information, there is no way for me to help determine if the problem is with the theme, the customisations, or with the block itself.

And I am not sure what a "Modal tag" is.

**Comment by carolinan** [comment]
The navigation must be inside a `<nav>` element, because the menu must be a semantic navigation, even on smaller screens.
The markup for the menu is added by the block, not by the theme. The theme only positions the navigation block and adds color and typography styles.

**Comment by quix-cafe** [comment]
I've learned so much about Blocks in the past 24 hours -- my apologies -- you are absolutely correct that themes no longer effect the code that I was looking at. I'm a bit of a dinosaur -- cheers!
