### ISSUE TITLE
Update "Call to Action" to "Call to action"

### ISSUE THREAD

**Issue by jasmussen** [WordPress/twentytwentyfive#674]
In general, the pattern UI, inserter, and block editor uses sentence case, not titlecase, for all UI. Should we update the pattern category to match? See also "Post format", "My patterns", etc.

 ![Image](https://github.com/user-attachments/assets/207346be-6678-441b-9667-248879620fb0)

![Image](https://github.com/user-attachments/assets/eaaea026-46ac-45fb-845b-0d2d7364b88e)

**Comment by juanfra** [comment]
Thanks for reporting @jasmussen - It makes sense.

I can see this is coming from core, specifically [here](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-patterns.php#L77). I'll open a trac issue and create a PR for it later today.

**Comment by jasmussen** [comment]
Thanks so much. I don't think it's super urgent, but good to track!

**Comment by juanfra** [comment]
Thank you! I'm closing this one in favor of https://core.trac.wordpress.org/ticket/62414
