### ISSUE TITLE
Block Patterns - Search - Big heading and search form

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#71]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Search - Big heading and search form` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1781&t=IqDHO3nwfV13Hcvm-1)

![Search_ Big heading and search form](https://github.com/user-attachments/assets/ad0bfd14-a2a4-405a-89d8-52d2209562c2)

**Comment by jenniferfarhat** [comment]
Hello, I created a [PR](https://github.com/WordPress/twentytwentyfive/pull/166) that includes this pattern creation. Thanks in advance for your review.
