### ISSUE TITLE
Block Patterns - Services - Three-column boxed pricing table 

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#76]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Services - Three-column boxed pricing table` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1809&t=IqDHO3nwfV13Hcvm-1)

![Pricing_ 3-column boxed pricing table](https://github.com/user-attachments/assets/e2b44c86-ec59-4bee-b69f-fa5978584b56)

**Comment by noruzzamans** [comment]
I have been working on these patterns
