### ISSUE TITLE
Block Patterns - Services - Subscriber only section

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#77]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Services - Subscriber only section` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1808&t=IqDHO3nwfV13Hcvm-1)

![Services_ Subscriber only section](https://github.com/user-attachments/assets/ddff6609-98fd-4b11-80c2-6c88815751a0)

**Comment by noruzzamans** [comment]
I want to work on these patterns. I have faced an issue: I did not export the image

**Comment by juanfra** [comment]
👋 Thank you @noruzzamans 

You can find the image in the following attachment: 

[screens.webp.zip](https://github.com/user-attachments/files/16847607/screens.webp.zip)
