### ISSUE TITLE
Block Patterns - Events - Three columns with event images and title

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#84]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Events - Three columns with event images and title` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1803&t=IqDHO3nwfV13Hcvm-1)

![Events_ 3 columns with event images and title](https://github.com/user-attachments/assets/a975ad8d-a5fb-4a32-95c5-4a18df30daee)

**Comment by dballari** [comment]
Hi, I would like to contribute to the theme with this pattern. May I?

**Comment by juanfra** [comment]
Hi @dballari - Absolutely, no need to ask! Thank you very much
