### ISSUE TITLE
Block Patterns - Hero - Overlapped book cover with links

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#86]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Hero - Overlapped book cover with links` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1794&t=IqDHO3nwfV13Hcvm-1)

![Hero_ Overlapped book cover with links](https://github.com/user-attachments/assets/f2444e2a-b176-4c9e-8ef0-e214ccab60cc)

**Comment by Arkenon** [comment]
Hello, I would like to start contributing to the theme with this issue.

**Comment by juanfra** [comment]
Thank you!

**Comment by Arkenon** [comment]
Hi, I am working on the pattern.

I could not find the book image here: https://tinyurl.com/tt5-images

By the way, this will be my first contribution, so the development process will be a bit slow, I apologize in advance for that.

**Comment by juanfra** [comment]
Thanks @Arkenon ✨

You can find the image in the following zip file.

[book-image.webp.zip](https://github.com/user-attachments/files/16871410/book-image.webp.zip)

**Comment by Arkenon** [comment]
Update:

[screen-capture (1).webm](https://github.com/user-attachments/assets/97b4d96e-1bd0-4aac-8a1d-c8d2f3719481)

The desktop version is ready. But it needs some development on mobile. It will be ready soon.

Thanks...

**Comment by Arkenon** [comment]
Hi, I have created a new PR #309
