### ISSUE TITLE
Block Patterns - Hero - Full-width cover image, heading and short paragraph

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#87]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Hero - Full-width cover image, heading and short paragraph` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1795&t=IqDHO3nwfV13Hcvm-1)

![Intro_ Full width cover image, heading and short paragraph](https://github.com/user-attachments/assets/ace23ce9-27a0-45c3-9968-65882eb2b129)

**Comment by jonnywatersbb** [comment]
I'll have a go at this today

**Comment by juanfra** [comment]
Thank you!
