### ISSUE TITLE
Block Patterns - Hero - Short heading and paragraph and image on the right

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#88]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Hero - Short heading and paragraph and image on the right` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1796&t=IqDHO3nwfV13Hcvm-1)

![Intro_ Short heading and paragraph and image on the right](https://github.com/user-attachments/assets/e2efddbc-8903-47e4-8409-03a215d14dc9)

**Comment by kishanjasani** [comment]
@juanfra I would love to work on this. I am working on it.

**Comment by juanfra** [comment]
@kishanjasani that's great! thank you for working on this, I've just assigned it to you.
