### ISSUE TITLE
Block Patterns - Hero - Left-aligned description

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#89]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Hero - Left-aligned description` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3177-1797&t=IqDHO3nwfV13Hcvm-1)

![Intro_ Left-aligned description](https://github.com/user-attachments/assets/8ec47153-9c81-47b6-8a4d-7b176362ebcc)

**Comment by karmatosed** [comment]
Assigning to myself to take on when presets are added. This like all patterns is blocked by #36

**Comment by juanfra** [comment]
@karmatosed thank you! the presets are already merged so everything should ready now.

**Comment by jasmussen** [comment]
I saw a comment by @carolinan separately, that "Fleurs.co" should not be referenced, as it's a URL that we don't control. IIRC the recommendation was to just go with "Fleurs"? CC: @beafialho

**Comment by juanfra** [comment]
Thanks for pointing that out Joen. Indeed, here's [the link](https://github.com/WordPress/twentytwentyfive/issues/130#issuecomment-2312299870) to the conversation.

**Comment by beafialho** [comment]
That's correct, thank you @jasmussen. We can go with Fleurs instead of Fleurs.co.
