### ISSUE TITLE
Block Patterns - Hero - Podcast

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfive#91]
**Description**

🛠️ The goal of this issue is to track the implementation of the `Hero - Podcast` pattern. 
🧑‍💻 The implementation must follow the [pattern creation guidelines](https://github.com/WordPress/twentytwentyfive/blob/trunk/README.md#pattern-creation-guidelines), and should be assigned to its appropriate category.
🎨 [Figma design](https://www.figma.com/design/dzGCSntVch4EQdVERTqyVK/Twenty-Twenty-Five?node-id=3181-2243&t=IqDHO3nwfV13Hcvm-1)

![Hero_ Podcast](https://github.com/user-attachments/assets/3044f239-45f4-43c7-9683-ab805a5fd828)

**Comment by iamsam2e** [comment]
Gonna work on this and snag this today! :D

**Comment by iamsam2e** [comment]
Issue attempted to resolve in #105

**Comment by iamsam2e** [comment]
@juanfra I moved the PR to #124 setting up new computer and TLDR I stuffed it 🤦🏽
